cloudwalk/stratus

- Cargo.lock
- Cargo.toml
- src/eth/executor.rs
- src/eth/primitives/block_header.rs
- src/eth/primitives/log_mined.rs
- src/eth/rpc/mod.rs
- src/eth/rpc/rpc_context.rs
- src/eth/rpc/rpc_server.rs
- src/eth/rpc/rpc_subscriptions.rs
Initial work for supporting subscriptions.
* newHeads (emitted when a new block is mined).
* logs (emitted for transactions logs).
> feat: subscriptions

- .github/CODEOWNERS
- .gitignore
- Cargo.lock
- Cargo.toml
- Dockerfile
- docker-compose.yaml
- e2e-contracts/test-contracts.sh
- e2e/hardhat.config.ts
- e2e/test/e2e.test.ts
- e2e/test/helpers/network.ts
- justfile
- src/eth/rpc/rpc_server.rs
- src/infra/tracing.rs
- src/main.rs
- move from ledger to stratus
- add CODEOWNERS
> project name

- Cargo.lock
- Cargo.toml
- src/config.rs
- src/eth/rpc/rpc_server.rs
- src/main.rs
* Load config from env.
* Define short and long arg flags.
* Bump clap.
> feat: config improvements

- .github/workflows/doc-test.yml
- .github/workflows/unit-test.yml
- justfile
- Add action to run unit tests in the docs
- Add action to run unit tests in the library
- Change justfile to use stable rust instead of nightly for `test-doc`
> test: add actions to run automatically

- .github/workflows/lint-check.yml
- justfile
- Add `lint-check` to justfile
- Update lint-check workflow to use just
> chore: add lint-check to justfile

- Cargo.lock
- Cargo.toml
- src/eth/primitives/log_filter.rs
- src/eth/primitives/log_filter_input.rs
- src/eth/primitives/mod.rs
- src/eth/rpc/rpc_server.rs
- src/eth/rpc/rpc_subscriptions.rs
* Using Subscription ID as String instead of number to be compatible with Geth client.
* Fix log filter:
* It can receive multiple address.
* It can received multiple combination of topics.
> feat: subscriptions improvements

- src/config.rs
- src/main.rs
* Configure number of async threads.
* Configure number of blocking threads.
* Configure number of evms.
> feat: make number of threads and evms configurable

- e2e/contracts/TestContract.sol
- e2e/package-lock.json
- e2e/package.json
- e2e/test/e2e.test.ts
- e2e/test/helpers/account.ts
- e2e/test/helpers/rpc.ts
- justfile
- src/eth/primitives/transaction_input.rs
* Using Axios to send RPC requests because Ethers.JS just does not send parallel requests.
* Configured a scenario sending multiple transaction in parallel to detect conflicts.
> test: testing execution of parallel transactions

- .github/workflows/e2e-test.yml
- e2e/test/e2e.test.ts
- e2e/test/helpers/rpc.ts
- justfile
- src/eth/primitives/slot.rs
- src/eth/rpc/rpc_server.rs
This is needed for blockscout. Test case added.
> feat: add eth get storage at

- .gitignore
- justfile
simple command to easy run e2e tests for postgres
> just command to run postgres tests

- Cargo.lock
- update github repos dependencies to latest commit
- fixes https://github.com/cloudwalk/stratus/security/dependabot/6
- fixes https://github.com/cloudwalk/stratus/security/dependabot/7
> deps: update git repos and fix alerts

- e2e-contracts/test-contracts.sh
- justfile
Parameters and justfile options to run specific contract tests
> improvements to run specific contract tests

- e2e/test/e2e-tx-serial-transfer.test.ts
- e2e/test/helpers/rpc.ts
- src/eth/primitives/block_header.rs
- Fix block timestamp to be current time
- Add e2e test case for timestamp
- Add e2e test case for parent hash
> fix: block timestamp

- Cargo.toml
- src/bin/rpc_server_poller.rs
This pull request introduces a multiple binaries architecture to the Stratus codebase. The aim is to enhance modularity, facilitate focused development and testing, streamline maintenance, and bolster the security posture by isolating critical components.
As Stratus grows in complexity and scope, the need for a scalable and maintainable codebase becomes crucial. A monolithic binary approach is increasingly unwieldy, making updates and maintenance challenging. Furthermore, it does not leverage the potential security benefits of isolation between components. By implementing a multiple binaries architecture, we can achieve:
> chore: create rpc_server_poller

- e2e-contracts/clone-contracts.sh
- e2e-contracts/test-contracts.sh
Adds new Yield streamer contracts
Adds PixCashier contracts
> adding pix cashier and yield streamer contracts

- src/bin/rpc_server_poller.rs
- src/eth/executor.rs
- src/eth/primitives/transaction_input.rs
- src/eth/storage/inmemory/inmemory_account.rs
later we will save those transactions footprint to generate a NONCE and process multiple transactions
> chore: execute transactions on EVM

- src/eth/primitives/transaction_input.rs
Otherwise we have a panic when chain id is not set. Stopping all the process
> chore: bypass chain id validation

- src/eth/storage/eth_storage.rs
- src/eth/storage/inmemory/inmemory.rs
- src/eth/storage/metrified.rs
- src/eth/storage/mod.rs
- src/eth/storage/overlay.rs
- src/eth/storage/postgres/postgres.rs
closes https://github.com/cloudwalk/stratus/issues/143
> add save_account_changes method to InMemory storage

- .github/workflows/doc-test.yml
- .github/workflows/e2e-test.yml
- .github/workflows/lint-check.yml
- .github/workflows/unit-test.yml
Test actions will now have a `workflow_dispatch` trigger option
> test: add manual trigger to actions

- src/eth/storage/eth_storage.rs
- src/eth/storage/inmemory/inmemory.rs
- src/eth/storage/metrified.rs
- src/eth/storage/mod.rs
- src/eth/storage/overlay.rs
- src/eth/storage/postgres/postgres.rs
#179 needed to be reverted due to failing e2e tests that weren't caught in the Actions. This PR brings it back
> Bring #179 back to main

- src/eth/primitives/nonce.rs
> fix: nonce conversion and add regression test

- src/eth/primitives/wei.rs
> fix: port the fix and test made for Nonce to Wei

- src/eth/evm/revm.rs
https://github.com/cloudwalk/stratus/issues/201
Next part will be the regression test and then the usage of gas limit coming from the transaction itself.
> fix: unlimited gas limit

- src/eth/evm/evm.rs
- src/eth/executor.rs
Creation of `EvmInput` is evolving to accept multiple parameters, so creating factory methods can give a better context of which method to use to create it instead of relying on implicit tuple conversions.
> refactor: use factory methods insteaf From trait to create EvmInput

- .github/workflows/_setup-e2e.yml
- .github/workflows/e2e-contracts.yml
- .github/workflows/e2e-test.yml
- e2e-contracts/clone-contracts.sh
- e2e-contracts/remove-contracts.sh
- e2e-contracts/test-contracts.sh
- justfile
- Change cloning approach to https
- Automate e2e contract test run
> test: add contracts e2e action

- Cargo.toml
- e2e/test/e2e-json-rpc.test.ts
- src/eth/executor.rs
- src/eth/miner/block_miner.rs
- src/eth/primitives/unix_time.rs
- src/eth/rpc/rpc_server.rs
- src/ext.rs
there are some improvements to be made for the changes in #223, namely a few changes on the new rpc method tests, feature flags, variable name changes, and improving evm_setNextBlockTimestamp implementation.
> chore: improve changes made in #223

- justfile
- src/bin/rpc_server_poller.rs
Justfile adjustments
Fix the way the mock stops
> Fix flamegraph details

- src/eth/evm/evm.rs
- src/eth/executor.rs
- src/eth/primitives/execution.rs
- src/eth/primitives/execution_value_change.rs
- src/eth/primitives/external_receipt.rs
- src/eth/primitives/wei.rs
Implements and fixes https://github.com/cloudwalk/stratus/issues/272
> feat: reexecute external transactions assuming gas price zero

- src/eth/rpc/rpc_server.rs
> chore: add error details

- Cargo.lock
- Cargo.toml
- justfile
- src/eth/storage/inmemory/inmemory_permanent.rs
- src/infra/metrics.rs
- tests/test_import_offline_snapshot.rs
* Test is running with PostgreSQL.
* Testcontainer initial adoption.
> feat: run block importer with postgres instead of inmemory

- src/bin/importer_offline.rs
- src/bin/rpc_downloader.rs
- src/config.rs
- src/infra/postgres.rs
- tests/test_execution.rs
- tests/test_import_offline_snapshot.rs
Defines max_connection and acquiring connection timeout for Postgres.
> Configurable postgres connections

- justfile
- src/eth/storage/csv/csv_exporter.rs
adds `historical_slots` table to CsvExporter
> feat: add historical slots table to CsvExporter

- justfile
- src/eth/storage/csv/csv_exporter.rs
adds `historical_nonces` table to CsvExporter
> feat: adds historical_nonces table to CsvExporter

- justfile
- src/eth/storage/csv/csv_exporter.rs
adds `topics` table to CsvExporter
> feat: adds topics table to CsvExporter

- justfile
- src/eth/primitives/miner_nonce.rs
- src/eth/storage/csv/csv_exporter.rs
adds `blocks` table to CsvExporter
> feat: add blocks table to csv exporter

- justfile
- src/eth/primitives/execution_value_change.rs
- src/eth/storage/csv/csv_exporter.rs
Exporting accounts, but handling of NULL values in CSV is not working yet.
> feat: export accounts

- src/eth/storage/hybrid/mod.rs
I will revisit this in the future (after we're passing all the tests), I don't really like how this was implemented.
> fix: pending task lock logic error (hybrid)

- src/eth/rpc/rpc_server.rs
it was not returning the actual status code
> fix: health and readiness probe

- src/config.rs
- src/globals.rs
- src/infra/tracing.rs
* Enum for log format.
* Sentry exporter only if Sentry is enabled.
* Consistent log messages on initialization.
> feat: improving tracing initialization

- utils/block-time-check.sh
> test(clock): reduce duration to 60s

- e2e-contracts/integration/package-lock.json
- e2e/package-lock.json
Fixes
- https://github.com/cloudwalk/stratus/security/dependabot/24
- https://github.com/cloudwalk/stratus/security/dependabot/25
> deps(braces): bump to 3.0.3

- justfile
> remove postgres tests from justfile

- src/eth/consensus/mod.rs
this will later be used so we can check the append entries validity
> chore: send forward term and index

- e2e/test/automine/e2e-json-rpc.test.ts
Reverts cloudwalk/stratus#1159
> Revert "test: queries for non-existant blocks should return null"

- src/eth/primitives/block_selection.rs
- src/eth/primitives/log_filter.rs
- src/eth/primitives/log_filter_input.rs
- src/eth/rpc/rpc_client_app.rs
- src/eth/rpc/rpc_middleware.rs
- src/eth/rpc/rpc_parser.rs
- src/eth/rpc/rpc_server.rs
- src/eth/rpc/rpc_subscriptions.rs
- src/ext.rs
Added RPC method "debug_readSubscriptions" to list all actives subscriptions in a server.
> feat: debug_readSubscriptions

- .github/CODEOWNERS
We're not relying on code reviews for now
> remove CODEOWNERS

- e2e/cloudwalk-contracts/clone-contracts.sh
- e2e/cloudwalk-contracts/patches/brlc-periphery.patch
- e2e/cloudwalk-contracts/remove-contracts.sh
- justfile
> update brlc periphery

- .github/workflows/build-binary.yml
Already manually tested, this PR removes the "feature flag" (comments on push), so now the action runs automatically.
closes #1192
> enable build binary

- .github/workflows/build-binary.yml
- .github/workflows/e2e-consensus.yml
- .github/workflows/e2e-contracts-rocks.yml
- .github/workflows/e2e-contracts.yml
- .github/workflows/e2e-relayer.yml
- .github/workflows/e2e-test.yml
- .github/workflows/lint-check.yml
- .github/workflows/unit-test.yml
I forgot to wrap the paths in single quotes, and to add `**` to directories
> fix(actions): quotes in paths

- .gitmodules
- justfile
Adding hive tool as submodule
```
git submodule init
git submodule update
```
```
just hive
```
```
just hiveview
```
will be available at http://127.0.0.1:8080/
> Add hive test tool

- src/eth/consensus/append_log_entries_storage.rs
if we have a logindex mismatch we need to evaluate what can we do, because of the append-only nature of our blockchain storage.
> chore: return error if we have a conflict appending entries

- .github/workflows/e2e-contracts-rocks.yml
- .github/workflows/e2e-contracts.yml
- .github/workflows/merge-gatekeeper.yml
- e2e/cloudwalk-contracts/clone-contracts.sh
- e2e/cloudwalk-contracts/test-contracts.sh
They are not required to merge
> test(contracts): add brlc pix cashier v3

- .github/workflows/e2e-contracts-rocks.yml
- .github/workflows/e2e-contracts.yml
- .github/workflows/merge-gatekeeper.yml
- e2e/cloudwalk-contracts/clone-contracts.sh
- e2e/cloudwalk-contracts/patches/brlc-periphery-v2.patch
- e2e/cloudwalk-contracts/test-contracts.sh
> test(contracts): add brlc periphery v2

- docker/Dockerfile.run_relayer
- docker/Dockerfile.run_stratus
- docker/Dockerfile.run_with_importer
- docker/Dockerfile.run_with_importer_cached
When merging #1231 I forgot to change the dockerfiles as well
> fix rust version in Dockerfiles

- src/ext.rs
> Put traced sleep behind feature flag

- src/eth/executor.rs
First step to have serial execution fallback.
> refactor: extract local transaction execution to execute_local_transaction_until

- src/eth/block_miner.rs
- src/eth/primitives/block_header.rs
> Fill block `size` field

- e2e/hardhat.config.ts
this will be used when we have a simulation of loadbalancer/consensus
> chore: add custom address for hardhat

- .github/workflows/e2e-contracts-rocks.yml
- .github/workflows/e2e-contracts.yml
- .github/workflows/merge-gatekeeper.yml
- e2e/cloudwalk-contracts/clone-contracts.sh
- e2e/cloudwalk-contracts/test-contracts.sh
Add pix cashier v4 to CI tests pipeline
> test(contracts): pix cashier v4

- chaos/experiments/leader-election.sh
This PR fixes consensus e2e restart not working.
> fix: consensus e2e restart not working

- src/eth/rpc/rpc_server.rs
We used to rely on `readiness` and `liveness` when running `stratus` with Kubernetes.
We now need a single probe for running `stratus` in VMs, so `/health` is an AND between
`readiness` and `liveness`.
In other words: `/health` tells when `stratus` is ready and isn't shutting down.
> feat: create the `/health` probe endpoint

- src/eth/block_miner.rs
Using an internal Mutex for now because changing everythin to `&mut self` will required a lot more refactoring.
> feat: block-miner mining and commit operations does not allow parallel access

- Cargo.toml
- src/eth/consensus/mod.rs
- src/eth/consensus/server.rs
- src/eth/storage/mod.rs
- src/eth/storage/permanent_storage.rs
- tests/test_import_external_snapshot_rocksdb.rs
> chore: remove not rocks feature flag

- src/bin/importer_offline.rs
- src/bin/importer_online.rs
- src/bin/relayer.rs
- src/eth/consensus/mod.rs
- src/eth/executor/executor.rs
- src/eth/miner/miner.rs
- src/eth/rpc/mod.rs
- src/eth/rpc/rpc_context.rs
- src/eth/rpc/rpc_server.rs
- src/eth/rpc/rpc_subscriptions.rs
- src/globals.rs
* Enable/disable miner.
* Enable/disable unknown clients.
* Refactoring to GlobalState.
> feat: stratus admin methods

- config/importer-offline.env.local
to account for the recent spans renaming
> chores: update `importer-offline.env.local`

- src/eth/rpc/rpc_server.rs
when adding the /health probe, I accidentally removed a piece of the metrics call, this commit fixes that and reuses existing code
> fix: readiness metric on /health probe

- e2e/test/external/e2e-json-rpc.test.ts
- e2e/test/helpers/rpc.ts
JSON-RPC: state, metadata, gas, account, block, logs, sendRawTransaction
> test: migrate automine to external (part 1)

- src/bin/run_with_importer.rs
- src/config.rs
- src/eth/rpc/mod.rs
- src/eth/rpc/rpc_config.rs
- src/eth/rpc/rpc_context.rs
- src/eth/rpc/rpc_server.rs
- src/main.rs
Refactors RPC server config into its own config, removing duplicate configuration.
> chore: refactor rpc server config

- .github/workflows/e2e-generic.yml
- remove nested trigger (lint bug?)
- clone and flatten only necessary contract
- decrease job name size
> ci: improve e2e generic action

- e2e/test/automine/e2e-tx-parallel-contract.test.ts
if sending the same transaction multiple times, it should only succeed once
> e2e-test: send repeated transaction in parallel

- src/eth/rpc/rpc_client_app.rs
Enhancement
___
- Added new categorizations for `stratus`, `authorizer`, and `insomnia` in the `RpcClientApp` implementation.
- Organized existing categorizations into sections with comments for better readability.
- Improved the `name` matching logic to ensure more accurate categorization.
___
<tr>
<td>
<details>
<summary><strong>rpc_client_app.rs</strong><dd><code>Enhance RPC client categorization logic with new categories</code></dd></summary>
<hr>
src/eth/rpc/rpc_client_app.rs
<li>Added new categorizations for <code>stratus</code>, <code>authorizer</code>, and <code>insomnia</code>.<br> <li> Organized existing categorizations into sections with …
> enha: more rpc-client categorization

- build.rs
Enhancement, Error handling
___
- Replaced `unwrap` with `expect` to provide more detailed error messages in `generate_proto_structs` and `parse_contract`.
- Introduced type aliases `ContractAddress` and `ContractName` to improve code readability and maintainability.
- Enhanced error handling in `parse_contract` and `parse_signature` functions to provide more context-specific error messages.
- Added `SolidityId` enum to distinguish between different Solidity identifiers, improving type safety and code clarity.
- Updated `populate_contracts_map` and `populate_signature_maps` to use new type aliases and enums, ensuring consistency across the codebase.
___ …
> enha: improve error handling in build.rs removing replacing unwrap with detailed expect

- src/eth/primitives/block.rs
- src/eth/primitives/block_filter.rs
- src/eth/primitives/external_block.rs
- src/eth/primitives/external_receipt.rs
- src/eth/primitives/log_mined.rs
- src/eth/primitives/stratus_error.rs
- src/eth/primitives/transaction_input.rs
- src/eth/primitives/transaction_stage.rs
- src/eth/rpc/rpc_context.rs
- src/eth/rpc/rpc_middleware.rs
- src/eth/rpc/rpc_server.rs
- src/eth/storage/external_rpc_storage.rs
- src/eth/storage/postgres_external_rpc/postgres_external_rpc.rs
- src/ext.rs
- src/infra/blockchain_client/blockchain_client.rs
- src/infra/build_info.rs
- src/infra/tracing/tracing.rs
- tests/test_import_external_snapshot_common.rs
Enhancement
___
- Changed import of `JsonValue` from `ext` to `alias` across multiple modules.
- Removed `JsonValue` type alias from `ext.rs`.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><details><summary>18 files</summary><table>
<tr>
<td>
<details>
<summary><strong>block.rs</strong><dd><code>Update `JsonValue` import in block module</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
src/eth/primitives/block.rs
- Changed import of `JsonValue` from `ext` to `alias`.
</details>
</td>
<td><a href="https://github.com/cloudwalk/stratus/pull/1559/files#diff-1713a99b45fd64ac0570786603a3a17edc97657646bd333e5e214e4a531def10" …
> refactor: alias::JsonValue

- src/eth/rpc/rpc_middleware.rs
Unrealiable numbers.
___
Enhancement, Other
___
- Removed the `active_requests` module, which included the `ActiveRequests` struct and its methods for incrementing and decrementing active RPC request counts.
- Deleted the `PinnedDrop` implementation for `RpcResponse`, which previously decremented the active request count on drop.
- Removed metrics tracking calls related to active RPC requests in the `RpcServiceT` implementation.
___
<tr>
<td>
<details>
<summary><strong>rpc_middleware.rs</strong><dd><code>Remove active RPC requests tracking and related metrics</code>&nbsp; &nbsp; </dd></summary>
<hr>
src/eth/rpc/rpc_middleware.rs
<li>Removed the …
> chore: remove rpc_requests_active

- static/diagrams/components.pik
- static/diagrams/components.svg
Documentation, Enhancement
___
- Introduced a new `Consensus Layer` to the diagram, including `Consensus` and `BlockchainClient` components.
- Adjusted padding variables and updated dimensions for better layout consistency.
- Modified existing arrows and added new ones to reflect the new `Consensus Layer` connections.
- Added descriptive labels for `App`, `Core`, and `Storage` layers to improve diagram clarity.
___
<tr>
<td>
<details>
<summary><strong>components.pik</strong><dd><code>Add Consensus Layer and Update Diagram Layout</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr> …
> doc: consensus module and headers

- .github/workflows/pr-agent.yml
configuration changes, enhancement
___
- Updated the AI review model in the GitHub Actions workflow from `gpt-4o` to `anthropic/claude-3-5-sonnet-20240620`.
- Added a new configuration `config.model_turbo` for the AI model.
- Included `anthropic.key` for authentication purposes.
___
<tr>
<td>
<details>
<summary><strong>pr-agent.yml</strong><dd><code>Update AI review model to Claude Sonnet and add configurations</code></dd></summary>
<hr>
.github/workflows/pr-agent.yml
<li>Changed AI review model from <code>gpt-4o</code> to <br><code>anthropic/claude-3-5-sonnet-20240620</code><br> <li> Added <code>config.model_turbo</code> configuration<br> <li> …
> ci: change AI review model to claude sonnet

- src/infra/build_info.rs
This fixes local LSP errors.
I can't tell if this will fail again for someone after some time, or why it's giving errors.
> chore: fix rust-analyzer issue

- src/eth/executor/executor.rs
- src/eth/miner/miner.rs
- src/eth/rpc/rpc_subscriptions.rs
* Tracing span behind feature-flag is cheaper than tracing::instrument.
* Remove unnecessary clones.
___
Enhancement
___
- Improved performance in the importer-offline tracing hot path:
- Replaced `tracing::instrument` with conditional `info_span!` for better performance in executor and miner
- Removed unnecessary clones and optimized metrics handling in executor
- Enhanced efficiency in transaction handling:
- Changed `notifier_pending_txs` to broadcast `Hash` instead of `TransactionExecution`
- Updated RPC subscriptions to work with transaction hashes instead of full executions
- Reduced redundant logging:
- Removed logging of lock acquisitions in miner
- Added `cfg_if` for conditional compilation of metrics-related code
- Minor code cleanup and formatting improvements
___ …
> perf: improve importer-offline tracing hot path

- src/eth/miner/miner.rs
- src/eth/rpc/rpc_subscriptions.rs
* Clone only block header instead of entire block when sending block to notifications.
* Do not clone header and logs if does not have subscribers.
___
Enhancement
___
- Optimized block notification process by sending only the block header instead of the entire block, reducing data transfer and improving performance.
- Implemented checks for subscriber count before cloning and sending notifications, avoiding unnecessary operations.
- Updated RPC subscriptions to work with `BlockHeader` instead of `Block`, maintaining consistency with the new notification system.
- Improved logging and error handling in the miner commit process.
- Added `itertools` crate usage for more efficient data manipulation.
___ …
> perf: improve miner commit clones

- src/eth/storage/inmemory/inmemory_permanent.rs
Enhancement
___
- Improved performance of the `InMemoryPermanentStorage` implementation by reducing unnecessary cloning operations when saving blocks
- Simplified the process of storing transactions and logs in the state
- Removed the conditional check for successful transactions when storing logs, now storing all logs regardless of transaction status
- These changes should result in faster block saving and reduced memory usage
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Performance optimization</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>inmemory_permanent.rs</strong><dd><code>Optimize InMemoryPermanentStorage block saving process</code>&nbsp; &nbsp; &nbsp; </dd></summary>
<hr> …
> perf: InMemoryPermanent less cloning when saving block

- src/eth/rpc/rpc_server.rs
- src/globals.rs
Enhancement
___
- Refactored `GlobalState` from an empty struct to a fully-fledged struct with fields representing various global state flags.
- Implemented `Serialize` and `Deserialize` traits for `GlobalState`, enabling easy serialization and deserialization of the global state.
- Updated `get_internal_state_as_json()` to use the new `GlobalState` struct, improving code consistency and maintainability.
- Added necessary `serde` imports to support serialization and deserialization functionality.
- This change enhances the structure and usability of the global state, making it easier to manage and serialize application-wide settings.
___
<tr>
<td> …
> chore: improve global state

- src/eth/executor/executor.rs
applicable when importing external blocks
___
Enhancement
___
- Improved error logging for mismatching receipts when importing external blocks
- Enhanced the `tracing::error!` macro call in the `Executor` implementation to include detailed error information
- The change allows for better debugging and troubleshooting of issues related to transaction reexecution
- This improvement is particularly relevant when importing external blocks
___
<tr>
<td>
<details>
<summary><strong>executor.rs</strong><dd><code>Enhance error logging for transaction reexecution</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr> …
> enha: improve error for mismatching receipts

- src/eth/follower/importer/importer.rs
- src/eth/miner/miner.rs
Enhancement
___
- Optimized the use of the "metrics" feature in the importer module by adding a conditional compilation directive for the `receipts_len` variable.
- Refactored the tracing-related imports in the miner module to use conditional compilation, improving code organization and reducing unnecessary imports when the "tracing" feature is not enabled.
- Removed unused imports to clean up the code.
___
<tr>
<td>
<details>
<summary><strong>importer.rs</strong><dd><code>Optimize metrics feature usage in importer</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr> …
> chore: solve warnings

- Cargo.lock
- Cargo.toml
- justfile
- src/bin/importer_offline.rs
- src/bin/rocks_revert_to_block.rs
- src/bin/rpc_downloader.rs
- src/eth/primitives/log_filter.rs
- src/main.rs
Enhancement
___
- Added support for Jemalloc as a global allocator with optional profiling
- Introduced new feature flags: 'jemalloc' and 'jeprof' for enabling Jemalloc and its profiling capabilities
- Updated src/main.rs to conditionally use Jemalloc when the appropriate features are enabled
- Modified Cargo.toml to include tikv-jemallocator dependency and new feature definitions
- Added a new command in justfile for running Stratus with memory profiling enabled
- Reformatted some dependency specifications in Cargo.toml for improved readability
___
<tr>
<td>
<details>
<summary><strong>main.rs</strong><dd><code>Add Jemalloc global allocator …
> feat: add jemalloc and jeprof feature flags

- .github/workflows/comment-tag-report.yml
- .github/workflows/outdated.yml
- change from daily to weekly
- change from 7am to 9am, since it's UTC, it'll be 6am in BRT
___
Enhancement
___
- Changed the schedule for both Comment Tag Report and Outdated Check workflows from daily to weekly
- Updated the execution time from 7 AM to 9 AM UTC for both workflows
- Set both workflows to run every Monday
- Added comments in the YAML files to clarify the new schedule and timezone
___
<tr>
<td>
<details>
<summary><strong>comment-tag-report.yml</strong><dd><code>Update Comment Tag Report schedule</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
> chore: increase crontabs time windows

- src/eth/storage/rocks/rocks_state.rs
Bug fix
___
- Fixed a critical issue in the block reversion process for historical accounts and slots
- Improved the logic to properly skip future blocks' slots and accounts during reversion
- Moved the deletion of historical entries after checking if the block should be deleted
- Added conditional updating of last_account and last_slot based on whether the block should be deleted
- Ensures that the most up-to-date state is maintained after block reversion
- Improves data consistency and prevents potential data loss during block reversion
___
<tr>
<td>
<details>
<summary><strong>rocks_state.rs</strong><dd><code>Fix block reversion logic for historical …
> fix: block revert bin not skipping future blocks slots and accounts

- e2e/test/external/e2e-tx-serial-transfer.test.ts
- justfile
___
- Added new E2E test file `e2e-tx-serial-transfer.test.ts` for testing serial transfer transactions
- Implements tests for transactions up to EIP-155 and EIP-1559
- Covers transaction creation, block creation, receipt verification, and balance changes
- Includes tests for both regular and new account transfers
- Fixed test parameter handling in `justfile` for e2e-stratus and e2e-stratus-rocks commands
- Added quotes around the {{test}} parameter to properly handle test names with spaces
___
<tr>
<td>
<details>
<summary><strong>e2e-tx-serial-transfer.test.ts</strong><dd><code>Add E2E tests for serial transfer transactions</code>&nbsp; …
> test: migrate automine to external (part 3)

- src/eth/storage/rocks/rocks_state.rs
regression test for https://github.com/cloudwalk/stratus/pull/1616
___
Tests
___
- Added a regression test `regression_test_read_logs_without_providing_filter_address` in `src/eth/storage/rocks/rocks_state.rs`
- The test verifies the functionality of reading logs without providing a filter address
- Creates 100 blocks with 200 logs in total and checks if all logs are retrieved when using an empty address filter
- Ensures compatibility with the changes made in https://github.com/cloudwalk/stratus/pull/1616
___
<tr>
<td>
<details>
<summary><strong>rocks_state.rs</strong><dd><code>Add regression test for reading logs without filter address</code></dd></summary> …
> test: regression: read_logs without address

- src/eth/storage/rocks/rocks_permanent.rs
This PR solves errors from RocksDB not being always displayed
___
___
- Implemented comprehensive error logging for RocksDB operations in the `RocksPermanentStorage` struct
- Added `inspect_err` calls to log errors for all major storage operations (read_account, read_slot, read_block, etc.)
- Improved error visibility for debugging and monitoring purposes
- Made minor code formatting adjustments for better readability
- Ensures that all errors from the RocksDB storage layer are now properly displayed
___
<tr>
<td>
<details>
<summary><strong>rocks_permanent.rs</strong><dd><code>Enhance error logging in …
> fix: output all errors from the rocks storage layer

- src/bin/rocks_revert_to_block.rs
Enhancement, Error handling
___
- Added validation to check if the target block number is valid before attempting to revert
- Implemented error handling to prevent reverting to a future block
- Added a warning message when the target block is equal to the current block
- Improved error logging by including the target block number in the error message
- Refactored the code to use the `cmp` method for comparing block numbers
- Added necessary imports for new functionality (`std::cmp::Ordering`, `anyhow::bail`, `stratus::eth::storage::PermanentStorage`)
___
<tr>
<td>
<details>
<summary><strong>rocks_revert_to_block.rs</strong><dd><code>Enhance block …
> enha: revert-block binary: throw error if target block is invalid

- src/bin/importer_offline.rs
…y consumption
___
Enhancement
___
- Modified all `tracing` macro calls in `importer_offline.rs` to include `parent: None`
- This change prevents tracing spans from building up, reducing memory consumption
- Affected logging statements include error, info, and other tracing levels
- No functional changes to the importer's behavior, only logging modifications
___
<tr>
<td>
<details>
<summary><strong>importer_offline.rs</strong><dd><code>Set tracing parents to None in importer_offline</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
src/bin/importer_offline.rs
<li>Added <code>parent: None</code> to all …
> chore: set importer-offline's tracing parents to None to reduce memory buildup

- e2e/cloudwalk-contracts/integration/package-lock.json
- e2e/package-lock.json
- e2e/rpc-mock-server/package-lock.json
___
- Updated Nomicfoundation dependencies in e2e/cloudwalk-contracts/integration/package-lock.json:
* @nomicfoundation/edr and related packages from 0.3.8 to 0.5.2
* @nomicfoundation/hardhat-chai-matchers from 2.0.6 to 2.0.7
* @nomicfoundation/hardhat-verify from 2.0.7 to 2.0.10
- Added @nomicfoundation/slang and related packages at version 0.17.0
- Updated Express and related dependencies in e2e/rpc-mock-server/package-lock.json:
* body-parser from 1.20.2 to 1.20.3
* express from 4.19.2 to 4.20.0
- Various minor dependency updates and bug fixes
___
<tr>
<td>
<details>
<summary><strong>package-lock.json</strong><dd><code>Update …
> deps: npm audit fix

- src/eth/follower/importer/importer_config.rs
- src/eth/rpc/rpc_server.rs
Enhancement
___
- Moved importer initialization logic from `rpc_server.rs` to `importer_config.rs`
- Added `init_follower_importer` method to `ImporterConfig` struct
- Improved error handling and state management in importer initialization
- Updated `stratus_init_importer` in RPC server to use the new method
- Removed redundant `init_importer` function from `rpc_server.rs`
___
<tr>
<td>
<details>
<summary><strong>importer_config.rs</strong><dd><code>Add follower importer initialization method</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr> …
> enha: move importer init function to importer module

- Cargo.lock
- Cargo.toml
- src/eth/rpc/rpc_parser.rs
- src/eth/rpc/rpc_server.rs
Enhancement
___
- Implemented CORS middleware for the RPC server to improve compatibility with Blockscout v6
- Added CORS configuration to allow POST method and any origin/headers
- Enhanced type safety in RPC parameter parsing functions by explicitly specifying lifetimes
- Updated dependencies to include CORS-related packages
___
<tr>
<td>
<details>
<summary><strong>rpc_parser.rs</strong><dd><code>Enhance type safety in RPC parameter parsing</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
src/eth/rpc/rpc_parser.rs
<li>Updated lifetime parameter in <code>next_rpc_param</code> and …
> feat: add cors middleware for compatibility with blockscout v6

- .github/workflows/e2e-leader-follower.yml
- justfile
- utils/deploy.sh
Enhancement
___
- Added a new deployment script (`utils/deploy.sh`) for managing leader-follower node setup:
* Implements health checks and state validation for both nodes
* Manages role switching between leader and follower
* Handles transaction enabling/disabling during the process
* Includes detailed logging and error handling
- Updated the E2E workflow (`e2e-leader-follower.yml`) to include a 'deploy' test in the matrix
- Modified the `justfile` to integrate the new deploy script into the e2e-leader-follower-up recipe:
* Added a condition to run the deploy script
* Implemented error handling for the deploy script execution
- These changes enhance the deployment and testing processes for the leader-follower setup
___ …
> feat: add initial deploy script

- utils/deploy.sh
Enhancement
___
- Implemented a more robust pending transactions check mechanism:
- Added configuration variables for total check attempts, required consecutive checks, and sleep interval
- Replaced single check with a loop that performs multiple attempts
- Introduced a consecutive success counter to ensure stability
- Improved logging and readability:
- Updated color definitions for better visual distinction
- Added more detailed status messages, including attempt numbers
- Enhanced error handling and exit conditions based on the new check mechanism
- Maintained existing functionality for disabling transactions and changing leader to follower
___
<tr> …
> enha: add consecutive pending transaction check

- utils/deploy/deploy.py
Enhancement
___
- Improved consistency in log messages by using `role.name` instead of `role` for better readability
- Updated capitalization of 'Leader' and 'Follower' to 'LEADER' and 'FOLLOWER' in log messages for emphasis
- Enhanced error messages to use `role.name`, providing more precise information about node roles
- These changes improve the overall clarity and consistency of log outputs in the deployment process
___
<tr>
<td>
<details>
<summary><strong>deploy.py</strong><dd><code>Enhance node role naming in log messages</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
> chore: improve leader and follower naming

- e2e/test/automine/e2e-tx-parallel-contract.test.ts
- e2e/test/external/e2e-tx-parallel-contract.test.ts
Tests
___
- Added a new test file `e2e-tx-parallel-contract.test.ts` to test parallel transactions with smart contracts
- Implemented three main test suites:
1. Parallel transactions with TestContractBalances
2. Parallel transactions with TestContractCounter
3. Sending repeated transactions in parallel
- Each test suite includes blockchain reset, contract deployment, and initial state verification
- Tests cover scenarios such as successful parallel transactions, handling failures due to insufficient balance, and attempting to send repeated transactions
- Utilizes helper functions for RPC calls, contract deployment, and transaction management
___
<tr>
<td> …
> test: migrate automine to external (part 5)

- e2e/test/external/e2e-tx-parallel-transfer.test.ts
Tests
___
- Introduced a new end-to-end test file for parallel transfer transactions
- Implemented test cases to verify the functionality of parallel transfers:
- Reset blockchain to ensure a clean state
- Send multiple transactions in parallel from different accounts
- Verify successful execution of all transactions
- Confirm correct final balance of the recipient
- Utilized helper functions for RPC calls and account management
- Included both funded and unfunded accounts in the test scenario
- Ensured proper error handling and balance verification
___
<tr>
<td>
<details>
<summary><strong>e2e-tx-parallel-transfer.test.ts</strong><dd><code>Add parallel transfer …
> test: migrate automine to external (part 6)

- src/eth/rpc/rpc_middleware.rs
* Always create a new root span when a new RPC request is started.
* Drop request span after processing span instead of letting JSON-RPC drop it later.
___
___
- Ensure RPC request spans are always created as root spans by adding `parent: None` to the span creation.
- Improve response handling in the `RpcResponse` future:
- Move response processing inside the `Poll::Ready` block for better organization.
- Explicitly drop the middleware span and remove it from extensions to prevent potential memory leaks.
- Enhance code comments for better clarity and documentation.
- Refactor response tracking and metrics collection for improved readability.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td>< …
> fix: ensure rpc::request is always a new root span

- justfile
- utils/deploy/deploy.py
Enhancement
___
- Improved clarity of deploy script arguments by renaming them:
- `--leader` is now `--current-leader`
- `--follower` is now `--current-follower`
- Updated `justfile` to use the new argument names when calling the deploy script
- These changes enhance the readability and maintainability of the deployment process
___
<tr>
<td>
<details>
<summary><strong>deploy.py</strong><dd><code>Improve deploy script argument naming</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
utils/deploy/deploy.py
<li>Renamed command-line argument …
> chore: improve deploy script arg naming

- justfile
- utils/deploy/deploy.py
___
- Fixed argument parsing in `deploy.py` by correcting the names from `args.leader` and `args.follower` to `args.current_leader` and `args.current_follower`.
- Added error handling for Config initialization in `deploy.py`, raising a DeploymentError with specific error types.
- Improved error checking in the `justfile` for the deploy script execution, exiting immediately if a deploy script fails.
- Enhanced logging in the `justfile` to provide clearer feedback on deploy script success or failure.
- Restructured the deploy script execution loop in the `justfile` for better readability and error handling.
___
<tr>
<td>
<details> …
> fix: validate deploy args

- utils/deploy/deploy.py
Enhancement
___
- Enhanced the deployment script by modifying how leader and follower addresses are formatted.
- Appended `/?app=deploy` to both leader and follower addresses in the `Config` initialization.
- This change ensures that the deployment script uses the correct URL format when connecting to leader and follower nodes.
- The modification improves the specificity of the deployment process by explicitly targeting the deploy application.
___
<tr>
<td>
<details>
<summary><strong>deploy.py</strong><dd><code>Modify address formatting in deployment configuration</code>&nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
utils/deploy/deploy.py …
> chore: update deploy script arg naming and addresses

- .github/workflows/_setup-e2e.yml
- .github/workflows/build-binary.yml
- .github/workflows/check-features.yml
- .github/workflows/comment-tag-report.yml
- .github/workflows/doc-test.yml
- .github/workflows/docs-release.yml
- .github/workflows/e2e-contracts-rocks.yml
- .github/workflows/e2e-contracts.yml
- .github/workflows/e2e-leader-follower.yml
- .github/workflows/e2e-test.yml
- .github/workflows/int-test.yml
- .github/workflows/lint-check.yml
- .github/workflows/merge-gatekeeper.yml
- .github/workflows/outdated.yml
- .github/workflows/pr-agent.yml
- .github/workflows/unit-test.yml
Enhancement
___
- Standardized string quotes across all workflow files, changing single quotes to double quotes for consistency.
- Added "rust-toolchain.toml" to the list of paths that trigger workflows on push, ensuring that changes to the Rust toolchain configuration are properly captured.
- Adjusted indentation in several files to use 2 spaces consistently, improving readability and adherence to YAML best practices.
- Removed trailing whitespace and unnecessary newlines in some files.
- Updated matrix contract list formatting in e2e-contracts workflows for better readability.
- Minor formatting improvements and consistency updates across all modified files.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Formatting</strong></td><td> …
> style: lint actions and propagate rust toolchain

- Cargo.lock
- Cargo.toml
- src/eth/rpc/rpc_middleware.rs
- src/infra/tracing/tracing_services.rs
Enhancement
___
- Implemented active request tracking using jsonrpsee counters in the RPC middleware
- Added metrics for active requests using the `ConnectionGuard` from jsonrpsee
- Removed temporary metrics from events in the tracing services
- Simplified event field mapping and removed the `event_to_metrics` function
- Updated jsonrpsee dependency to version 0.24.5
___
<tr>
<td>
<details>
<summary><strong>rpc_middleware.rs</strong><dd><code>Implement active request tracking with jsonrpsee</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
src/eth/rpc/rpc_middleware.rs
<li>Added import for …
> feat: track active requests using jsonrpsee counters

- .github/workflows/e2e-leader-follower.yml
Enhancement
___
- Added `workflow_dispatch` event to the e2e-leader-follower.yml workflow
- This change allows manual triggering of the leader-follower test workflow
- Enhances flexibility in CI/CD process by enabling on-demand execution
___
<tr>
<td>
<details>
<summary><strong>e2e-leader-follower.yml</strong><dd><code>Add manual trigger to leader-follower workflow</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
.github/workflows/e2e-leader-follower.yml
- Added `workflow_dispatch` event trigger to the workflow
</details>
</td>
<td><a href="https://github.com/cloudwalk/stratus/pull/1747/files#diff-6cb0 …
> ci: add workflow dispatch to leader follower

- Cargo.lock
- Cargo.toml
Enhancement
___
- Updated the `futures-util` dependency in `Cargo.toml` from version 0.3.30 to 0.3.31.
- This minor version update may include bug fixes, performance improvements, or new features for the `futures-util` crate.
- The update ensures the project is using the latest compatible version of `futures-util`.
___
<tr>
<td>
<details>
<summary><strong>Cargo.toml</strong><dd><code>Update futures-util dependency version</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
Cargo.toml
- Updated `futures-util` dependency from version 0.3.30 to 0.3.31 …
> chore: fix action `outdated`

- src/eth/rpc/rpc_server.rs
Enhancement
___
- Refactored the `eth_get_logs` function in `rpc_server.rs` to remove the use of `unwrap()`.
- Introduced a `match` statement to safely handle the `Option<BlockNumber>` for `filter.to_block`.
- Updated variable references and logging to use the new `to_block` variable.
- Improved code safety and error handling by eliminating potential panics from `unwrap()`.
- Enhanced code readability and maintainability.
___
<tr>
<td>
<details>
<summary><strong>rpc_server.rs</strong><dd><code>Refactor eth_get_logs to remove unwrap()</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
> chore: remove unwrap in rpc-server

- src/ledger/events.rs
Still missing tests for the main payload because there are pending details to be implemented.
___
___
- Implemented serialization support for `AccountTransfersEvent` and `AccountTransfer` structs using `serde` and `serde_with` crates
- Added `DebugAsJson` and `Serialize` derive macros to relevant structs and enums
- Implemented unit tests for serialization of `AccountTransfer` and `AccountTransferDirection`
- Updated imports to include necessary serialization-related modules
- Adjusted `amount` field in `AccountTransfer` to use `DisplayFromStr` for serialization
- Renamed enum variants in `AccountTransferDirection` for JSON output
- Updated `Address` import to use local crate instead of `revm` crate
___ …
> test: serialization tests for events

- src/ledger/events.rs
Enhancement
___
- Implemented a custom serializer for `AccountTransfersEvent` to provide more control over the serialization process.
- Updated the `serde_event_account_transfers` test to verify the new serialization behavior.
- The custom serializer ensures specific field serialization, including:
- Converting `publication_id` and `block_number` to strings
- Formatting datetimes as RFC3339
- Encoding `function_id` as a prefixed hex string
- Removed the derive macro for `Serialize` from `AccountTransfersEvent` struct.
- Added necessary imports in the test module for new types used.
___
<tr>
<td>
<details> …
> enha: custom serializer for AccountTransfersEvent

- src/ledger/events.rs
Enhancement
___
- Implemented custom serializers for `AccountTransfers`, `AccountTransfer`, and `AccountTransferDirection` instead of using `serde` annotations
- Renamed `AccountTransfersEvent` to `AccountTransfers` for consistency
- Changed `primary_account_address` to `account_address` for clarity
- Removed `idempotency_key` field and added `idempotency_key()` method to generate it dynamically
- Updated serialization format for some fields (e.g., `block_number` now as u64 instead of string)
- Removed dependency on `serde_with` and `DisplayFromStr`
- Updated test case to reflect new structure and serialization format
___
<tr>
<td>
<details> …
> feat: custom serializer for events instead of serde annotations

- docker-compose.yaml
Enhancement
___
- Introduced a new Kafka service to the Docker Compose configuration
- Configured Kafka using the `confluentinc/cp-kafka:7.4.1` image
- Set up Kafka with a single broker (ID: 1) and controller
- Configured listeners for PLAINTEXT, PLAINTEXT_HOST, and CONTROLLER protocols
- Exposed port 29092 for external access to Kafka
- Set up environment variables for optimal Kafka operation in a development environment
- Configured minimal replication factors and ISR for single-node operation
- Added Kafka-specific volume for storing logs
___
<tr>
<td>
<details>
<summary><strong>docker-compose.yaml</strong><dd><code>Add Kafka service to …
> feat: add kafka to compose file

- Cargo.lock
- Cargo.toml
- src/eth/primitives/account.rs
- src/eth/primitives/address.rs
- src/eth/primitives/unix_time.rs
- src/ext.rs
- src/ledger/events.rs
Enhancement
___
- Implemented transaction_to_events function to convert mined transactions into account transfer events
- Added conversions between Address, LogTopic, and DateTime types
- Implemented InfallibleExt for DateTime<Utc>
- Added tests for event parsing and serialization
- Enabled UUID v7 feature in Cargo.toml
- Minor formatting changes and import additions across multiple files
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Formatting</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>account.rs</strong><dd><code>Minor formatting in test_accounts function</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr> …
> feat: parsing transactions to events - part 1

- justfile
- utils/deploy/deploy.py
Enhancement
___
- Implemented persistent logging to file for the deployment process
- Added a new command-line argument `--log-file` to specify the log file path
- Modified the `log` function to write logs to both file and console
- Updated the `justfile` to include log file arguments in deploy script execution
- Separated colored console output from plain text file logging
- Ensured proper file handling with opening and closing of log file
___
<tr>
<td>
<details>
<summary><strong>deploy.py</strong><dd><code>Implement file logging for deployment process</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
> enha: persist deploy logs to file

- utils/deploy/requirements.txt
Enhancement
___
- Created a new `requirements.txt` file in the `utils/deploy/` directory
- Added specific versions of essential Python packages for deployment:
- certifi (2024.8.30)
- charset-normalizer (3.4.0)
- idna (3.10)
- requests (2.32.3)
- urllib3 (2.2.3)
- These dependencies are likely needed for secure HTTP requests and URL handling during deployment
___
<tr>
<td>
<details>
<summary><strong>requirements.txt</strong><dd><code>Add deployment requirements file</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
> chore: add deploy requirements

- src/ledger/events.rs
Enhancement
___
- Implemented full parsing of ERC-20 transfer events to `AccountTransfers` structures
- Added error handling for cases where event data doesn't match expected format
- Updated `transaction_to_events` function to correctly parse transfer amount and generate `AccountTransfer` objects
- Modified test cases to verify correct parsing of transfer events, including amount and direction
- Added JSON formatting assertions to ensure proper serialization of transfer amounts
- Introduced `if_else!` macro for more concise conditional expressions in the code
___
<tr>
<td>
<details>
<summary><strong>events.rs</strong><dd><code>Implement ERC-20 transfer …
> feat: finish parsing events to transfers

- src/ledger/events.rs
Enhancement
___
- Added `transaction_index` field to `AccountTransfers` struct to store the index of the transaction in the block
- Updated serialization logic to include the new `transaction_index` field
- Modified `transaction_to_events` function to populate the `transaction_index` from `TransactionMined`
- Updated test case `ledger_events_serde_account_transfers` to include `transaction_index`
- Improved documentation for existing fields, including format specifications
- Minor formatting changes (e.g., "Number" to "Integer" in some comments)
___
<tr>
<td>
<details>
<summary><strong>events.rs</strong><dd><code>Add transaction index to …
> feat: transaction_index

- justfile
- src/eth/follower/importer/importer_config.rs
- src/eth/rpc/rpc_server.rs
- src/infra/kafka/kafka.rs
- src/infra/kafka/mod.rs
Enhancement
___
- Implemented Kafka SASL and SSL security protocols for secure connections
- Added new configuration options for Kafka security in `ImporterConfig` and `KafkaConfig`
- Introduced `KafkaSecurityProtocol` enum to handle different security protocols (None, SaslSsl, Ssl)
- Updated `KafkaConnector::new` to configure the Kafka client based on the selected security protocol
- Modified `has_kafka_config` method to check for security-specific configurations
- Updated RPC server and justfile to include new Kafka security options
___
<tr>
<td>
<details>
<summary><strong>importer_config.rs</strong><dd><code>Add Kafka security configuration …
> kafka configuration for sasl and ssl

- src/eth/rpc/rpc_middleware.rs
Enhancement
___
- Added Sentry integration to RPC response logging:
- Created a `log_tracing_event` closure to encapsulate the existing event logging logic
- Implemented Sentry scope management to set the RPC client as the Sentry username
- Wrapped the event logging within the Sentry scope for improved error tracking
- Maintained existing logging functionality while enhancing it with Sentry integration
- This change allows for better correlation between RPC clients and Sentry events, improving debugging and error tracking capabilities
___
<tr>
<td>
<details>
<summary><strong>rpc_middleware.rs</strong><dd><code>Enhance RPC logging with Sentry …
> feat: sentry add rpc client as sentry username

- src/infra/kafka/kafka.rs
- src/ledger/events.rs
Enhancement
___
- Enhanced Kafka event publishing mechanism:
- Added support for custom partition keys and headers
- Implemented new methods in the `Event` trait: `event_key`, `event_headers`, and `event_payload`
- Modified `send_event` method in `KafkaConnector` to use these new Event methods
- Improved error handling and logging in Kafka event publishing
- Implemented `event_key` for `AccountTransfers`, using the account address as the key
- Updated dependencies and imports to support new functionality
___
PRDescriptionHeader.CHANGES_WALKTHROUGH
<tr>
<td>
<details>
<summary><strong>kafka.rs</strong><dd><code>Enhance Kafka event publishing with custom …
> feat: kafka partition key and headers

- e2e/cloudwalk-contracts/contracts-clone.sh
- e2e/cloudwalk-contracts/contracts-compile.sh
- e2e/cloudwalk-contracts/contracts-coverage.sh
- e2e/cloudwalk-contracts/contracts-flatten.sh
- e2e/cloudwalk-contracts/contracts-remove.sh
- e2e/cloudwalk-contracts/contracts-test.sh
Enhancement
___
- Added support for the new `brlc-card-payment-processor` repository name across multiple scripts
- Maintained backward compatibility with the old `brlc-periphery` repository name
- Updated cloning, compiling, coverage, flattening, removal, and testing scripts to work with both repository names
- Ensured smooth transition for CardPaymentProcessor and CashbackDistributor contracts
- Updated handling of alternative versions (v2) of the repository
- Improved error handling and fallback mechanisms in case of repository name changes
___
<tr>
<td>
<details>
<summary><strong>contracts-clone.sh</strong><dd><code>Update repository cloning for new …
> ci: add support for new card payment processor repository name

- src/bin/historic_events_processor.rs
Bug fix
___
- Fixed the transaction progress bar in the historic events processor to accurately reflect the number of transactions processed.
- Improved error handling for event sending by simplifying the match statement.
- Optimized block processing by moving the `into_inner()` call earlier in the code.
- Added a `tx_count` variable to track the number of transactions in each block.
- Updated the progress bar increment to use the actual number of transactions processed.
- Maintained existing functionality for block progress tracking and saving the last processed block number.
___
<tr>
<td>
<details> …
> fix: transactions progress bar in historic events processor

- src/eth/follower/importer/importer.rs
sending online events buffered (speed improvement)
___
Enhancement
___
- Implemented buffered sending of Kafka events for improved performance
- Changed from sending individual events to sending events in batches of 30
- Introduced a new error handling mechanism for the buffered sending process
- Removed individual error logging for each event, now returning an error for the entire batch
- This change aims to improve the speed of sending events to Kafka
___
<tr>
<td>
<details>
<summary><strong>importer.rs</strong><dd><code>Implement buffered Kafka event sending</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
> sending kafka events buffered

- src/eth/follower/importer/importer.rs
Enhancement
___
- Simplified the error handling logic in the newHeads subscription process:
- Removed redundant `resubscribe_ws` variable and associated boolean assignments
- Consolidated error handling cases into more concise match arms
- Modified the resubscription condition to always attempt when WebSocket is supported, rather than based on a specific error condition
- Improved code readability and maintainability by reducing nested logic and removing unnecessary variables
___
<tr>
<td>
<details>
<summary><strong>importer.rs</strong><dd><code>Streamline newHeads subscription error handling</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
> chore: remove unused check

- src/ledger/events.rs
Enhancement
___
- Improved error logging in the `transaction_to_events` function by adding transaction hash context to three error scenarios:
1. When an ERC-20 transfer event has invalid amount data
2. When a transaction emitting transfers is missing the contract address
3. When a transaction emitting transfers is missing the 4-byte function signature
- These changes will make debugging easier by providing more context in error logs
- No functional changes to the code logic, only improvements to error reporting
___
<tr>
<td>
<details>
<summary><strong>events.rs</strong><dd><code>Enhance error logging with transaction context</code>&nbsp; &nbsp; &nbsp; …
> chore: add context to event logs

- src/eth/follower/importer/importer.rs
- src/infra/kafka/kafka.rs
- src/infra/metrics/metrics_config.rs
- src/infra/metrics/metrics_definitions.rs
- src/ledger/events.rs
Enhancement
___
- Enhanced KafkaConnector with new methods for efficient event buffering and sending
- Added comprehensive metrics and logging for Kafka operations
- Simplified Kafka event sending logic in the Importer implementation
- Integrated Kafka metrics into the overall metrics configuration
- Added Debug trait requirement to the Event interface for improved debugging capabilities
- Improved error handling and logging throughout Kafka-related operations
___
<tr>
<td>
<details>
<summary><strong>importer.rs</strong><dd><code>Simplify Kafka event sending in Importer</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
> enha: add metrics and logs to the kafka connector

- src/eth/follower/importer/importer.rs
Enhancement
___
- Enhanced logging in the fake miner mode of the Importer
- Added a tracing::info! log statement to record transaction details before execution
- Improves visibility and debugging capabilities for transactions processed by the fake miner
- This change helps in tracking and analyzing transaction flow in the fake miner scenario
___
<tr>
<td>
<details>
<summary><strong>importer.rs</strong><dd><code>Add transaction logging in fake miner mode</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
src/eth/follower/importer/importer.rs
<li>Added logging for transaction …
> enha: canary miner: log txs before executing

- e2e/cloudwalk-contracts/integration/package-lock.json
___
- Updated Hardhat and related dependencies to their latest versions
- Upgraded @openzeppelin packages, including defender-sdk and hardhat-upgrades
- Updated secp256k1 to version 4.0.4 with improved compatibility
- Various other dependency updates and version bumps for better stability and performance
- Fixed potential compatibility issues by updating interconnected packages
___
<tr>
<td>
<details>
<summary><strong>package-lock.json</strong><dd><code>Dependency updates and version upgrades</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
> chore(deps): audit hardhat

- src/eth/rpc/rpc_server.rs
Enhancement
___
- Introduced a new RPC method `stratus_getBlockAndReceipts` to facilitate faster external importing of blockchain data.
- Implemented the `stratus_get_block_and_receipts` function to handle the new RPC method:
- Accepts a `BlockFilter` parameter to specify the block
- Retrieves the block and its associated transaction receipts
- Returns the block with full transactions and receipts in a JSON format
- Registered the new method in the RPC module for accessibility
- Added necessary imports and used existing context and storage methods to fetch required data
- Enhanced error handling and logging for better debugging and monitoring
___
<tr> …
> enha: add endpoint for faster external importing

- src/globals.rs
Enhancement
___
- Implemented functionality to track and display the application's running time
- Added `START_TIME` static variable to store the application start time using `chrono::DateTime<Utc>`
- Created `setup_start_time()` method to initialize the start time when the application launches
- Enhanced `get_global_state_as_json()` to include:
- Application start time in UTC
- Elapsed time since start, formatted as "X days and HH:MM:SS elapsed"
- Updated `GlobalState::init()` to call `setup_start_time()` during initialization
___
<tr>
<td>
<details>
<summary><strong>globals.rs</strong><dd><code>Add application runtime tracking</code>&nbsp; &nbsp; &nbsp; …
> enha: show running time in state endpoint

- justfile
Enhancement
___
- Added a new command to generate a Codecov coverage report in JSON format
- The report is saved to 'target/llvm-cov/codecov/codecov.json'
- This enhancement allows for easier integration with Codecov for code coverage analysis
- The existing coverage report generation is maintained alongside the new Codecov report
___
<tr>
<td>
<details>
<summary><strong>justfile</strong><dd><code>Add Codecov coverage report generation</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
justfile
<li>Added a command to generate a Codecov coverage …
> chore: output codecov coverage

- .github/workflows/coverage.yml
- justfile
___
- Introduced a new GitHub Actions workflow (`coverage.yml`) for automated code coverage reporting:
- Runs weekly on Saturdays and can be manually triggered
- Sets up the necessary environment (Rust, Node.js, Python, Docker)
- Generates coverage reports using cargo-llvm-cov
- Uploads coverage data to Codecov for analysis
- Modified the `stratus-test-coverage` command in the justfile:
- Now accepts additional arguments for more flexible usage
- Updated to use these arguments when running cargo llvm-cov
- These changes enhance the project's testing infrastructure by providing regular code coverage insights and allowing for more customizable coverage report generation.
___ …
> chore: add codecov

- src/eth/storage/cache.rs
- src/eth/storage/mod.rs
- src/eth/storage/stratus_storage.rs
Enhancement
___
- Introduced `CacheConfig` struct to allow configurable capacities for slot and account caches
- Integrated `CacheConfig` into `StorageConfig` for centralized configuration
- Refactored `StorageCache`, `StratusStorage`, and related components to use the new configurable cache
- Updated initialization process to use the new cache configuration
- Improved testability by allowing custom cache configurations in test environments
___
<tr>
<td>
<details>
<summary><strong>cache.rs</strong><dd><code>Implement configurable cache capacities</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
> enha: add cache config

- justfile
Enhancement
___
- Refactored e2e-admin-password test to use a loop, reducing code duplication and improving maintainability
- Created _e2e-leader-follower-up-impl recipe to separate implementation from cleanup tasks
- Introduced _coverage-run-stratus-recipe to streamline coverage test execution
- Simplified stratus-test-coverage by using loops for multiple test scenarios
- Removed redundant code and improved overall script efficiency
- Enhanced readability and maintainability of the justfile
___
<tr>
<td>
<details>
<summary><strong>justfile</strong><dd><code>Refactor and optimize E2E tests and coverage scripts</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
> chore: refac justfile coverage and health test

- Cargo.lock
- Cargo.toml
Other
___
- Update package version from 0.1.0 to 0.20.1
___
<tr>
<td>
<details>
<summary><strong>Cargo.toml</strong><dd><code>Update package version to 0.20.1</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
Cargo.toml
- Increased package version from 0.1.0 to 0.20.1
</details>
</td>
<td><a href="https://github.com/cloudwalk/stratus/pull/1947/files#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542">+1/-1</a>&nbsp; &nbsp; &nbsp; </td>
</tr> …
> chore: bump version in Cargo.toml

- src/bin/importer_offline.rs
- src/eth/executor/evm.rs
- src/eth/executor/executor.rs
- src/eth/follower/importer/importer.rs
- src/eth/miner/miner.rs
- src/eth/primitives/log_filter_input.rs
- src/eth/rpc/rpc_server.rs
- src/eth/storage/mod.rs
- src/eth/storage/stratus_storage.rs
Enhancement
___
- Remove Storage trait
- Convert trait methods to public functions
- Update imports in affected files
- Simplify StratusStorage implementation
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Dependencies</strong></td><td><details><summary>7 files</summary><table>
<tr>
<td><strong>importer_offline.rs</strong><dd><code>Remove unused Storage import</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></td>
<td><a href="https://github.com/cloudwalk/stratus/pull/1951/files#diff-9fef7d584818c3db119ea1cd0952a57a953751f85f93ca813af861c4c737c53a">+0/-1</a>&nbsp; &nbsp; …
> chore: remove storage trait

- src/config.rs
- src/eth/executor/evm_result.rs
- src/eth/miner/miner_config.rs
- src/eth/primitives/block_number.rs
- src/eth/primitives/bytes.rs
- src/eth/primitives/nonce.rs
- src/eth/primitives/wei.rs
- src/eth/storage/permanent/inmemory.rs
- src/eth/storage/permanent/rocks/rocks_permanent.rs
- src/eth/storage/permanent/rocks/types/address.rs
- src/eth/storage/permanent/rocks/types/block_number.rs
- src/ext.rs
- src/infra/kafka/kafka.rs
Enhancement
___
- Remove unused code and configurations
- Simplify data structures and remove redundant methods
- Streamline type conversions and serialization logic
- Clean up unnecessary imports and dependencies
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><details><summary>13 files</summary><table>
<tr>
<td><strong>config.rs</strong><dd><code>Remove unused configuration structs and enums</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></td>
<td><a href="https://github.com/cloudwalk/stratus/pull/1954/files#diff-cba64c21ab992eaad29fce147a08f4560a4769bc14682b8a96081a5fd02dbecd">+0/-74</a>&nbsp; &nbsp; </td>
</tr>
<tr> …
> chore: remove more unused code

- .github/workflows/_setup-e2e.yml
- .github/workflows/build-binary.yml
- .github/workflows/check-features.yml
- .github/workflows/comment-tag-report.yml
- .github/workflows/coverage.yml
- .github/workflows/doc-test.yml
- .github/workflows/docs-release.yml
- .github/workflows/e2e-contracts-rocks.yml
- .github/workflows/e2e-contracts.yml
- .github/workflows/e2e-leader-follower.yml
- .github/workflows/int-test.yml
- .github/workflows/lint-check.yml
- .github/workflows/merge-gatekeeper.yml
- .github/workflows/outdated.yml
- .github/workflows/pr-agent.yml
- .github/workflows/unit-test.yml
Enhancement
___
- Pin Ubuntu runner to version 22.04
- Update all GitHub Actions workflows
- Prevent potential issues with Ubuntu 24.04
- Ensure consistent CI environment across workflows
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Configuration changes</strong></td><td><details><summary>16 files</summary><table>
<tr>
<td><strong>_setup-e2e.yml</strong><dd><code>Pin Ubuntu runner to 22.04</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></td>
<td><a href="https://github.com/cloudwalk/stratus/pull/1955/files#diff-41e89a8381754cea161274f93967da9d766868c2ee60 …
> ci: pin ubuntu runner to 22.04 to avoid 24.04 bump

- .github/workflows/_setup-e2e.yml
- .github/workflows/build-binary.yml
- .github/workflows/check-features.yml
- .github/workflows/comment-tag-report.yml
- .github/workflows/coverage.yml
- .github/workflows/doc-test.yml
- .github/workflows/docs-release.yml
- .github/workflows/e2e-contracts-rocks.yml
- .github/workflows/e2e-contracts.yml
- .github/workflows/e2e-leader-follower.yml
- .github/workflows/int-test.yml
- .github/workflows/lint-check.yml
- .github/workflows/outdated.yml
- .github/workflows/unit-test.yml
Enhancement
___
- Update Rust toolchain version to 1.84
- Upgrade nightly Rust to 1.86.0-nightly
- Standardize Rust version across workflows
- Minor formatting improvements in some files
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><details><summary>14 files</summary><table>
<tr>
<td><strong>_setup-e2e.yml</strong><dd><code>Update Rust toolchain to version 1.84</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></td>
<td><a href="https://github.com/cloudwalk/stratus/pull/1966/files#diff-41e89a8381754cea161274f93967da9d766868c2ee6083c52bf19d5f554ec332">+1/-1</a>&nbsp; &nbsp; &nbsp; </td>
</tr>
<tr> …
> chore: update worksflows rust version

- .github/workflows/_setup-e2e.yml
- .github/workflows/e2e-test.yml
- .gitignore
- justfile
- utils/compare_block/main.py
- utils/compare_block/requirements.txt
Add e2e test for importer offline
* Turn on stratus
* Runs some transactions
* Runs rpc downloader (downloads blocks and receipts to a SQL database)
* Runs importer-offline (generates a new database chain using the SQL database)
* Turn on stratus on importer-offline new database chain
* Compares blocks between both stratus
> Feat importer offline e2e

- .github/workflows/check-unused-deps.yml
- Cargo.lock
- Cargo.toml
- justfile
closes #1919
___
___
- Add GitHub Action to check for unused dependencies
- Remove unused dependencies from Cargo.toml
- Add 'check-unused-deps' command to justfile
- Implement workflow for PR and push events
___
```mermaid
flowchart LR
A["GitHub Action"] --> B["Check Unused Deps"]
B --> C["Cargo.toml"]
B --> D["justfile"]
C --> E["Remove Unused Deps"]
D --> F["Add check-unused-deps command"]
```
<tr>
<td>
<details>
<summary><strong>check-unused-deps.yml</strong><dd><code>Add GitHub Action for checking unused dependencies</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
> CI: check unused deps

- catalog-info.yaml
Enhancement, Documentation
___
- Added 'virtual-machine-deploy' tag to catalog-info.yaml
- Updated metadata for Stratus project
___
```mermaid
flowchart LR
A["catalog-info.yaml"] -- "Add tag" --> B["virtual-machine-deploy"]
```
<tr>
<td>
<details>
<summary><strong>catalog-info.yaml</strong><dd><code>Add VM deployment tag to metadata</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
catalog-info.yaml
- Added 'virtual-machine-deploy' tag to the list of tags …
> docs: create vm tag in catalog-info.yaml

- Cargo.lock
- Cargo.toml
Enhancement
___
- Update multiple dependency versions in Cargo.toml
- Bump minor versions for several crates
- Upgrade metrics and metrics-exporter-prometheus
- Update sqlx to version 0.8.6
___
```mermaid
flowchart LR
A["Cargo.toml"] --> B["Update Dependencies"]
B --> C["Minor Version Bumps"]
B --> D["Patch Version Bumps"]
C --> E["metrics, strum, clap, sqlx"]
D --> F["parking_lot, rand, ring"]
```
<tr>
<td>
<details>
<summary><strong>Cargo.toml</strong><dd><code>Update multiple dependency versions</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
> chore: bump minor + patch versions of several crates

- Cargo.lock
- Cargo.toml
- build.rs
Enhancement, Other
___
- Updated build dependencies to newer versions
- Refactored build.rs to use new vergen-gitcl API
- Removed unused dependencies from Cargo.toml
- Minor syntax updates in build.rs for nom 8.0.0
___
```mermaid
flowchart LR
A["Old Dependencies"] --> B["Updated Dependencies"]
C["Old vergen API"] --> D["New vergen-gitcl API"]
E["build.rs"] --> F["Refactored build.rs"]
G["Cargo.toml"] --> H["Cleaned Cargo.toml"]
```
<tr>
<td>
<details>
<summary><strong>build.rs</strong><dd><code>Refactor build script to use new vergen-gitcl API</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
> chore: bump build and dev crates

- src/eth/follower/importer/importer.rs
Bug fix
___
- Improved error handling in importer task execution
- Replaced generic error logging with specific error checks
- Enhanced task result processing for better error detection
___
```mermaid
flowchart LR
A["try_join! tasks"] --> B["Check individual results"]
B --> C["Propagate errors"]
C --> D["Improved error handling"]
```
<tr>
<td>
<details>
<summary><strong>importer.rs</strong><dd><code>Improve task result handling in importer</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr> …
> fix: error supression in importer

- src/eth/executor/evm_input.rs
- src/eth/follower/importer/importer.rs
- src/eth/primitives/block.rs
- src/eth/primitives/execution.rs
- src/eth/primitives/execution_result.rs
- src/eth/primitives/transaction_mined.rs
- src/eth/primitives/transaction_stage.rs
- src/eth/storage/permanent/rocks/rocks_permanent.rs
- src/eth/storage/permanent/rocks/rocks_state.rs
- src/eth/storage/permanent/rocks/types/transaction_mined.rs
- src/eth/storage/stratus_storage.rs
- src/infra/blockchain_client/blockchain_client.rs
Enhancement
___
- Remove execution changes from TransactionMined
- Simplify block storage and retrieval
- Refactor ExecutionResult and related structures
- Update API for fetching blocks with changes
___
```mermaid
flowchart LR
TM["TransactionMined"] -- "Remove" --> EC["execution.changes"]
TM -- "Add" --> NF["New fields"]
BS["Block Storage"] -- "Simplify" --> BWC["Block with Changes"]
ER["ExecutionResult"] -- "Add" --> ISM["is_success() method"]
API["API"] -- "Update" --> FBWC["Fetch Block with Changes"]
```
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><details><summary>12 files</summary><table>
<tr>
<td><strong>evm_input.rs</strong><dd><code>Update …
> enha: remove execution changes from transaction mined

- src/eth/executor/evm.rs
This PR implements error decoding for the `debug_traceTransaction` RPC method to provide human-readable error messages alongside raw hex output, making debugging failed smart contract transactions much easier.
Currently, when transactions fail in trace output, only raw hex error data is shown:
```json
{
"error": "execution reverted",
"output": "0xa818b01a"
}
```
Enhanced the CallTracer to decode errors using the existing error signature database:
```json
{
"error": "execution reverted: UnauthorizedCaller(address)",
"output": "0xa818b01a"
}
```
- ✅ **Leverages Existing Infrastructure**: Uses the existing `error_sig_opt` function and contract signature database
- ✅ **Backward Compatible**: Raw hex output is preserved for tools that expect it
- ✅ **Comprehensive**: Recursively processes …
> feat: Add Error Decoding To Raw Trace Output

- src/eth/rpc/rpc_config.rs
- src/eth/rpc/rpc_server.rs
Enhancement
___
- Added configuration for RPC batch request limit
- Implemented configurable limit in server setup
___
```mermaid
flowchart LR
A["RpcServerConfig"] -- "New field" --> B["batch_request_limit"]
B -- "Used in" --> C["ServerConfig"]
C -- "Applied to" --> D["RpcServer"]
```
<tr>
<td>
<details>
<summary><strong>rpc_config.rs</strong><dd><code>Add batch request limit configuration</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
src/eth/rpc/rpc_config.rs …
> enha: add config for rpc batch request limit

- e2e/cloudwalk-contracts/integration/package-lock.json
- e2e/cloudwalk-contracts/integration/test/helpers/account.ts
- e2e/cloudwalk-contracts/integration/test/leader-follower-importer.test.ts
- src/eth/executor/executor.rs
- src/eth/primitives/external_transaction.rs
- src/eth/primitives/transaction_input.rs
- src/eth/rpc/rpc_context.rs
- src/eth/rpc/rpc_server.rs
Bug fix, Enhancement, Tests
___
- Fix gas price handling for EIP-1559 transactions
- Improve transaction type support and testing
- Remove unused gas_price from RpcContext
- Add tracing for external transactions
___
```mermaid
flowchart LR
A["Gas Price Handling"] --> B["EIP-1559 Transactions"]
A --> C["Legacy Transactions"]
A --> D["EIP-2930 Transactions"]
B --> E["maxFeePerGas"]
B --> F["maxPriorityFeePerGas"]
G["Transaction Testing"] --> H["Type 0 (Legacy)"]
G --> I["Type 1 (EIP-2930)"]
G --> J["Type 2 (EIP-1559)"]
```
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><details><summary>4 files</summary><table>
<tr> …
> fix: set feePerGas params to gasPrice on type 2 external transactions

- src/bin/importer_offline.rs
- src/bin/rpc_downloader.rs
- src/eth/follower/importer/importer.rs
- src/eth/primitives/address.rs
- src/eth/primitives/chain_id.rs
- src/eth/primitives/gas.rs
- src/eth/primitives/index.rs
- src/eth/primitives/nonce.rs
- src/eth/primitives/transaction_input.rs
- src/eth/rpc/rpc_config.rs
- src/eth/storage/permanent/rocks/rocks_cf.rs
- src/infra/blockchain_client/blockchain_client.rs
Enhancement
___
- Replace 'return Err(anyhow!(...))' with 'bail!(...)'
- Simplify error handling across multiple files
- Improve code readability and consistency
___
```mermaid
flowchart LR
A["Error handling"] -- "Replace" --> B["anyhow!"]
B -- "With" --> C["bail!"]
C -- "Across" --> D["Multiple files"]
```
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><details><summary>12 files</summary><table>
<tr>
<td><strong>importer_offline.rs</strong><dd><code>Replace anyhow! with bail! for error handling</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></td>
<td><a …
> chore: use bail! instead of return Err(anyhow)

- .github/workflows/merge-gatekeeper.yml
Enhancement
___
- Added 'E2E Rocks on cppv2' to ignored checks in merge gatekeeper
___
```mermaid
flowchart LR
A["Merge Gatekeeper Configuration"] --> B["Add E2E Rocks on cppv2"]
B --> C["Updated Ignored Checks"]
```
<tr>
<td>
<details>
<summary><strong>merge-gatekeeper.yml</strong><dd><code>Add E2E Rocks on cppv2 to ignored checks</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
.github/workflows/merge-gatekeeper.yml
<ul><li>Added 'E2E Rocks on cppv2' to the list of ignored checks in the merge …
> test(temp): ignore cppv2 tests

- .github/workflows/e2e-contracts-rocks.yml
- .github/workflows/merge-gatekeeper.yml
- e2e/cloudwalk-contracts/contracts-clone.sh
- e2e/cloudwalk-contracts/contracts-compile.sh
- e2e/cloudwalk-contracts/contracts-coverage.sh
- e2e/cloudwalk-contracts/contracts-flatten.sh
- e2e/cloudwalk-contracts/contracts-remove.sh
- e2e/cloudwalk-contracts/contracts-test.sh
Refactor to use external hardhat configuration file instead of hardcoded values.
___
Enhancement
___
- Use external hardhat.config.ts file
- Remove hardcoded configuration copying
- Update merge gatekeeper ignored checks
___
```mermaid
flowchart LR
A["Hardhat Config"] --> B["External File"]
B --> C["Contracts Scripts"]
D["Merge Gatekeeper"] --> E["Updated Ignored Checks"]
```
<tr>
<td>
<details>
<summary><strong>contracts-flatten.sh</strong><dd><code>Remove hardcoded Hardhat config copy</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
> fix(tests): use external hardhat.config.ts

- src/eth/executor/evm.rs
Enhancement
___
- Reduced maximum gas limit for transactions from 1 billion to 100 million
___
```mermaid
flowchart LR
A["Old Gas Limit: 1,000,000,000"] --> B["New Gas Limit: 100,000,000"]
B --> C["Optimized Resource Usage"]
```
<tr>
<td>
<details>
<summary><strong>evm.rs</strong><dd><code>Reduce maximum gas limit for transactions</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
<ul><li>Decreased <code>GAS_MAX_LIMIT</code> constant from 1,000,000,000 to 100,000,000<br> <li> …
> chore: lower gas limit for transactions
