- src/eth/executor.rs
- src/eth/rpc/mod.rs
- src/eth/rpc/rpc_server.rs
- src/eth/rpc/rpc_subscriptions.rs
Changes the dynamics of how TX and RX are set when producing events.
`RpcSubscriptions` now receives the `rx` channel, making it possible to spawn multiple tasks from multiple sources. 
For example, we can have a notifier that notify about events produced by the server and another that notifies from other nodes.
> refactor: tx/rx between executor and subscription manager

- .github/workflows/lint-check.yml
Action to automatically check code formatting and common errors.
It differs from `just lint` in the `fmt` step: this action will just check and report, it will not fix the formatting.
> test: add action to lint and fmt checks

- Cargo.lock
- Cargo.toml
- src/eth/evm/revm.rs
- src/eth/executor.rs
- src/eth/miner/block_miner.rs
- src/eth/primitives/log_filter_input.rs
- src/eth/rpc/rpc_server.rs
- src/eth/storage/eth_storage.rs
- src/eth/storage/inmemory.rs
- src/eth/storage/metrified.rs
- src/eth/storage/postgres/postgres.rs
Note that in the file `src/eth/executor.rs` in the functions `EthExecutor::transact` and `EthExecutor::call`, I aquire the `evm_lock`, do nothing with it, and then create a new `Revm` object and pass that to `spawn_blocking`. There are two ways that I thought of to circumvent this, but I'd like further discussion before implementing either of them.
1. Run the EVM in a dedicated thread (instead of spawning a thread for each call) with some form of communication, maybe a channel or queue.
2. Require `Clone` for `EthStorage` and `Evm`. Then I could aquire the lock and clone the underlying struct. However implementing clone for dyn traits is not trivial, to solve this there is a popular crate that includes a macro for it (https://github.com/dtolnay/dyn-clone).
Are either of these approaches …
> feat: Migrate to async traits for EthStorage

- Cargo.lock
- Cargo.toml
- src/eth/evm/revm.rs
- src/eth/executor.rs
- src/ext.rs
- src/main.rs
* Tokio nested runtimes are not allowed, so use a Rayon thread-pool instead.
* Use crossbeam-channel instead of async-channel because Rayon is not async.
* Use `futures::executor::block_on` instead of `tokio::block_on` inside EVM because Tokio runtime is not available for EVM execution. It just blocks on the current thread, that is the desired behavior.
* Stop EVM threads when task channel is closed.
> feat: use rayon threadpool to run evms

- .github/workflows/e2e-test.yml
- justfile
The following changes were necessary/convenient to run the test in Github Actions
- hardcode the address in the justfile
- make killport run optional
- increase timeout for wait-service
The action is already checking this PR.
obs: in another PR I'll change the way we clone contracts so we can `just setup` in the actions too.
> test: add action to run e2e-stratus

- Cargo.lock
- Cargo.toml
- src/eth/evm/revm.rs
- src/eth/executor.rs
- src/eth/storage/inmemory.rs
- src/infra/tracing.rs
- src/main.rs
* EVM threads will have Tokio runtime available, so SQLx should not panic anymore.
* Removed rayon in favor of spawning native threads.
> fix: tokio runtime available to spawned threads. also remove rayon.

- .github/workflows/doc-test.yml
- .github/workflows/e2e-test.yml
- .github/workflows/lint-check.yml
- .github/workflows/unit-test.yml
- Set a concurrency rule to cancel in-progress runs if a commit is made to the same pull request
- Fix doc test job name (it wasn't unique)
With that, we might save resources by not completing runs that will no longer be useful
> test: add concurrency management to actions

- e2e/test/e2e.test.ts
- src/eth/rpc/rpc_server.rs
This is needed for blockscout. Test case added to e2e-stratus.
> feat: add eth get uncle by block hash and index

- e2e/test/e2e.test.ts
- e2e/test/helpers/rpc.ts
- src/eth/primitives/block_number.rs
- src/eth/rpc/rpc_server.rs
- src/eth/storage/eth_storage.rs
- src/eth/storage/inmemory/inmemory.rs
- src/eth/storage/inmemory/inmemory_account.rs
- src/eth/storage/inmemory/inmemory_history.rs
- src/eth/storage/metrified.rs
- src/eth/storage/postgres/postgres.rs
Implements `debug_setHead`. It allows resetting the blockchain entire state to a past block.
Like other functions like `test_accounts`, this method should be put behind a future-flag in the future to avoid destructive actions in production.
> feat: debug_setHead

- e2e/test/e2e-json-rpc.test.ts
- e2e/test/e2e-tx-parallel-contract.test.ts
- e2e/test/e2e-tx-parallel-transfer.test.ts
- e2e/test/e2e-tx-serial-transfer.test.ts
- e2e/test/helpers/account.ts
- e2e/test/helpers/rpc.ts
- justfile
- src/eth/evm/revm.rs
- src/eth/primitives/address.rs
- src/eth/primitives/execution_account_changes.rs
- src/eth/primitives/execution_conflict.rs
- src/eth/storage/eth_storage.rs
- src/eth/storage/inmemory/inmemory.rs
* Created test that sends paralell wei transfer.
* Created utilities for E2E like `sendRawTransactions` that sends multiple transactions in parallel.
* Do not track changes to special accounts like ZERO and COINBASE.
* Removed TODOs from change detection code in InMemory.
> test: creating test scenario for parallel wei transfer

- Dockerfile
44.88   failed to execute command: No such file or directory (os error 2)
44.88   is `cmake` not installed?
44.88
44.88   build script failed, must exit now
44.88   note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
44.88 warning: build failed, waiting for other jobs to finish...
> fix: Add cmake into Dockerfile

- src/bin/rpc_server_poller.rs
- src/config.rs
- src/eth/mod.rs
Calling import from rpc poller, the next step is making import properly execute transactions and extract the state root
> chore: add import call into rpc server poller

- justfile
- src/eth/evm/evm.rs
- src/eth/evm/revm.rs
- src/eth/primitives/external_transaction.rs
- src/eth/primitives/gas.rs
- src/eth/primitives/transaction_input.rs
* When executing an external transaction, uses original gas_limit and gas_price to reproduce original behavior.
* When executing an eth_call or eth_sendRawTransaction, keep using max values (current behavior), but it can be changed to start using the input values if necessary instead of being hardcoded inside the REVM.
* Original gas_limit is calculated according to the transaction type.
> feat: pass gas and gas_price to evm when executing external transaction

- .sqlx/query-e8a32893d991a776633dbba4e35b868c31f91cfe0c3e4081e7749c6a76cee5d1.json
- .sqlx/query-f401ecc9e454519dd2398bd17f2c0d9c99e4e980bd0de506ddd20d5ab753ff04.json
- src/eth/evm/revm.rs
- src/eth/miner/block_miner.rs
- src/eth/primitives/block.rs
- src/eth/primitives/block_header.rs
- src/eth/primitives/block_number.rs
- src/eth/primitives/execution.rs
- src/eth/primitives/external_block.rs
- src/eth/primitives/mod.rs
- src/eth/primitives/unix_time.rs
- src/eth/storage/postgres/postgres.rs
- src/eth/storage/postgres/queries/select_block_header_by_hash.sql
- src/eth/storage/postgres/queries/select_block_header_by_number.sql
- src/eth/storage/postgres/types.rs
- static/schema/001-init.sql
Codebase was inconsistent state where in some places Unix timestamps are represented as `u64`, and in other they are represents with the struct `UnixTime`.
Unify all representations using `UnixTime`.
> refactor: use UnixTime instead of u64 everywhere

- justfile
- src/eth/evm/evm.rs
- src/eth/evm/revm.rs
- src/eth/executor.rs
- src/eth/primitives/block_number.rs
- src/eth/primitives/external_block.rs
- src/eth/primitives/external_transaction.rs
There are a lot of TODOs in this PR, but they are just the actual incomplete behavior made explicit.
What this PR improves is that at least for external blocks being imported, the block number and timestamp set in the context are now correct and external contracts that relies on it like CompoundProtocol does not break anymore
> feat: pass block number and timestamp as parameters to evm instead of assuming default values

- e2e-contracts/test-contracts.sh
- justfile
Fixes the problem found by @carneiro-cw in which the script stops at the first successful test suite
we needed to make yield streamer public
> fix(e2e-contracts): wrap test return code in a conditional

- .github/workflows/e2e-contracts.yml
- e2e-contracts/clone-contracts.sh
To avoid breaking Contracts E2E automated test, this PR checkouts each contract repo in a specific commit after cloning.
> test: pin commit to repo clones

- src/eth/executor.rs
- src/eth/primitives/block.rs
- src/eth/primitives/block_header.rs
- src/eth/primitives/external_receipt.rs
- src/eth/primitives/external_transaction.rs
- src/eth/primitives/index.rs
- src/eth/primitives/log.rs
- src/eth/primitives/log_mined.rs
- src/eth/primitives/log_topic.rs
- src/eth/primitives/mod.rs
- src/eth/primitives/transaction_input.rs
- src/eth/primitives/transaction_mined.rs
- src/eth/storage/inmemory/inmemory.rs
**Main points**
This PR makes the block importer fully works with the in-memory `EthStorage` implementation, but performance is awful.
It works this way for each block to import:
* For each block to import, each transaction is re-executed and the temporary account changes are stored in the storage and the transaction execution changes are collected to a vector.
* After all transactions are re-executed in the block, the external block is converted to the internal block format with the related transactions and executions.
* The storage state is rolled-back using `reset` to its initial state before all temporary data was stored.
* The produced block with the is saved permanently to the storage.
The bottleneck of this flow is the `reset` method. Even the in-memory implementation is slow and …
> feat: make importer work with current storage design

- src/eth/executor.rs
- src/eth/storage/inmemory/inmemory_temporary.rs
- src/eth/storage/stratus_storage.rs
- src/eth/storage/temporary_storage.rs
Conflict detection is only working when trying to save the block.
The implementation in the temporary storage never triggers the conflict.
So at least for now it will be removed, and in the future we can try again to make a single conflict resolution algorithm in the temporary storage and remove them from the permanent storage.
> feat: remove check_conflicts from TemporaryStorage because it is not working

- .sqlx/query-730e617474d8bb7970702970ba162c321c80d3e77c1b364e101ae96f4d42e2f9.json
- src/bin/importer/_postgres.rs
- src/bin/importer/importer-download.rs
- src/bin/importer/importer-import.rs
- src/bin/importer/sql/select_downloaded_blocks_in_range.sql
- src/bin/importer/sql/select_downloaded_receipts_in_range.sql
Just a small refactoring creating some reuse between importer jobs. These functions will be enhanced in the next PRs.
> refactor: move postgres functions to _postgres.rs module

- justfile
it is needed before the whole e2e-flamegraph call
> chore: remove sudo, as it is not needed here

- Cargo.toml
- justfile
- src/config.rs
- src/eth/block_miner.rs
- src/eth/evm/revm.rs
- src/eth/executor.rs
- src/eth/primitives/unix_time.rs
- src/eth/rpc/rpc_context.rs
- src/eth/rpc/rpc_server.rs
All developments features are now behind the `dev` compilation flag.
The flag is not enabled by default, but Justfile pass the `dev` flag in `cargo run` commands.
If necessary, we can create more granular flags, but we should try to fit the feature behind `dev` first, and only if really necessary we should create additional flags.
`RevmInspector` was removed, but that is a good candidate of feature that we may want to have a more granular flag if we want it back, because even in `dev` mode, we may not want to execute Evm with an inspector.
> feat: unify all develoment features behind `dev` flag

- justfile
To improve readability when running tests, this PR redirects Stratus log messages to a file.
> test: hide stratus logs

- Cargo.lock
closes https://github.com/cloudwalk/stratus/security/dependabot/12
> deps: bump mio from 0.8.10 to 0.8.11

- src/bin/importer_offline.rs
this allows us to do smaller quries and less time waiting PG 3x faster this way
> chore: creates smaller blocks batches

- Cargo.lock
- Cargo.toml
- src/eth/primitives/bytes.rs
- tests/test_import_offline_snapshot.rs
* Improvements to test_import_offline_snapshot test
* Always calling `to_analysed` in the bytecode conversion decreased 200ms from EVM execution.
Other possible improvements spots like using a faster keccak256 implementation were identified, but we are using REVM 3.5.0 and the latest version is 7.1.0, so we should upgrade REVM before focusing on more EVM related optimizations.
> feat: performance measurements and improvements

- Cargo.lock
- Cargo.toml
- src/config.rs
- src/eth/evm/evm.rs
- src/eth/evm/revm.rs
- src/eth/executor.rs
- src/eth/mod.rs
- src/eth/primitives/log.rs
- src/eth/primitives/storage_point_in_time.rs
- src/eth/primitives/unix_time.rs
- tests/test_execution.rs
- tests/test_import_offline_snapshot.rs
* Upgraded REVM to 7.1.0
* In high-level view, REVM interaction still working the same way by mutatin the current env configurations. In a next PR we can evaluate if there are better way to interact with it.
* EVMs are now created directly in their own threads instead of being created in the main thread and moved to another threads, so they don't need to be Send + Sync anymore.
> chore: upgrade revm to 7.1.0

- Cargo.lock
- Cargo.toml
- src/bin/importer_offline.rs
- src/bin/importer_online.rs
- src/bin/rpc_downloader.rs
- src/config.rs
- src/eth/executor.rs
- src/eth/primitives/account.rs
- src/eth/storage/csv/csv_exporter.rs
- src/eth/storage/csv/mod.rs
- src/eth/storage/mod.rs
- src/eth/storage/permanent_storage.rs
- src/infra/postgres.rs
- tests/test_execution.rs
- tests/test_import_offline_snapshot.rs
* Postgres receives a `PostgresClientConfig` so it is easier to understand each parameter when reading code instead of relying on positional parameters.
* Number of connections and timeout is always configurable in all jobs. They were hardcoded in several places with huge values.
* Assume small values for connections instead of huge values that only makes sense in production.
* Very initial version of CSV exporter, it will be implemented in a next PR.
> feat: base csv writer and storage/postgres configurations

- .gitignore
- src/bin/importer_offline.rs
- src/eth/storage/csv/csv_exporter.rs
- src/eth/storage/inmemory/inmemory_temporary.rs
- src/eth/storage/sled/sled_temporary.rs
- src/eth/storage/stratus_storage.rs
- src/eth/storage/temporary_storage.rs
- src/infra/metrics.rs
When resuming the importer after a stop:
* Creates a new CSV from the current block instead of overwriting the previous file.
* Resume from the last used ID instead of restarting at 0.
Also sinchronizes CSV flushes and temporary storage flushes.
> feat: improving csv exporter

- e2e/package-lock.json
fixes https://github.com/cloudwalk/stratus/security/dependabot/13
> deps(follow-redirects): bump from 1.15.5 to 1.15.6

- src/eth/evm/revm.rs
- src/eth/executor.rs
- src/eth/primitives/execution.rs
- src/eth/primitives/nonce.rs
- src/eth/storage/postgres_permanent/types.rs
When importing external transactions, do not reexecute transactions that failed.
Instead manually increment the sender nonce and generate a fake execution for the failed transaction.
> feat: do not reexecute external transactions that failed

- .github/workflows/outdated.yml
- .justfile_helpers
- justfile
Change `just outdated` to use `cargo outdated` instead of a custom script.
It will start notifying about major updates.
closes #344 
[Example run](https://github.com/cloudwalk/stratus/actions/runs/8379006727/job/22944918923)
> build: use cargo outdated

- src/bin/importer_offline.rs
- src/config.rs
- src/lib.rs
Allow to manually specify the starting and ending block of the importer-offline job.
> feat: `--block-start` and `--block-end` args for importer-offline

- .github/workflows/e2e-contracts-hybrid.yml
- .github/workflows/e2e-test.yml
The #392 was merged without being ready. To avoid the annoying CI failing on every pull request, I'm skipping it until the code is fixed to pass them.
To run the hybrid test, manually dispatch the run in the Actions tab for your branch.
> test: skip broken hybrid

- e2e-contracts/integration/test/relayer.test.ts
- justfile
Executing Stratus and Relayer builds + docker compose up in parallel to reduce test duration.
This enhancement subtracted ~3min if cache hits.
> optimize relayer e2e test duration

- src/bin/importer_offline.rs
- src/eth/block_miner.rs
- src/eth/primitives/block.rs
- src/eth/storage/csv/csv_exporter.rs
- src/eth/storage/inmemory/inmemory_permanent.rs
- src/eth/storage/rocks/rocks_permanent.rs
- src/eth/storage/stratus_storage.rs
Ensure consistency of `hash` and `number` functions.
They should always returns owned values.
> feat: always returns owned values for hash and number

- src/config.rs
- src/eth/executor.rs
Instead of passing the span ID and creating a new span in the EVM thread, we create the span in the client thread and only enter it inside the EVM thread.
> fix: do not panic on evm thread because of tracing

- src/eth/storage/rocks/rocks_state.rs
> fix: blocks by hash returned genesis if the hash was not found

- e2e/test/automine/e2e-tx-serial-transfer.test.ts
- e2e/test/helpers/account.ts
- e2e/test/helpers/rpc.ts
- regression test for #1184 
- basic test for type 2 transactions
ignored (left as comment) tests
- `type` in receipts (already known in #1136)
- `type` (rocks storage only), `maxFeePerGas` and `maxPriorityFeePerGas` in inputs (opened #1187)
> test: type 2 transactions

- src/eth/consensus/mod.rs
Sometimes the current heartbeat interval is not high enough and leads to changes in leadership when nothing relevant actually happened other than the timeout. This PR increases the interval to try to reduce these cases from happening.
> increase heartbeat interval

- src/bin/importer_online.rs
- src/eth/primitives/block_number.rs
- src/eth/rpc/rpc_error.rs
- src/eth/rpc/rpc_server.rs
Limit `eth_getLogs` to 5000 blocks. We can make this number configurable or tune to a better value later.
Also added automatic conversion from `ErrorObjectOwned` to `RpcError`.
> feat: limit eth_getLogs to 5000 blocks

- src/config.rs
- src/eth/storage/permanent_storage.rs
- src/eth/storage/stratus_storage.rs
- src/eth/storage/temporary_storage.rs
- tests/test_import_external_snapshot_common.rs
This is a first step to making services static to decrease the use of Arc like suggested in this issue: https://github.com/cloudwalk/stratus/issues/489
> refactor: use Box instead of Arc inside StratusStorage

- chaos/experiments/leader-election.sh
Sometimes there is a case of elections in rapid succession, and this leads to the code checking leader to sometimes accuse more than one leader, even though the leaders are for different terms and correct behavior. This PR increases the time before making the check to allow some time for the leadership to settle down.
> Increase time duration before checking leader

- Cargo.toml
- src/eth/primitives/storage_point_in_time.rs
- src/eth/storage/rocks/rocks_config.rs
- src/eth/storage/stratus_storage.rs
- src/globals.rs
- src/infra/metrics/metrics_definitions.rs
- src/infra/metrics/metrics_init.rs
- src/infra/metrics/metrics_types.rs
- src/infra/mod.rs
- src/infra/tracing.rs
`[cfg(feature = "metrics")]` is spawning across the entire codebase.
Introducing the `timed` function aims to centralize this feature-flag inside its implementation and making code maintenance easier while still providing the benefits of having a compile-time feature-flag.
> feat: timed function for metrics

- src/config.rs
- src/eth/storage/rocks/rocks_db.rs
- src/eth/storage/rocks/rocks_permanent.rs
- src/eth/storage/rocks/rocks_state.rs
- src/eth/storage/stratus_storage.rs
- tests/test_import_external_snapshot_rocksdb.rs
We decided that we prefer to make snapshots on the storage instead of using the backup functionality with rocksdb
> Disable RocksDB backups

- src/bin/rpc_downloader.rs
It introduces a bug since `rpc_downloader` downloads partially from different batches in parallel
> Revert PR #1244

- src/bin/importer_offline.rs
- src/bin/importer_online.rs
- src/bin/relayer.rs
- src/bin/rpc_downloader.rs
- src/eth/block_miner.rs
- src/eth/consensus/discovery.rs
- src/eth/consensus/forward_to.rs
- src/eth/consensus/mod.rs
- src/eth/executor.rs
- src/eth/primitives/external_receipts.rs
- src/eth/primitives/wei.rs
- src/eth/relayer/external.rs
- src/eth/rpc/rpc_error.rs
- src/eth/rpc/rpc_server.rs
- src/eth/storage/inmemory/inmemory_permanent.rs
- src/eth/storage/rocks/rocks_state.rs
- src/eth/storage/stratus_storage.rs
- src/infra/blockchain_client/blockchain_client.rs
- src/infra/tracing.rs
Ensure that in tracing events and spans:
* Block number fields is always `block_number`.
* Transaction Hash is always `tx_hash`.
* Account address is `address`.
* Error cause is `reason`.
Values are displayed using Display implementation.
> refactor: tracing fields

- src/eth/consensus/mod.rs
Fix empty transaction execution save log. Currently it is not saving if empty, but it should.
> Fix empty transaction execution save log

- src/eth/primitives/block_filter.rs
- src/eth/primitives/log_filter.rs
- src/eth/primitives/log_filter_input.rs
- src/eth/primitives/log_topic.rs
- src/eth/rpc/rpc_server.rs
- src/eth/rpc/rpc_subscriptions.rs
Fix #1258.
Also, reduce RwLock unnecessary retention in subscription notifications.
> RPC: reuse log subscriptions with same filter

- Cargo.toml
- src/eth/storage/stratus_storage.rs
To disable spans that hurt our run time.
These can be re-enabled for debugging purposes.
> Create feature `expensive-spans`

- src/eth/consensus/append_log_entries_storage.rs
- src/eth/consensus/mod.rs
- src/eth/consensus/server.rs
As per RAFT specification, a leader never overwrites or deletes entries in its log; it only appends new entries. This PR adds a conditional to save_log_entry method to distinguish between leader or follower behavior.
> enha: improve save log entry behavior on leader

- src/eth/relayer/external.rs
- src/eth/relayer/transaction_dag.rs
Adding a nonce dependency obviously defeated the whole purpose of resigning the transactions. But it fixed a logic error this also fixes the same issue but does so without compromising on performance.
> perf: remove nonce depencency, split graph components for parallel relaying

- .github/workflows/build-binary.yml
changes from `stratus-*-linux-$SHA` to `*-$SHA`
> ci: use shorter and precise names for artifacts

- e2e/test/automine/e2e-tx-parallel-contract.test.ts
- e2e/test/automine/e2e-tx-parallel-transfer.test.ts
- e2e/test/automine/e2e-tx-serial-contract.test.ts
- e2e/test/automine/e2e-tx-serial-transfer.test.ts
- e2e/test/external/e2e-multiple-tx.test.ts
some e2e tests were interfering with the state of the next one, to work around this, this PR adds a sleep between them (as a temporary solution)
> e2e: sleep between tests to fix interference

- src/eth/primitives/log_filter_input.rs
Accepts payloads like this:
```json
[
{
"address":null,
"blockHash":"0x0b936a9ec14f4ec76a0a0d37f00effa589016d25c5f00d394f328a941b7271e4",
"topics":null
}
]
```
> fix: accept null fields on LogFilterInput

- src/eth/storage/rocks/rocks_db.rs
- src/eth/storage/rocks/rocks_state.rs
- src/infra/metrics/mod.rs
This PR is an attempt at fixing the slow RocksDB boot.
We analyzed our usage case and decided to sacrifice shutdown time in exchange
of a faster boot, this PR takes a conservative approach and waits up to 15 minutes
for the database to finish compaction.
Waiting for compaction is used in order to "force" the pending logs in WAL to be
written, the library doesn't seem to offer a more direct solution.
When it reaches 15 minutes, it safely cancels the operation and proceed with the
shutdown, I expect it to usually run out of time due to `L0 -> L1` compaction, and
not `WAL -> LOG` flushing.
Shutdowns are timed and logged.
> rocks: wait for compaction in shutdown

- .github/workflows/merge-gatekeeper.yml
configuration changes
___
- Updated the merge gatekeeper workflow to ignore additional flaky consensus tests.
- Added "E2E Leader Election with 2 instance(s) and leader restart true" to the ignored list.
- Added "E2E Leader Election with 3 instance(s) and leader restart true" to the ignored list.
___
<tr>
<td>
<details>
<summary><strong>merge-gatekeeper.yml</strong><dd><code>Update ignored tests in merge gatekeeper workflow</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
.github/workflows/merge-gatekeeper.yml
<li>Added two new test scenarios to the ignored list in the merge <br>gatekeeper workflow.<br> …
> ci: ignore flaky consensus tests

- chaos/experiments/leader-election.sh
This PR fixes the variables utilized by killport to kill the instance mid test.
> fix: consensus e2e not killing instances

- src/eth/block_miner.rs
- src/eth/primitives/logs_bloom.rs
- src/eth/primitives/transaction_mined.rs
closes #1134
Ideally we'd save the bloom to the database when mining the block, but this will have to wait until we have db versioning.
> fix: compute transaction's LogsBloom when creating the receipt

- src/bin/importer_offline.rs
- src/bin/importer_online.rs
- src/bin/rpc_downloader.rs
- src/bin/run_with_importer.rs
- src/main.rs
it wasn't finishing properly cause other threads were blocked dropping
our Rocks storage, in turn, the `main` thread was unblocked and
exited early
---
After writing this, it seems like a more general solution is to wait for all threads and tasks to finish.
However, it's still possible to shoot you on the foot by send an `Arc` clone to a spawned thread or task and forgetting about it.
This one, although ugly, seems to work and make it hard to shoot your foot in the process.
An theoretical problem is that RocksDB lost the potential to shut down in parallel with other things, but I can't think of a simple way to do it while guaranteeing proper shutdown.
> fix: storage shutdown when receiving `SIGTERM`

- src/eth/storage/rocks/rocks_state.rs
we decided that 15 minutes was too long, and 4 minutes of waiting for compaction should be enough for flushing WAL files
> tweak: set RocksDB shutdown timeout to 4 minutes

- src/bin/run_with_importer.rs
- src/config.rs
- src/eth/rpc/rpc_client_app.rs
- src/eth/rpc/rpc_context.rs
- src/eth/rpc/rpc_error.rs
- src/eth/rpc/rpc_server.rs
- src/eth/rpc/rpc_subscriptions.rs
- src/main.rs
This PR implements a configurable limit to the max number of subscriptions from `eth_subscribe`, using a default of 15.
> enha: create max subscription limit per client

- src/eth/executor/executor.rs
- src/eth/storage/inmemory/inmemory_temporary.rs
- src/eth/storage/stratus_storage.rs
- src/eth/storage/temporary_storage.rs
- src/infra/metrics/metrics_definitions.rs
___
- Introduced a `Mutex` for serial execution in the `Executor` to prevent conflicts.
- Added handling for poisoned mutex locks to ensure robustness.
- Removed `check_conflicts` method from `TemporaryStorage`, `StratusStorage`, and `TemporaryStorage` trait.
- Removed the metric definition for `storage_check_conflicts` operation.
___
<tr>
<td>
<details>
<summary><strong>executor.rs</strong><dd><code>Add mutex for serial execution in Executor</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
src/eth/executor/executor.rs
<li>Introduced …
> enha: mutex for executor in serial mode

- src/eth/executor/evm.rs
- src/eth/executor/executor.rs
- src/eth/miner/miner.rs
- src/eth/storage/storage_point_in_time.rs
Enhancement, Documentation
___
- Added `serde::Serialize` derive to `EvmInput` struct and `StoragePointInTime` enum to enable serialization.
- Changed lock acquisition order in `Executor` implementation to ensure proper synchronization.
- Added detailed logging for lock acquisition in `Executor` to aid in debugging.
- Updated log level from debug to info for lock acquisition messages in `Miner` for better visibility.
___
<tr>
<td>
<details>
<summary><strong>evm.rs</strong><dd><code>Add serialization to EvmInput struct</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
> enha: change lock order

- src/eth/primitives/address.rs
- src/eth/primitives/block_number.rs
- src/eth/primitives/chain_id.rs
- src/eth/primitives/hash.rs
- src/eth/primitives/index.rs
- src/eth/primitives/transaction_input.rs
- src/eth/primitives/transaction_mined.rs
- src/eth/relayer/transaction_dag.rs
- src/eth/storage/rocks/types.rs
Enhancement
___
- Made inner fields of several structs (`Address`, `BlockNumber`, `ChainId`, `Hash`, `Index`, and various RocksDB types) public.
- Removed the `inner_value` methods from these structs.
- Updated related code and tests to use public field access instead of the removed `inner_value` methods.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><details><summary>7 files</summary><table>
<tr>
<td>
<details>
<summary><strong>address.rs</strong><dd><code>Expose inner value of `Address` struct directly</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
src/eth/primitives/address.rs
<li>Made the <code>H160</code> field of <code>Address</code> public.<br> …
> refactor: remove unnecessary inner_value methods by exposing the newtypes inner value where necessary

- src/eth/consensus/server.rs
- src/eth/primitives/account.rs
- src/eth/primitives/code_hash.rs
- src/eth/primitives/log_topic.rs
- src/eth/primitives/transaction_execution.rs
- src/eth/primitives/wei.rs
Enhancement
___
- Replaced various `inner` methods with direct field access across multiple structs (`CodeHash`, `LogTopic`, `Wei`).
- Added `as_local` method to `TransactionExecution` for extracting `LocalTransactionExecution`.
- Simplified field access in `TransactionExecution` and `Account` conversions.
- Refactored transaction execution extraction in `AppendEntryServiceImpl`.
___
<tr>
<td>
<details>
<summary><strong>server.rs</strong><dd><code>Refactor transaction execution extraction method</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
src/eth/consensus/server.rs
<li>Replaced <code>inner_local</code> method …
> refactor: remove unnecessary inner methods by exposing the newtypes inner value where necessary

- Cargo.lock
- Cargo.toml
dependencies
___
- Updated `openssl` dependency from version 0.10.64 to 0.10.66 to ensure the latest security patches and improvements are included.
- Pinned `nanoid` dependency to version 0.4.0 to ensure consistent builds and avoid potential issues with future versions.
___
<tr>
<td>
<details>
<summary><strong>Cargo.toml</strong><dd><code>Update and pin dependencies in Cargo.toml</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
Cargo.toml
<li>Updated <code>openssl</code> dependency from version 0.10.64 to 0.10.66.<br> <li> Pinned <code>nanoid</code> dependency to …
> deps: audit openssl and nanoid 

- Cargo.lock
- Cargo.toml
- src/eth/storage/rocks/mod.rs
- src/eth/storage/rocks/rocks_cf.rs
- src/eth/storage/rocks/rocks_db.rs
- src/eth/storage/rocks/rocks_permanent.rs
- src/eth/storage/rocks/rocks_state.rs
- src/eth/storage/rocks/types/slot.rs
- tests/test_import_external_snapshot_rocksdb.rs
This PR improves error treatment in the lower layers of the RocksDB code.
Things that used to unwrap are now returned and errors are contextualized.
A couple of things to improve (possibly in another PR):
1. Ensure that panics are logged.
2. Minimize the amount of panics.
3. Ensure that all errors are logged once before returning.
4. Add more context (with anyhow) at the storage trait layers.
___
___
- Improved error handling across RocksDB-related modules using `anyhow`.
- Added detailed context to error messages for better debugging.
- Made several functions fallible to handle errors gracefully.
- Introduced `RocksCfIterator` for iterating over column families with error handling.
- Enhanced logging for block reads and other operations.
- Documented types used for …
> enha: improve rocksdb error treatment

- src/eth/executor/executor.rs
- src/eth/executor/revm.rs
- src/eth/primitives/stratus_error.rs
- src/eth/rpc/rpc_server.rs
___
- Changed return types of several transaction execution methods to use `Result` with `StratusError` for better error handling.
- Added new error variants in `StratusError` for transaction nonce mismatches and zero address transactions.
- Improved error parsing and logging in EVM execution.
- Enhanced error handling in RPC methods `eth_estimateGas`, `eth_call`, and `eth_sendRawTransaction`, including internal error checks.
___
<tr>
<td>
<details>
<summary><strong>executor.rs</strong><dd><code>Enhanced error handling in transaction execution methods</code>&nbsp; </dd></summary>
<hr>
src/eth/executor/executor.rs
<li>Changed return …
> enha: improve error handling of eth_call, eth_estimateGas and eth_sendRawTransaction

- src/eth/executor/evm.rs
- src/eth/executor/executor.rs
- src/eth/primitives/call_input.rs
- src/eth/primitives/external_transaction.rs
- src/eth/primitives/transaction_input.rs
- src/eth/rpc/rpc_middleware.rs
___
- Refactored the EVM executor to remove unused code and simplify transaction execution logic.
- Fixed the issue of computing external transaction metrics only after the transaction is persisted.
- Renamed `extract_function` to `solidity_signature` across multiple files for consistency.
- Added and documented new methods in `ExternalTransaction` for better code organization.
___
<tr>
<td>
<details>
<summary><strong>evm.rs</strong><dd><code>Refactor EVM executor and remove unused code</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr> …
> fix: computer external_transaction metrics only after transaction is persisted

- chaos/experiments/main.sh
Bug fix
___
- Redirected error output to `/dev/null` for file removal commands in `cleanup` function.
- Ensured cleanup commands do not fail if files or directories do not exist.
___
<tr>
<td>
<details>
<summary><strong>main.sh</strong><dd><code>Ignore errors when removing files in cleanup script</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
chaos/experiments/main.sh
<li>Redirected error output to <code>/dev/null</code> for file removal commands.<br> <li> Ensured cleanup commands do not fail if files or directories do not <br>exist.<br>
</details>
</td>
<td><a href="https://github.com/cloudwalk/stratus/pull/1526/files#diff-244c0f1739d9a0 …
> fix: ignore error when removing file on e2e

- src/alias.rs
- src/eth/executor/evm.rs
- src/eth/primitives/account.rs
- src/eth/primitives/address.rs
- src/eth/primitives/block.rs
- src/eth/primitives/block_header.rs
- src/eth/primitives/block_number.rs
- src/eth/primitives/bytes.rs
- src/eth/primitives/external_block.rs
- src/eth/primitives/external_receipt.rs
- src/eth/primitives/external_transaction.rs
- src/eth/primitives/log.rs
- src/eth/primitives/log_mined.rs
- src/eth/primitives/log_topic.rs
- src/eth/primitives/slot_index.rs
- src/eth/primitives/slot_value.rs
- src/eth/primitives/transaction_input.rs
- src/eth/primitives/transaction_mined.rs
- src/eth/primitives/transaction_stage.rs
- src/eth/primitives/unix_time.rs
- src/eth/primitives/wei.rs
- src/infra/blockchain_client/blockchain_client.rs
- src/infra/blockchain_client/pending_transaction.rs
- src/lib.rs
Enhancement
___
- Introduced a new module `alias.rs` to define common type aliases for external crates such as Serde, Ethers, and REVM.
- Replaced direct imports of external crate types with the newly defined aliases across multiple modules.
- Improved code readability and maintainability by using type aliases.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><details><summary>24 files</summary><table>
<tr>
<td>
<details>
<summary><strong>alias.rs</strong><dd><code>Introduce common type aliases for external crates</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
src/alias.rs
<li>Added type aliases for external crate types.<br> <li> Included aliases for Serde, Ethers, and …
> refactor: common type aliases in alias.rs

- Cargo.lock
- Cargo.toml
- src/eth/executor/evm.rs
- src/eth/storage/rocks/cf_versions.rs
- src/eth/storage/rocks/mod.rs
- src/eth/storage/rocks/rocks_state.rs
- src/eth/storage/rocks/types/account.rs
- src/eth/storage/rocks/types/execution.rs
Currently, we need to re-compute the entire database after any type change.
This PR lets a Column Family store an enum as a value, this enables us to change data that is stored and support multiple types. 
We are relying on `bincode` serialization of enums, as a consequence, we can't reorder variants in an enum or remove previous versions because `bincode` marks the variants an `i32` discriminant in order of declaration, by changing the declaration it will try using different types to deserialize, with different sizes and paddings.
___
Enhancement, Other
___
- Introduced a macro to implement versioned column family values and added new enums for different column family values.
- Updated `RocksStorageState` to use new versioned column family values, modifying methods to handle new enum …
> feat: support CF versions in RocksDB

- e2e/test/external/e2e-json-rpc.test.ts
Tests
___
- Added a new test case to the `eth_getLogs` suite to verify the correct number of logs returned for different block ranges.
- Introduced a helper function `sendNTransactions` to facilitate sending multiple transactions in tests.
- Ensured that `sendEvmMine` is awaited to maintain consistency and reliability in tests.
- Added multiple assertions to check log retrieval for single blocks and various block ranges.
___
<tr>
<td>
<details>
<summary><strong>e2e-json-rpc.test.ts</strong><dd><code>Enhance `eth_getLogs` tests with block range scenarios</code>&nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
e2e/test/external/e2e-json-rpc.test.ts
<li>Added a new test …
> test: improve external get logs test to test block ranges

- .github/workflows/docs-release.yml
- .github/workflows/lint-check.yml
- src/eth/miner/miner.rs
- src/eth/primitives/transaction_mined.rs
closes #1232
___
Enhancement, Tests, Configuration changes
___
- Refactored block processing in `miner.rs` by replacing `map` with `inspect` for better readability and performance.
- Enhanced transaction sorting test by adding an `is_sorted` function and replacing manual checks with assertions.
- Updated Rust Nightly version to 2024-07-19 in GitHub workflows for docs release and lint checks.
___
<tr>
<td>
<details>
<summary><strong>miner.rs</strong><dd><code>Refactor block processing with `inspect` method</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
src/eth/miner/miner.rs
<li>Replaced <code>map</code> …
> update nightly and fix new warnings

- src/config.rs
- src/infra/tracing/tracing.rs
Enhancement
___
- Made `tokio_console_address` an optional configuration parameter in `CommonConfig`.
- Updated `init_tracing` function to handle the optional `tokio_console_address`.
- Conditional initialization of the Tokio Console layer based on the presence of `tokio_console_address`.
- Adjusted tracing subscriber initialization to support the optional Tokio Console layer.
___
<tr>
<td>
<details>
<summary><strong>config.rs</strong><dd><code>Make `tokio_console_address` optional in configuration</code>&nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
src/config.rs
<li>Made <code>tokio_console_address</code> an optional configuration.<br> <li> Removed default …
> enha: make tokio-console optional

- src/eth/storage/redis/redis_permanent.rs
Enhancement
___
- Replaced inline key formatting with dedicated helper functions for better code readability and maintainability.
- Added `account_key`, `slot_key`, and `tx_key` helper functions to generate keys for accounts, slots, and transactions respectively.
- Updated key generation in methods like `read_block`, `read_transaction`, `read_account`, and `read_slot` to use the new helper functions.
___
<tr>
<td>
<details>
<summary><strong>redis_permanent.rs</strong><dd><code>Refactor key generation using helper functions</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr> …
> enha: use helper functions for keys

- chaos/experiments/main.sh
- docker/Dockerfile.run_with_importer_cached
- justfile
- src/eth/miner/miner_config.rs
- src/eth/primitives/account.rs
- src/eth/primitives/mod.rs
Enhancement
___
- Removed the `enable_test_accounts` configuration option and always enable test accounts in development mode.
- Added comments with names for test accounts in `src/eth/primitives/account.rs`.
- Removed `--enable-test-accounts` flag from `chaos/experiments/main.sh`.
- Removed `ENABLE_TEST_ACCOUNTS` environment variable from `docker/Dockerfile.run_with_importer_cached`.
- Removed `--enable-test-accounts` flag from various commands in `justfile`.
___
<tr>
<td>
<details>
<summary><strong>miner_config.rs</strong><dd><code>Always enable test accounts in development mode</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
> enha: always enable test-accounts in dev mode

- e2e/cloudwalk-contracts/patches/brlc-yield-streamer.patch
- e2e/test/automine/e2e-json-rpc.test.ts
- e2e/test/external/e2e-json-rpc.test.ts
- e2e/test/helpers/rpc.ts
- src/eth/rpc/rpc_server.rs
- src/eth/storage/inmemory/inmemory_permanent.rs
- src/eth/storage/permanent_storage.rs
- src/eth/storage/redis/redis_permanent.rs
- src/eth/storage/rocks/rocks_permanent.rs
- src/eth/storage/stratus_storage.rs
___
- Replaced `debug_setHead` with `stratus_reset` and `hardhat_reset` in the RPC server.
- Renamed `reset_at` to `reset` in various storage implementations and added `#[cfg(feature = "dev")]` attribute.
- Updated end-to-end tests to use `stratus_reset` instead of `debug_setHead`.
- Simplified `sendReset` function by removing conditional check for `isStratus`.
- Updated patch files to replace `debug_setHead` with `stratus_reset`.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><details><summary>8 files</summary><table>
<tr>
<td>
<details>
<summary><strong>rpc_server.rs</strong><dd><code>Replace debug_setHead with stratus_reset and hardhat_reset</code></dd></summary>
<hr> …
> feat: stratus_reset instead of debug_setHead

- src/eth/storage/permanent_storage.rs
- src/eth/storage/redis/redis_permanent.rs
___
- Added a TODO comment in `src/eth/storage/permanent_storage.rs` to update the `filter.to_block` type in the `read_logs` method.
- Refactored type aliases for Redis result types in `src/eth/storage/redis/redis_permanent.rs` for better clarity.
- Updated various methods in `RedisPermanentStorage` to use the new type aliases.
- Implemented the `read_logs` method in `RedisPermanentStorage` to retrieve and filter logs from Redis.
- Refactored key generation functions for blocks, accounts, slots, and transactions for better readability and consistency.
___
<tr>
<td>
<details>
<summary><strong>permanent_storage.rs</strong><dd><code>Add …
> enha: redis eth_getLogs

- src/eth/storage/redis/redis_permanent.rs
Enhancement
___
- Added support for saving and retrieving historical values for accounts and slots in Redis storage.
- Introduced new functions `key_account_history` and `key_slot_history` for generating keys to access historical data.
- Modified the `save_block` function to use `zadd` for storing historical data in Redis.
- Enhanced the `read_account` and `read_slot` functions to handle historical data retrieval based on the `StoragePointInTime` parameter.
___
<tr>
<td>
<details>
<summary><strong>redis_permanent.rs</strong><dd><code>Add support for historical values in Redis storage</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary> …
> enha: redis historical values

- src/eth/primitives/block_header.rs
- src/eth/primitives/hash.rs
- src/eth/primitives/mod.rs
- src/ext.rs
Tests, Enhancement
___
- Added tests for `BlockHeader` methods including hash calculation and parent hash.
- Introduced `Hash::ZERO` constant and removed the `zero` method.
- Enhanced `gen_test_serde` macro to generate both serde_json and bincode tests.
- Added serde tests for multiple primitives.
- Relocated `BlockHeader` tests from `mod.rs` to `block_header.rs`.
___
<tr>
<td>
<details>
<summary><strong>block_header.rs</strong><dd><code>Add tests and modify `parent_hash` initialization in `BlockHeader`</code></dd></summary>
<hr>
src/eth/primitives/block_header.rs
<li>Added tests for <code>BlockHeader</code> methods.<br> <li> Modified <code>parent_hash</code> …
> test: primitives serde test with serde_json and bincode

- Cargo.lock
- Cargo.toml
- src/eth/primitives/call_input.rs
- src/eth/primitives/ecdsa_rs.rs
- src/eth/primitives/ecdsa_v.rs
- src/eth/primitives/execution_metrics.rs
- src/eth/primitives/mod.rs
- src/eth/primitives/now.rs
___
- Enhanced multiple structs (`CallInput`, `EcdsaRs`, `EcdsaV`, `EvmExecutionMetrics`, `DateTimeNow`) with additional derives including `PartialEq`, `Eq`, `fake::Dummy`, and `serde::Serialize`/`Deserialize`.
- Implemented `Dummy<Faker>` for `EcdsaRs` and `EcdsaV`.
- Added `gen_test_serde!` macros for several structs to generate serde tests.
- Updated `fake` dependency in `Cargo.toml` to include the `chrono` feature.
___
<tr>
<td>
<details>
<summary><strong>call_input.rs</strong><dd><code>Enhance <code>CallInput</code> struct with additional derives and serde attributes</code></dd></summary>
<hr>
src/eth/primitives/call_input.rs …
> enha: more serde tests

- e2e/test/external/e2e-json-rpc.test.ts
Bug fix, Tests
___
- Added `await` to `sendEvmMine` calls in `eth_sendRawTransaction` test to ensure proper asynchronous handling.
- Fixed potential timing issues in the `eth_sendRawTransaction` test by awaiting `sendEvmMine`.
___
<tr>
<td>
<details>
<summary><strong>e2e-json-rpc.test.ts</strong><dd><code>Ensure asynchronous handling in JSON-RPC e2e tests</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
e2e/test/external/e2e-json-rpc.test.ts
<li>Added <code>await</code> to <code>sendEvmMine</code> calls to ensure proper asynchronous <br>handling.<br> <li> Fixed potential timing issues in <code>eth_sendRawTransaction</code> test.<br> …
> fix: test: e2e-external test not awating evm_mine

- src/eth/primitives/address.rs
- src/eth/primitives/block_header.rs
- src/eth/primitives/block_number.rs
- src/eth/primitives/bytes.rs
- src/eth/primitives/call_input.rs
- src/eth/primitives/chain_id.rs
- src/eth/primitives/code_hash.rs
- src/eth/primitives/difficulty.rs
- src/eth/primitives/execution_result.rs
- src/eth/primitives/execution_value_change.rs
- src/eth/primitives/gas.rs
- src/eth/primitives/hash.rs
- src/eth/primitives/index.rs
- src/eth/primitives/log.rs
- src/eth/primitives/log_mined.rs
- src/eth/primitives/log_topic.rs
- src/eth/primitives/miner_nonce.rs
- src/eth/primitives/nonce.rs
- src/eth/primitives/size.rs
- src/eth/primitives/slot_index.rs
- src/eth/primitives/slot_value.rs
- src/eth/primitives/unix_time.rs
- src/eth/primitives/wei.rs
- src/ext.rs
___
- Implemented `DebugAsJson` for various Ethereum primitive structs and enums.
- Removed custom `Debug` implementations where applicable.
- Added `serde_debug_json` test macro to ensure JSON serialization matches `Debug` output.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><details><summary>23 files</summary><table>
<tr>
<td>
<details>
<summary><strong>address.rs</strong><dd><code>Implement `DebugAsJson` for `Address` struct</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
src/eth/primitives/address.rs
- Added `DebugAsJson` derive to `Address` struct.
</details>
</td>
<td><a …
> enha: ensure all primitives implement DebugAsJson

- justfile
Enhancement
___
- Enhanced the E2E testing script to support multiple block modes by renaming `block-mode` to `block_modes`.
- Added logic to split the `block_modes` variable and iterate over each mode.
- Updated the test execution commands to handle multiple block modes, allowing for more flexible testing configurations.
___
<tr>
<td>
<details>
<summary><strong>justfile</strong><dd><code>Support multiple block modes in E2E tests</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
justfile
<li>Renamed <code>block-mode</code> to <code>block_modes</code> to support …
> test: block_modes can receive multiple modes

- e2e/test/automine/e2e-json-rpc.test.ts
- e2e/test/external/e2e-json-rpc.test.ts
Tests
___
- Added tests to check that contract code is available in the block it was deployed.
- Wrapped `eth_getCode` related tests in a `describe` block for better organization.
- Included `sendReset` calls before `eth_blockNumber` tests to ensure a clean state.
___
<tr>
<td>
<details>
<summary><strong>e2e-json-rpc.test.ts</strong><dd><code>Add tests for contract code availability and block number reset</code></dd></summary>
<hr>
e2e/test/automine/e2e-json-rpc.test.ts
<li>Added a test to check contract code availability in the block it was <br>deployed.<br> <li> Wrapped <code>eth_getCode</code> tests in a <code>describe</code> block.<br> <li> Added …
> test: contract availability after deployment

- src/eth/executor/evm.rs
- src/eth/executor/evm_input.rs
- src/eth/primitives/stratus_error.rs
___
- Enhanced error handling in EVM execution by adding specific handling for storage errors and converting errors to strings before returning.
- Changed the error type in the `Database` trait implementation from `anyhow::Error` to `StratusError`.
- Added a check in the `basic` method of `RevmSession` to ensure the `to` account has bytecode if it is a contract call, returning a specific error if not.
- Introduced a new method `is_contract_call` in `EvmInput` to determine if the input is a contract call.
- Extended the `StratusError` enum with a new variant `TransactionAccountNotContract` and modified the `TransactionFailed` variant to accept a string.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</st …
> feat: reject transactions that are calling a contract, but does not have a bytecode

- src/eth/storage/redis/redis_permanent.rs
Bug fix
___
- Modified the `zadd` command in `RedisPermanentStorage` to use the `NX` option, ensuring that only new elements are added to the sorted set.
- Replaced the direct `zadd` call with a custom Redis command using `redis::cmd` to incorporate the `NX` option.
___
<tr>
<td>
<details>
<summary><strong>redis_permanent.rs</strong><dd><code>Ensure historical values are only inserted if changed in Redis</code></dd></summary>
<hr>
src/eth/storage/redis/redis_permanent.rs
<li>Modified the <code>zadd</code> command to use the <code>NX</code> option to ensure only new <br>elements are added.<br> <li> Replaced the direct <code>zadd</code> call with a custom Redis …
> fix: only insert historical values if changed

- src/eth/storage/redis/redis_permanent.rs
Bug fix
___
- Fixed slot insertion logic in `RedisPermanentStorage` to include the block number in the JSON value.
- Added the `to_json_value` import to support the new slot insertion logic.
- Updated the serialization process for slot values to ensure the block number is included.
___
<tr>
<td>
<details>
<summary><strong>redis_permanent.rs</strong><dd><code>Fix slot insertion to include block number in Redis storage</code></dd></summary>
<hr>
src/eth/storage/redis/redis_permanent.rs
<li>Added import for <code>to_json_value</code>.<br> <li> Modified slot insertion to include block number in the JSON value.<br> <li> Updated serialization logic for slot …
> fix: force slot insertion

- src/eth/primitives/execution_account_changes.rs
- src/eth/storage/redis/redis_permanent.rs
___
- Renamed the `is_changed` method to `is_account_modified` in `ExecutionAccountChanges` to better reflect its purpose.
- Enhanced Redis storage logic to include block number in account and slot modifications, ensuring forced updates.
- Updated JSON serialization to include block number for both accounts and slots.
- Modified logic to only process accounts if they are modified, optimizing storage operations.
___
<tr>
<td>
<details>
<summary><strong>execution_account_changes.rs</strong><dd><code>Rename and update account modification check method</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr> …
> enha: force block changes to redis

- src/eth/storage/permanent_storage.rs
- src/eth/storage/redis/redis_permanent.rs
Enhancement, Error handling
___
- Enhanced `PermanentStorageConfig` to require `perm_storage_url` when `perm_storage_kind` is set to `redis`.
- Improved error handling for missing Redis URL in `PermanentStorageConfig`.
- Modified `RedisPermanentStorage::new` to accept a URL parameter.
- Added error handling for Redis client creation failure in `RedisPermanentStorage`.
___
<tr>
<td>
<details>
<summary><strong>permanent_storage.rs</strong><dd><code>Require and validate Redis URL in `PermanentStorageConfig`</code></dd></summary>
<hr>
src/eth/storage/permanent_storage.rs
<li>Added <code>log_and_err</code> import.<br> <li> Updated …
> feat: redis configuration url

- src/eth/executor/evm.rs
- src/eth/executor/executor.rs
- src/eth/executor/executor_config.rs
Enhancement
___
- Integrated `ExecutorConfig` into the `Evm` and `RevmSession` structs to centralize configuration.
- Modified `Evm::new` and `RevmSession::new` constructors to accept `ExecutorConfig` instead of `ChainId`.
- Added a new configuration option `reject_not_contract` to `ExecutorConfig` to control whether transactions to non-contract accounts should be rejected.
- Updated logging to reflect the inclusion of `ExecutorConfig`.
- Adjusted the EVM spawning logic to utilize the new `ExecutorConfig`.
___
<tr>
<td>
<details>
<summary><strong>evm.rs</strong><dd><code>Integrate `ExecutorConfig` into EVM and RevmSession</code>&nbsp; &nbsp; &nbsp; &nbsp; …
> feat: configure if transactions to non-contracts should be rejected

- src/eth/consensus/mod.rs
- src/eth/consensus/tests/factories.rs
- src/eth/executor/evm_input.rs
- src/eth/primitives/log_mined.rs
- src/eth/primitives/mod.rs
Enhancement
___
- Removed obsolete comments in `Consensus` implementation.
- Removed obsolete comments in `create_mock_consensus` function.
- Removed obsolete comments in `EvmInput` implementation.
- Removed obsolete comments in `LogMined` implementation.
- Removed multiple obsolete comments in `primitives` module tests.
___
<tr>
<td>
<details>
<summary><strong>mod.rs</strong><dd><code>Remove obsolete comment in `Consensus` implementation</code>&nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
src/eth/consensus/mod.rs
- Removed obsolete comment.
</details>
</td>
<td><a href="https://github.com/cloudwalk/stratus/pull/1581/files#diff-f7df3d82112cd8c1758b7ccd9 …
> chore: remove obsolete commentaries

- src/eth/primitives/mod.rs
I removed those commentaries by mistake 😅
___
documentation
___
- Restored previously removed test commentaries in `src/eth/primitives/mod.rs`.
- Added `FIX` and `TODO` markers for various test cases to indicate required fixes and pending implementations.
___
<tr>
<td>
<details>
<summary><strong>mod.rs</strong><dd><code>Restore and annotate test commentaries in `mod.rs`</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
src/eth/primitives/mod.rs
<li>Restored previously removed test commentaries.<br> <li> Added <code>FIX</code> and <code>TODO</code> markers for various test cases.<br>
</details>
</td>
<td><a …
> chore: restore test commentaries

- config/stratus.env.local
- src/infra/metrics/metrics_definitions.rs
- src/infra/tracing/tracing.rs
Enhancement, Configuration changes
___
- Simplified the `rpc_requests_active` gauge definition by removing labels.
- Added temporary metrics collection from tracing events, including a new `event_to_metrics` function to parse and set metrics.
- Modified the `TracingLog` struct to use `JsonValue` for fields instead of `SerializeFieldMap`.
- Updated the `RUST_LOG` configuration to include `jsonrpsee-server=debug` for better logging visibility.
___
<tr>
<td>
<details>
<summary><strong>metrics_definitions.rs</strong><dd><code>Simplified `rpc_requests_active` gauge definition</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr> …
> feat: compute rpc active connections metrics from jsonrpsee logs

- config/importer-offline.env.local
- src/bin/importer_offline.rs
- src/eth/primitives/external_block.rs
- src/eth/primitives/external_transaction.rs
___
- Added a method to `ExternalTransaction` to infer and fill the `transaction_type` field based on the `v` value.
- Modified the block import loop to utilize the new method for filling missing `transaction_type`.
- Added `DerefMut` derive to `ExternalBlock` to allow mutable dereferencing.
- Simplified the match arm for `BlockFilter::Hash` in `RocksStorageState`.
___
<tr>
<td>
<details>
<summary><strong>importer_offline.rs</strong><dd><code>Fill missing transaction_type during block import</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
src/bin/importer_offline.rs
<li>Added import for …
> tweak: infer transaction type from tx signature

- src/eth/storage/postgres_external_rpc/postgres_external_rpc.rs
enhancement
___
- Added a warning log in `PostgresExternalRpcStorage::new` to notify if the RPC storage connection URL does not contain the `?app=NAME` query parameter.
- Imported the `not` utility function to facilitate the new warning condition.
___
<tr>
<td>
<details>
<summary><strong>postgres_external_rpc.rs</strong><dd><code>Add warning for unidentified RPC storage connection URL</code>&nbsp; &nbsp; </dd></summary>
<hr>
src/eth/storage/postgres_external_rpc/postgres_external_rpc.rs
<li>Added a warning log if the RPC storage connection URL does not contain <br>a specific query parameter.<br> <li> Imported a new utility function <code>not</code>.<br> …
> tweak: warn if RPC storage connection is unidentified

- utils/slack-notifiers/comments.rb
We're not using this tag in code and it's also giving false positives.
Bugs should probably go into issues.
> chore: remove BUG tag from the slack comment notifier

- src/eth/executor/executor.rs
- src/eth/rpc/rpc_context.rs
- src/eth/rpc/rpc_middleware.rs
- src/eth/storage/rocks/rocks_state.rs
enhancement
___
- Added conditional compilation for `metrics` feature in multiple files.
- Removed unnecessary `#[allow(dead_code)]` attribute in `rpc_context.rs`.
- Added conditional attribute to allow unused variables when `metrics` feature is not enabled in `rpc_middleware.rs`.
___
<tr>
<td>
<details>
<summary><strong>executor.rs</strong><dd><code>Add conditional compilation for metrics feature</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
src/eth/executor/executor.rs
- Added conditional compilation for `metrics` feature.
</details>
</td>
<td><a …
> chore: solve warnings

- src/eth/storage/permanent_storage.rs
enhancement
___
- Removed an outdated TODO comment in the `read_logs` method of the `PermanentStorage` trait.
___
<tr>
<td>
<details>
<summary><strong>permanent_storage.rs</strong><dd><code>Remove outdated TODO comment in `PermanentStorage` trait</code>&nbsp; </dd></summary>
<hr>
src/eth/storage/permanent_storage.rs
- Removed an outdated TODO comment.
</details>
</td>
<td><a href="https://github.com/cloudwalk/stratus/pull/1601/files#diff-7b27a17201e5a4916214bb7bebbeaba2874cce309edd6f628018abe45f88a1c5">+0/-2</a>&nbsp; &nbsp; &nbsp; </td>
</tr>                    
</table></td></tr></tr></tbody></table>
___
> 💡 **PR-Agent usage**:
>Comment `/help` on the …
> chore: remove outdated todo at permanent_storage

- config/stratus-follower.env.local
- justfile
- src/config.rs
Enhancement, Configuration changes
___
- Added support for custom local environment paths in the dotenv loading process.
- Introduced a new environment configuration file for `stratus-follower`.
- Updated `justfile` to remove hardcoded external RPC URLs and use `LOCAL_ENV_PATH` for `stratus-follower`.
___
<tr>
<td>
<details>
<summary><strong>config.rs</strong><dd><code>Support custom local environment paths in dotenv loading</code>&nbsp; </dd></summary>
<hr>
src/config.rs
<li>Added support for custom local environment paths.<br> <li> Modified logic to determine the <code>.env</code> file to load based on the <br>environment.<br> <li> Introduced handling …
> enha: allow custom env when local

- config/stratus-follower.env.local
- justfile
enhancement, configuration changes
___
- Updated the `stratus-follower.env.local` configuration file to include the `ADDRESS` setting and changed `EXTERNAL_RPC` and `EXTERNAL_RPC_WS` to use localhost.
- Added `run-follower` and `run-importer` aliases to the `justfile`.
___
<tr>
<td>
<details>
<summary><strong>stratus-follower.env.local</strong><dd><code>Update follower environment configuration</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
config/stratus-follower.env.local
<li>Added <code>ADDRESS</code> configuration.<br> <li> Updated …
> feat: justfile follower commands and configs

- src/eth/consensus/mod.rs
- src/eth/consensus/raft/mod.rs
- src/eth/consensus/simple_consensus/mod.rs
- src/eth/importer/importer.rs
- src/eth/rpc/rpc_context.rs
- src/eth/rpc/rpc_server.rs
- src/main.rs
___
- Enhanced the `Consensus` trait by adding default methods for `should_serve` and `forward`, along with new methods `get_chain` and `lag`.
- Implemented the `Consensus` trait for `Importer`, `Raft`, and `SimpleConsensus` structs.
- Modified the `RpcContext` and RPC server to handle an optional `consensus`.
- Updated the `run` function in `main.rs` to initialize `consensus` as an `Option`.
___
<tr>
<td>
<details>
<summary><strong>mod.rs</strong><dd><code>Enhance `Consensus` trait with default methods and error handling</code></dd></summary>
<hr>
src/eth/consensus/mod.rs
<li>Implemented default methods for <code>should_serve</code> …
> enha: implement Consensus trait for Importer

- src/eth/consensus/mod.rs
Bug fix
___
- Corrected a typo in the log message within the `src/eth/consensus/mod.rs` file. The word "appart" was changed to "apart".
___
<tr>
<td>
<details>
<summary><strong>mod.rs</strong><dd><code>Corrected typo in log message</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
src/eth/consensus/mod.rs
- Fixed a typo in a log message.
</details>
</td>
<td><a href="https://github.com/cloudwalk/stratus/pull/1609/files#diff-f7df3d82112cd8c1758b7ccd906775c78e1cf8860f0d2ac7c0d6e5ad9ab92f80">+ …
> chore: fix typo

- static/diagrams/components.pik
- static/diagrams/components.svg
documentation
___
- Adjusted the vertical positioning of arrows in the `components.pik` diagram file to ensure correct alignment from `RpcServer` to `Executor` and `Miner`.
___
<tr>
<td>
<details>
<summary><strong>components.pik</strong><dd><code>Fix arrow positioning in components diagram</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
static/diagrams/components.pik
<li>Adjusted the vertical positioning of arrows from <code>RpcServer</code> to <code>Executor</code> <br>and <code>Miner</code>.<br>
</details>
</td>
<td><a …
> doc: fix components.svg

- src/eth/consensus/raft/tests/test_simple_blocks.rs
- src/eth/storage/rocks/rocks_state.rs
Bug fix, Tests
___
- Fixed the `read_logs` method in `RocksStorageState` to filter logs directly instead of filtering transactions by address.
- Simplified the log extraction process by removing unnecessary transaction filtering.
- Improved code readability by renaming the block number range checking closure.
- Updated test module with necessary imports.
___
<tr>
<td>
<details>
<summary><strong>rocks_state.rs</strong><dd><code>Fix and simplify log filtering in `read_logs` method</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
src/eth/storage/rocks/rocks_state.rs
<li>Removed filtering of transactions by address in <code>read_logs</code> …
> fix: RocksDB `eth_getLogs` filtering address by transaction instead of log

- src/eth/storage/rocks/rocks_state.rs
this contribution was mistakenly removed by #871
___
Bug fix
___
- Reintroduced account change checks that were mistakenly removed in a previous commit.
- Added a conditional check to ensure account modifications are only processed when changes occur.
- Updated logic to push account changes and history changes only when modifications are detected.
___
<tr>
<td>
<details>
<summary><strong>rocks_state.rs</strong><dd><code>Reintroduce and conditionally check account changes</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
src/eth/storage/rocks/rocks_state.rs
<li>Reintroduced account change checks that were mistakenly removed.<br> <li> Wrapped …
> fix: reintroduce #908

- src/eth/rpc/rpc_parser.rs
- src/eth/storage/rocks/rocks_state.rs
enhancement
___
- Added a documentation link to the `parse_rpc_rlp` function in `rpc_parser.rs`.
- Simplified the `RocksStorageState` implementation by removing unnecessary clone operations and using `self` references directly.
- Updated iteration over transactions to use `iter().cloned()` instead of `clone()`.
___
<tr>
<td>
<details>
<summary><strong>rpc_parser.rs</strong><dd><code>Add documentation link to `parse_rpc_rlp` function</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
src/eth/rpc/rpc_parser.rs
- Added a documentation link to the `parse_rpc_rlp` function.
</details>
</td>
<td><a …
> chore: simplify code

- src/eth/executor/executor.rs
- src/eth/miner/miner.rs
- src/eth/storage/inmemory/inmemory_temporary.rs
- src/eth/storage/stratus_storage.rs
- src/eth/storage/temporary_storage.rs
Enhancement
___
- Introduced a new `check_conflicts` boolean parameter in the `save_execution` method across multiple components (executor, miner, storage).
- Implemented conditional conflict checking for transaction executions, allowing skipping of conflict checks for external transactions.
- Updated the `TemporaryStorage` trait to include the new `check_conflicts` parameter.
- Renamed internal functions in the inmemory storage implementation for better clarity (e.g., `read_account` to `do_read_account`).
- Modified the executor to pass `false` for external transactions and `true` for local transactions when calling `save_execution`.
___
<tr>
<td> …
> perf: skip conflict checks for external transactions

- src/eth/executor/evm_input.rs
- src/eth/executor/executor.rs
- src/eth/primitives/execution.rs
Fist step to remove unnecessary `ExternalBlock` clones is receiving only the necessary external block fields, usually number and timestamp, in functions instead of a reference to the entire external block.
___
Enhancement, Performance
___
- Reduced dependency on `ExternalBlock` across multiple files, improving performance by avoiding unnecessary cloning.
- Refactored functions to accept specific block properties (number and timestamp) instead of the entire block object.
- Updated `EvmInput`, `Executor`, and `EvmExecution` to work with individual block properties.
- Optimized error logging and execution tracking to use specific block information.
- Removed unused imports related to `ExternalBlock`.
___ …
> perf: do not depend on entire block

- src/bin/importer_offline.rs
- src/eth/executor/executor.rs
- src/eth/follower/importer/importer.rs
- src/eth/primitives/external_block.rs
- src/eth/primitives/external_receipts.rs
Enhancement
___
- Optimized block and transaction execution by removing unnecessary cloning and improving memory usage
- Refactored `execute_external_block` and related functions to take ownership of data instead of borrowing
- Updated `ExternalReceipts` to consume receipts when accessed, reducing redundant data storage
- Improved logging and metrics collection throughout the execution process
- Added mutable dereferencing for `ExternalBlock` struct
- Minor code cleanup and variable naming improvements
___
<tr>
<td>
<details>
<summary><strong>importer_offline.rs</strong><dd><code>Optimize offline importer block execution</code>&nbsp; &nbsp; &nbsp; &nbsp; …
> perf: remove unnecessary block, transcation and receipt clones

- src/eth/follower/importer/importer.rs
- src/eth/miner/miner.rs
Enhancement
___
- Removed unused `mine_external_mixed()` and `mine_external_mixed_and_commit()` methods from the `Miner` struct
- Updated the importer to use `mine_external_and_commit()` instead of `mine_external_mixed_and_commit()`
- Simplified the miner implementation by removing logic for mining external mixed blocks
- This change reduces code complexity and removes unused functionality
___
<tr>
<td>
<details>
<summary><strong>importer.rs</strong><dd><code>Update miner method call in importer</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
> refactor: remove unused mine_external_mixed from miner

- src/eth/miner/miner.rs
Enhancement
___
- Optimize `save_execution` method by computing `tx_hash` once at the beginning
- Update tracing span to use pre-computed `tx_hash`, reducing redundant computations
- Reorder operations in `save_execution`:
- Notify about pending transactions before mining in automine mode
- Improve code readability and potentially slight performance gain
- These changes aim to enhance performance by avoiding unnecessary recomputation of `tx_hash`
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Performance optimization</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>miner.rs</strong><dd><code>Optimize transaction hash computation and execution flow</code>&nbsp; </dd></summary>
<hr>
src/eth/miner/miner.rs
<li>Compute …
> perf: avoid recomputing tx_hash when saving execution

- src/bin/rpc_downloader.rs
- src/eth/follower/importer/importer.rs
- src/eth/miner/miner.rs
- src/eth/primitives/block_number.rs
- src/eth/primitives/code_hash.rs
- src/eth/primitives/execution.rs
- src/eth/primitives/execution_conflict.rs
- src/eth/primitives/external_transaction.rs
- src/eth/primitives/log_mined.rs
- src/eth/primitives/nonce.rs
- src/eth/rpc/rpc_middleware.rs
- src/eth/rpc/rpc_subscriptions.rs
- src/eth/storage/inmemory/inmemory_history.rs
- src/eth/storage/inmemory/inmemory_temporary.rs
- src/eth/storage/redis/redis_permanent.rs
- src/eth/storage/rocks/rocks_state.rs
- src/eth/storage/stratus_storage.rs
- src/ext.rs
In this PR I try removing unwraps, or, when not possible, replacing them by expect with a message of why that isn't going to fail.
___
___
- Improved error handling across multiple modules by replacing `unwrap()` calls with proper error handling mechanisms.
- Enhanced the `ExternalTransaction` struct to return `Result<BlockNumber>` instead of unwrapping.
- Implemented `TryFrom` trait for `SubscriptionMessage` conversion to handle potential serialization errors.
- Simplified and optimized various utility functions and methods, including JSON handling and type manipulations.
- Improved RPC logging by using pretty-printed JSON strings.
- Enhanced test suite by using temporary directories and removing unnecessary file system operations.
- Refactored JSON object …
> chore: review error handling and remove unwraps 

- src/config.rs
- src/eth/follower/consensus.rs
- src/infra/metrics/metrics_definitions.rs
Enhancement
___
- Removed unused consensus-related configuration from `CommonConfig` struct in `src/config.rs`
- Cleaned up unused consensus metrics in `src/infra/metrics/metrics_definitions.rs`
- Fixed a typo in a log message in the consensus module
- Overall, this PR removes leftover unused code related to consensus, improving code cleanliness and maintainability
___
<tr>
<td>
<details>
<summary><strong>config.rs</strong><dd><code>Remove unused consensus-related configuration</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
src/config.rs
<li>Removed unused import of …
> chore: remove unused leftover consensus code

- src/bin/importer_offline.rs
- src/eth/executor/executor.rs
- src/eth/follower/importer/importer.rs
- src/eth/primitives/external_receipts.rs
Enhancement
___
- Optimized block execution by passing receipts as mutable reference instead of cloning
- Simplified and renamed methods in `ExternalReceipts` struct for better clarity and efficiency
- Improved variable naming throughout the codebase for better readability
- Removed unnecessary cloning and unused methods to enhance performance
- Updated function signatures and calls to reflect the new optimized approach
- Simplified block mining process in the importer
- Adjusted logging and metrics to provide more accurate information
___
<tr>
<td>
<details>
<summary><strong>importer_offline.rs</strong><dd><code>Optimize block execution and improve …
> perf: remove more unnecessary cloning and pass receipts by mutable reference

- src/eth/executor/evm_result.rs
- src/eth/primitives/address.rs
- src/eth/primitives/block_filter.rs
- src/eth/primitives/execution.rs
- src/eth/primitives/execution_account_changes.rs
- src/eth/primitives/execution_conflict.rs
- src/eth/primitives/log_filter.rs
- src/eth/primitives/log_filter_input.rs
- src/eth/primitives/mod.rs
- src/eth/primitives/transaction_execution.rs
- src/eth/primitives/transaction_mined.rs
- src/ext.rs
Tests, Enhancement
___
- Enhanced serialization and deserialization for multiple types, including `BlockFilter`, `EvmExecution`, and `ExecutionAccountChanges`.
- Added test-specific attributes to various structs and enums to improve testability.
- Implemented `DebugAsJson` for several types to improve debug output.
- Removed bincode-specific serde tests and focused on JSON serialization.
- Added support for ordered map serialization in test environments.
- Updated and expanded serde tests for primitive types in the `mod.rs` file.
- Improved case-insensitive deserialization for `BlockFilter`.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Tests</strong></td><td><details><summary>7 files</summary><table>
<tr>
<td>
<details> …
> tests: add tests for more primitive types

- src/eth/primitives/block.rs
- src/eth/storage/inmemory/inmemory_permanent.rs
Enhancement
___
- Optimized `InMemoryPermanentStorage` to reduce memory usage and improve performance:
- Removed separate storage of logs, now retrieving them from blocks
- Changed transaction storage to keep entire blocks, reducing duplication
- Improved `read_logs` method to filter logs more efficiently
- Enhanced `Block::compact_account_changes` method to minimize cloning:
- Updated to use references instead of cloning data
- Changed method calls to use `take_modified_ref` for better performance
- Added `itertools` crate dependency for improved iteration methods
- Removed unnecessary cloning operations throughout the codebase
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Performance optimization</strong></td><td><table>
<tr>
<td> …
> perf: improve InMemoryPermanentStorage#save_block

- Cargo.toml
- src/bin/rocks_revert_to_block.rs
- src/config.rs
- src/eth/executor/executor.rs
- src/eth/storage/rocks/rocks_cf.rs
- src/eth/storage/rocks/rocks_permanent.rs
- src/eth/storage/rocks/rocks_state.rs
Enhancement
___
- Implemented a new binary `rocks_revert_to_block.rs` to revert RocksDB state to a specified block number
- Added `RocksRevertToBlockConfig` for configuration of the new binary
- Enhanced `RocksStorageState` with `revert_state_to_block` method to handle state reversion logic
- Added `delete`, `iter_start`, and `iter_end` methods to improve RocksDB column family operations
- Implemented `revert_state_to_block` in `RocksPermanentStorage` to expose the functionality
- Updated Cargo.toml to include the new binary
- Minor documentation and code refactoring improvements
___
<tr>
<td>
<details> …
> feat: new binary to revert RocksDB blocks

- src/eth/primitives/log_filter.rs
- src/eth/storage/inmemory/inmemory_permanent.rs
- src/eth/storage/inmemory/inmemory_temporary.rs
- src/eth/storage/stratus_storage.rs
Enhancement
___
- Refactored storage-related test methods and implementations:
- Removed `mock_new` and `mock_new_rocksdb` methods from `StratusStorage`
- Removed `new` methods from `InMemoryPermanentStorage` and `InMemoryTemporaryStorage`
- Updated `log_filter.rs` to use `StratusStorage::new` instead of `StratusStorage::mock_new`
- Removed conditional imports for test configuration in `stratus_storage.rs`
- Overall, this PR simplifies the storage implementations and removes test-specific methods, promoting better separation of concerns
___
<tr>
<td>
<details>
<summary><strong>log_filter.rs</strong><dd><code>Update log filter test setup</code>&nbsp; …
> refactor: remove storage test methods

- Cargo.lock
fixes several dependabot issues
- https://github.com/cloudwalk/stratus/security/dependabot/21
- https://github.com/cloudwalk/stratus/security/dependabot/20
- https://github.com/cloudwalk/stratus/security/dependabot/18
- https://github.com/cloudwalk/stratus/security/dependabot/36
- https://github.com/cloudwalk/stratus/security/dependabot/19
> deps: update rustls, whoami, openssl and h2

- justfile_helpers
Bug fix
___
- Increased the wait timeout for Stratus startup from 60 to 120 seconds to accommodate builds without cache
- Updated the log message to reflect the new timeout duration (120 seconds instead of 60)
- This change aims to prevent errors that occur when Stratus takes longer to start, especially in builds without cache
___
<tr>
<td>
<details>
<summary><strong>justfile_helpers</strong><dd><code>Extend Stratus startup wait timeout</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
justfile_helpers
<li>Increased the …
> fix: increase wait timeout to avoid errors on builds without cache

- build.rs
Looks like a consequence of https://github.com/cloudwalk/stratus/pull/1629 not updating build.rs.
> chore: fix unnecessary recompilation

- src/eth/rpc/rpc_subscriptions.rs
- src/ext.rs
- src/infra/tracing/tracing_services.rs
This was causing a leak because of an unbounded Vec in https://github.com/tokio-rs/tracing-opentelemetry/blob/v0.1.x/src/layer.rs#L978 .
___
Bug fix
___
- Set tracing events parents to None for long-lived subscription tasks to prevent memory leaks
- Updated error logging in RPC subscriptions to use `parent: None`
- Modified task spawn logging to use `parent: None`
- Addresses a potential memory leak caused by an unbounded Vec in tracing-opentelemetry
___
<tr>
<td>
<details>
<summary><strong>rpc_subscriptions.rs</strong><dd><code>Update error logging in RPC subscriptions</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
> fix: set tracing events parents to None on long lived subscription tasks

- e2e/test/external/e2e-json-rpc.test.ts
Bug fix, Tests
___
- Fixed asynchronous behavior in JSON-RPC tests by adding `await` to `sendEvmMine()` calls
- Uncommented and fixed a previously intermittent test case that checks if eth_call works with 'input' field instead of 'data'
- Removed FIXME comment explaining the intermittent test issue, as it has been resolved
- Improved test reliability and coverage for JSON-RPC functionality
___
<tr>
<td>
<details>
<summary><strong>e2e-json-rpc.test.ts</strong><dd><code>Fix async behavior in JSON-RPC tests</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
> fix(e2e): await evm mine

- src/config.rs
- src/globals.rs
Enhancement
___
- Added a new configuration option `unknown_client_enabled` to `CommonConfig` in `src/config.rs`.
- This option can be set via an environment variable `UNKNOWN_CLIENT_ENABLED` with a default value of `true`.
- Updated `src/globals.rs` to set the `unknown_client_enabled` value in the global state.
___
<tr>
<td>
<details>
<summary><strong>config.rs</strong><dd><code>Add `unknown_client_enabled` configuration option to `CommonConfig`</code></dd></summary>
<hr>
src/config.rs
<li>Added a new configuration option <code>unknown_client_enabled</code> to <br><code>CommonConfig</code>.<br> <li> This option can be set via an environment variable …
> enha: add unknown_client_enabled config

- src/eth/storage/inmemory/inmemory_permanent.rs
- src/eth/storage/rocks/mod.rs
- src/eth/storage/rocks/rocks_batch_writer.rs
- src/eth/storage/rocks/rocks_cf.rs
- src/eth/storage/rocks/rocks_permanent.rs
- src/eth/storage/rocks/rocks_state.rs
- src/eth/storage/rocks/types/block_number.rs
- src/eth/storage/rocks/types/slot.rs
it's now constant in memory complexity and writes everything in batches
to reduce overhead
previously, this binary was O(Slots) in memory and was crashed by OS's
OOM when running with our production database due to the amount
of slots
now, it shouldn't crash
___
Enhancement
___
- Implemented `BufferedBatchWriter` and `CfBufferedBatchWriter` for efficient batch operations in RocksDB
- Refactored and optimized `revert_state_to_block` method to use `BufferedBatchWriter`, improving memory usage and performance
- Enhanced `RocksCfRef` with new methods and improved iterators
- Added `Add` trait implementation for `BlockNumberRocksdb` and `Copy` trait for `SlotValueRocksdb`
- Minor formatting improvements in some files
___ …
> enha: improve rocks revert to block

- src/bin/importer_offline.rs
there is currently no benefit in having a larger backlog size, and we've been experiencing OOM problems, so this PR reduces it
___
Enhancement
___
- Reduced the `BACKLOG_SIZE` constant in the importer_offline module from 50 to 10
- This change aims to address Out of Memory (OOM) issues experienced with the larger backlog size
- The smaller backlog size is expected to improve memory usage without significant performance impact
___
<tr>
<td>
<details>
<summary><strong>importer_offline.rs</strong><dd><code>Decrease importer offline backlog size</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
> tweak: importer-offline decrease backlog size

- e2e/cloudwalk-contracts/integration/test/leader-follower.test.ts
- src/eth/primitives/stratus_error.rs
- src/eth/rpc/rpc_server.rs
___
- Improved handling of leader and follower node behavior in RPC functions:
- Modified `stratus_health` to check consensus readiness for follower nodes only.
- Updated `eth_send_raw_transaction` to use `NodeMode` for determining leader/follower status.
- Added new error `RpcConsensusUnavailable` for cases when consensus is unavailable for follower nodes.
- Enhanced integration tests:
- Added health checks for both leader and follower nodes.
- Modified BRLC contract deployment test to demonstrate transaction forwarding via follower node.
- Improved error handling and logging for consensus-related issues.
___
<tr>
<td>
<details> …
> enha: expose leader/follower branching on health and send_raw_transaction endpoints

- src/eth/storage/rocks/rocks_state.rs
for the logging, they did overflow previously
___
Bug fix
___
- Fixed potential integer overflow issues in the `RocksStorageState` implementation
- Changed the type of counter variables from implicit integer to explicit `u64`:
- `history_accounts_count`
- `accounts_count`
- `history_slots_count`
- `slots_count`
- This change ensures that these counters can handle large numbers without overflowing
- Improves code clarity and prevents potential bugs related to integer size assumptions
___
<tr>
<td>
<details>
<summary><strong>rocks_state.rs</strong><dd><code>Explicit type declaration for counter variables</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
> fix: slot counters in rocks revert_to_block

- src/bin/rpc_downloader.rs
- src/eth/storage/postgres_external_rpc/postgres_external_rpc.rs
Enhancement
___
- Improved URL validation for external RPC:
- Added a check in `rpc_downloader.rs` to verify if the external RPC URL contains 'app=' or '/app/'
- Implemented a warning log if the URL doesn't contain the expected identifier
- Removed redundant URL check from `postgres_external_rpc.rs`:
- Deleted the previous warning log and associated import
- Enhanced code organization by moving the URL check to a more appropriate location
___
<tr>
<td>
<details>
<summary><strong>rpc_downloader.rs</strong><dd><code>Add URL identifier check and warning</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
> tweak: adjust misleading warning

- src/eth/storage/rocks/rocks_state.rs
___
- Refactored `RocksStorageState` implementation:
- Simplified `prepare_batch_with_execution_changes` method
- Removed unused `write_accounts` function
- Made `write_slots` method test-only
- Added new test-only methods:
- `read_all_accounts`: Reads all accounts from the database
- `read_all_historical_accounts`: Reads all historical accounts from the database
- Implemented regression test to ensure unmodified accounts aren't saved in history
- Minor code cleanup and formatting improvements
___
<tr>
<td>
<details>
<summary><strong>rocks_state.rs</strong><dd><code>Refactor RocksStorageState and add regression test</code>&nbsp; &nbsp; …
> regression test: don't save unchanged accounts to history 

- src/eth/executor/executor.rs
- src/eth/miner/miner.rs
Bug fix
___
- Fixed a critical bug in the `Executor` implementation where the wrong mutex was being cleared of poison. The correct mutex (`self.miner.locks.mine_and_commit`) is now being cleared instead of `self.locks.serial`.
- Improved error handling in the `Miner` implementation for the `save_execution` lock. Now using `expect()` with a descriptive error message instead of `unwrap()`.
- These changes enhance the robustness and maintainability of the codebase, particularly in concurrent execution scenarios.
___
<tr>
<td>
<details>
<summary><strong>executor.rs</strong><dd><code>Fix mutex poison clearing in Executor</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
> fix: clear poison from wrong Mutex

- src/eth/storage/rocks/rocks_state.rs
Enhancement
___
- Refactored `prepare_batch_with_execution_changes` method to accept owned changes, improving efficiency
- Eliminated unnecessary intermediate buffers, reducing memory usage
- Simplified the code by processing account and slot changes in a single loop
- Updated method signature to use generic `IntoIterator` for better flexibility
- Modified test cases to align with the new method signature
- Improved overall performance by reducing allocations and iterations
___
<tr>
<td>
<details>
<summary><strong>rocks_state.rs</strong><dd><code>Optimize batch preparation for execution changes</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
> enha: simplify code in execution changes batching

- src/eth/executor/executor.rs
- src/eth/follower/importer/importer.rs
- src/eth/miner/miner.rs
- src/eth/storage/storage_point_in_time.rs
- src/infra/tracing/tracing_services.rs
Documentation, Enhancement
___
- Removed redundant documentation comments for `new` functions in multiple files (executor.rs, importer.rs, miner.rs)
- Improved documentation formatting in `storage_point_in_time.rs`:
- Updated code references to use backticks instead of square brackets
- Ensured consistent formatting for `Account`, `Slot`, and `Mined` references
- Enhanced URL formatting in `tracing_services.rs` by using angle brackets for proper linking
- These changes improve code documentation clarity and adhere to Rust documentation best practices
___
<tr>
<td>
<details>
<summary><strong>executor.rs</strong><dd><code>Remove redundant documentation …
> chore: solve cargo doc warnings

- src/eth/executor/executor.rs
- src/eth/miner/miner.rs
- src/eth/primitives/block_header.rs
- src/eth/storage/rocks/rocks_state.rs
- src/ext.rs
Now, no Mutex lock is called with an `unwrap()` anymore, it's either logged and the poison is cleared, or we wrap it in an error and return it
Plus, I promoted some warnings to errors, as poisons aren't expected and can be catastrophic.
> enha: improve error handling for Mutex

- src/eth/storage/rocks/rocks_state.rs
to ensure that it actually generates slots that are extra and different from the previous ones
___
___
- Enhanced the test data generation for extra slots in the `rocks_state.rs` file:
- Replaced the range-based approach with `iter::repeat_with()` for generating extra slots
- Added a `.take(1000)` to ensure exactly 1000 extra slots are generated
- This change guarantees that all generated extra slots are unique and different from the existing slots
- Improved code efficiency and readability in the test module
- Added `use std::iter;` import to support the new implementation
___
<tr>
<td>
<details> …
> test: small fix on test

- src/eth/primitives/execution.rs
- src/eth/primitives/stratus_error.rs
- src/utils.rs
logs shouldn't have dynamic event names because that makes querying harder
___
Enhancement
___
- Implemented structured logging across multiple files to improve log querying and readability
- Updated tracing macros (trace!, warn!, info!) to use named parameters instead of string interpolation
- Reduced the use of dynamic event names in logs, making it easier to query and analyze log data
- Maintained consistent logging format across different components (EvmExecution, StratusError, DropTimer)
___
<tr>
<td>
<details>
<summary><strong>execution.rs</strong><dd><code>Enhance logging in EvmExecution comparison</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
> chore: decrease amount of dynamic event named logs

- src/eth/executor/evm.rs
- src/eth/primitives/bytes.rs
This was causing a few issues:
1. We were double padding the bytecode, adding 66 0s to the end of it. This kept us from being able to verify contracts on blockscout.
2. Since we don't save the jump tables we took a performance hit for analyzing the bytecode, but none of the performance gains from storing the jump table to be used later.
___
___
- Fixed a critical bug where bytecode was being double padded, causing issues with contract verification on blockscout.
- Removed unnecessary bytecode analysis, improving performance by eliminating redundant processing.
- Updated EVM configuration to use raw bytecode analysis, ensuring proper handling of created bytecodes.
- Simplified `Bytes` to `RevmBytecode` conversion, removing the `to_analysed` step.
- These changes …
> fix: remove to_analysed being (wrongly) used

- src/eth/primitives/stratus_error.rs
- src/eth/rpc/mod.rs
- src/eth/rpc/rpc_method_wrapper.rs
- src/eth/rpc/rpc_server.rs
- src/infra/metrics/metrics_definitions.rs
Enhancement
___
- Implemented error metrics for RPC methods, specifically for transaction errors
- Added a new `rpc_method_wrapper` module with a `call_error_metrics_wrapper` function
- Applied the error metrics wrapper to `eth_call` and `eth_sendRawTransaction` methods
- Added a new counter metric `executor_transaction_error_types` to track different error types
- Enhanced `StratusError` enum with `strum::IntoStaticStr` derive for easier conversion to static strings
___
<tr>
<td>
<details>
<summary><strong>stratus_error.rs</strong><dd><code>Add IntoStaticStr derive for StratusError</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
> enha: execution error types

- Cargo.lock
- Cargo.toml
- src/eth/primitives/address.rs
- src/eth/primitives/block_number.rs
- src/eth/primitives/hash.rs
- src/eth/primitives/slot_index.rs
- src/eth/primitives/slot_value.rs
- src/eth/primitives/wei.rs
also had to bump tempfile for it to work
> chore: bump sqlx version due to security alert

- src/eth/rpc/rpc_server.rs
- src/eth/storage/inmemory/inmemory_temporary.rs
- src/eth/storage/stratus_storage.rs
- src/eth/storage/temporary_storage.rs
Enhancement
___
- Added new RPC method `stratus_pendingTransactionsCount` to retrieve the count of executed transactions waiting to enter the next block
- Refactored `pending_transactions` method in various storage-related files to return `Vec<TransactionExecution>` directly, removing the `Result` wrapper
- Simplified the implementation of `pending_transactions` in `InMemoryTemporaryStorage` using iterator methods
- Updated the `TemporaryStorage` trait to reflect the changes in the `pending_transactions` method signature
- These changes improve error handling and make the API more straightforward for retrieving pending transactions
___
<tr>
<td>
<details> …
> feat: add rpc method for pending transactions count

- src/eth/rpc/rpc_server.rs
Enhancement
___
- Improved performance by reducing RwLock retention in the `stratus_get_subscriptions` function
- Modified the approach to read subscription data sequentially instead of simultaneously
- Implemented serialization of subscription data outside of lock scope
- Added error handling for serialization using `expect_infallible()`
- Simplified the JSON response construction by using pre-serialized values
___
<tr>
<td>
<details>
<summary><strong>rpc_server.rs</strong><dd><code>Optimize RwLock usage in subscription data retrieval</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
src/eth/rpc/rpc_server.rs
<li>Imported …
> chore: decrease RwLock retention

- src/eth/rpc/rpc_server.rs
Enhancement
___
- Removed redundant deserialization of `app_config` in the `stratus_init_importer` function
- Simplified the process of extracting and parsing the importer configuration
- Removed unused import of `serde_json::Value`, which was only used in the dev feature
- Improved code efficiency and readability by directly accessing the `app_config` field
___
<tr>
<td>
<details>
<summary><strong>rpc_server.rs</strong><dd><code>Optimize RPC server configuration parsing</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
src/eth/rpc/rpc_server.rs
<li>Removed redundant …
> chore: remove redundant deserialization

- e2e/cloudwalk-contracts/integration/test/leader-follower-change.test.ts
___
- Removed redundant `stratus_changeToLeader` calls in the "Validate new Follower health after change" and "Validate new Leader health after change" test cases
- Optimized test execution time by reducing the sleep duration from 10 seconds to 5 seconds
- Improved test efficiency without compromising the validation of leader and follower health after changes
___
<tr>
<td>
<details>
<summary><strong>leader-follower-change.test.ts</strong><dd><code>Optimize leader-follower change tests</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
> fix: remove unused request

- src/eth/miner/miner_config.rs
- src/eth/rpc/rpc_client_app.rs
- src/eth/rpc/rpc_http_middleware.rs
- src/eth/rpc/rpc_parser.rs
Enhancement
___
- Removed unnecessary lock and associated error handling in miner configuration
- Simplified miner mode checking by directly using `mode.is_interval()`
- Removed `Default` implementation for `RpcClientApp` enum
- Consistently use `RpcClientApp::Unknown` instead of `default()` across multiple files
- Improved code clarity and reduced potential for errors related to default implementations
___
<tr>
<td>
<details>
<summary><strong>miner_config.rs</strong><dd><code>Simplify miner mode checking and remove lock</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr> …
> chore: remove unnecessary lock

- src/eth/rpc/rpc_server.rs
Enhancement
___
- Refactored miner mode handling in RPC server:
- Introduced `change_miner_mode` function to centralize mode changing logic
- Updated `stratus_change_to_leader` and `stratus_change_to_follower` to use the new function
- Added `LEADER_MINER_INTERVAL` constant for leader miner interval
- Improved error handling and logging for miner mode changes
- Simplified parameter parsing in `stratus_change_miner_mode` function
- Removed redundant JSON parameter creation in leader and follower change functions
___
<tr>
<td>
<details>
<summary><strong>rpc_server.rs</strong><dd><code>Refactor miner mode handling and improve RPC endpoints</code>&nbsp; …
> enha: refactor miner mode endpoint

- src/eth/primitives/stratus_error.rs
- src/eth/rpc/rpc_server.rs
Enhancement
___
- Refactored the importer initialization process in the RPC server:
- Split `stratus_init_importer` into two functions for better separation of concerns
- `stratus_init_importer` now handles parameter parsing and `ImporterConfig` creation
- New `init_importer` function focuses on the actual initialization logic
- Improved code organization and maintainability
- No changes to the overall functionality or external API
___
<tr>
<td>
<details>
<summary><strong>rpc_server.rs</strong><dd><code>Refactor importer initialization for better separation of concerns</code></dd></summary>
<hr>
src/eth/rpc/rpc_server.rs
<li>Refactored …
> enha: refactor init importer

- e2e/cloudwalk-contracts/integration/test/leader-follower-miner.test.ts
- src/eth/executor/executor.rs
- src/eth/miner/miner.rs
- src/eth/miner/miner_config.rs
- src/eth/primitives/log_filter.rs
- src/eth/rpc/rpc_server.rs
- src/eth/rpc/rpc_subscriptions.rs
- src/eth/storage/stratus_storage.rs
- src/globals.rs
Also move things from Miner to Storage.
Also, simplify interface.
Also, make some functions not fail.
___
___
- Refactored miner control from global state to Miner struct methods
- Enhanced Miner struct with new control methods (enable, disable, set_mode)
- Simplified miner mode access and change logic in RPC server
- Improved error handling in miner and storage initialization
- Removed unnecessary global state for miner control
- Updated various components to use new miner control methods
- Minor improvements in error logging and test initialization
___
<tr>
<td>
<details>
<summary><strong>executor.rs</strong><dd><code>Simplify miner …
> refac: move things from GlobalState to Miner

- src/eth/executor/executor.rs
this var is not a lock anymore, but I left the `lock` suffix in the var name
___
Enhancement
___
- Simplified the logic for acquiring the miner lock in the `Executor` implementation
- Removed the redundant `mode_lock` variable, directly using `self.miner.mode()` in the condition
- Reduced code nesting, improving readability
- This change maintains the same functionality while making the code more concise and easier to understand
___
<tr>
<td>
<details>
<summary><strong>executor.rs</strong><dd><code>Simplify miner lock acquisition logic</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
> chore: remove misleading lock var name

- src/eth/primitives/stratus_error.rs
- src/eth/rpc/rpc_server.rs
Enhancement
___
- Improved error handling in the process of changing a node from follower to leader:
- Added new `ImporterConfigNotFound` error for cases where importer configuration is missing
- Implemented parsing and error handling for current importer configuration
- Enhanced rollback mechanism:
- On failure to change miner mode, the system now reverts to the previous state
- Restarts the importer with the current configuration if errors occur during the process
- Improved logging throughout the function for better debugging and monitoring
- Overall, these changes make the follower-to-leader transition more robust and reversible
___
<tr>
<td> …
> enha: follower to leader change reversible

- src/eth/primitives/stratus_error.rs
- src/eth/rpc/rpc_server.rs
Reverts cloudwalk/stratus#1705
___
Enhancement
___
This PR reverts changes made in a previous commit (cloudwalk/stratus#1705) related to making the follower to leader change reversible. The main changes include:
- Removed `ImporterConfigNotFound` error variant from `StratusError` enum
- Simplified the `stratus_change_to_leader` function by removing:
- Importer configuration parsing and handling
- Rollback logic for miner mode changes
- Importer reinitialization in case of errors
- Streamlined error handling in the leader change process
- Removed the ability to revert changes if errors occur during the leader change process
These changes simplify the code and remove the reversibility feature, potentially making the leader change process more straightforward but less fault-tolerant.
___ …
> Revert "enha: follower to leader change reversible"

- e2e/cloudwalk-contracts/integration/test/leader-follower-change.test.ts
- e2e/cloudwalk-contracts/integration/test/leader-follower-miner.test.ts
- src/bin/importer_offline.rs
- src/eth/miner/miner.rs
- src/eth/miner/miner_config.rs
- src/eth/rpc/rpc_server.rs
- src/globals.rs
- src/main.rs
___
- Refactored the Miner struct and related components to support asynchronous shutdown and more robust interval mining:
- Implemented new methods like start_interval_mining, switch_to_external_mode, and shutdown_and_wait
- Changed is_enabled to is_paused for better clarity
- Added interval_joinset for managing interval mining tasks
- Updated MinerConfig to support async initialization
- Refactored RPC server to handle async miner mode changes
- Simplified global state management by removing INTERVAL_MINER_SHUTDOWN and renaming STRATUS_SHUTDOWN
- Fixed various bugs related to miner mode changes and shutdown processes
- Updated integration tests to reflect new miner state checks
___ …
> refac: make miner shutdown awaitable

- e2e/cloudwalk-contracts/integration/test/leader-follower-change.test.ts
- src/eth/rpc/rpc_server.rs
- utils/deploy.sh
___
- Improved the process of changing a node from leader to follower mode:
- Added a check to ensure the miner is paused before changing to follower mode
- Removed unnecessary wait delays, making the transition more efficient
- Enhanced the deploy script with additional checks and safeguards:
- Added logic to pause the miner on the leader node
- Implemented a block synchronization check between leader and follower
- Updated integration tests to reflect new behavior:
- Added a test case for changing to follower mode with miner enabled
- Modified existing test to disable miner before changing to follower
- Improved error handling and logging throughout the changes
___ …
> enha: add block sync check

- .github/workflows/e2e-leader-follower.yml
- e2e/cloudwalk-contracts/integration/test/leader-follower-change.test.ts
- justfile
- src/eth/miner/miner.rs
- utils/deploy.sh
___
- Enhanced leader-follower change integration tests with more detailed state checks and expanded test coverage
- Improved deploy script with flexible configuration options and manual confirmation steps
- Added unpause functionality when switching miner to external mode
- Updated justfile to accommodate new deploy script arguments
- Reduced wait times in integration tests for faster execution
___
<tr>
<td>
<details>
<summary><strong>miner.rs</strong><dd><code>Unpause miner when switching to external mode</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr> …
> enha: add more test coverage and script improvements

- e2e/cloudwalk-contracts/integration/test/leader-follower-change.test.ts
- src/eth/miner/miner.rs
Bug fix
___
- Fixed a bug in the miner's `switch_to_external_mode` function by explicitly setting the mode to External
- Updated integration test expectations for the leader node state
- Ensured that the interval miner is running as expected in the leader-follower change test
___
<tr>
<td>
<details>
<summary><strong>miner.rs</strong><dd><code>Set miner mode to external when switching</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
src/eth/miner/miner.rs
<li>Added <code>self.set_mode(MinerMode::External);</code> in the <br><code>switch_to_external_mode</code> …
> fix: change to external bug

- src/eth/follower/importer/importer.rs
- src/eth/rpc/rpc_server.rs
- src/globals.rs
Enhancement
___
- Implemented a semaphore system to manage importer tasks:
- Added `IMPORTER_ONLINE_TASKS_SEMAPHORE` with 3 permits
- Modified importer functions to acquire semaphore permits
- Created `wait_for_importer_to_finish` function to ensure all importer tasks are completed
- Updated `stratus_change_to_leader` to use the new wait function instead of a fixed sleep
- Removed unused imports and constants
___
<tr>
<td>
<details>
<summary><strong>importer.rs</strong><dd><code>Implement semaphore for importer tasks</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
> enha: make importer-online shutdown awaitable

- src/eth/miner/miner.rs
Bug fix
___
- Fixed a corner case in the miner shutdown check logic
- Modified the `is_interval_miner_running` method in `src/eth/miner/miner.rs`
- Now checks if the joinset is both present and not empty
- Ensures more accurate detection of running miner tasks
- Prevents false positives when the joinset exists but contains no active tasks
___
<tr>
<td>
<details>
<summary><strong>miner.rs</strong><dd><code>Improve miner shutdown check accuracy</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
src/eth/miner/miner.rs
<li>Modified the …
> fix: corner case for miner shutdown check

- src/bin/rocks_revert_to_block.rs
- src/eth/storage/permanent_storage.rs
- src/eth/storage/rocks/rocks_permanent.rs
- src/eth/storage/rocks/rocks_state.rs
Enhancement
___
- Added a new configurable option `rocks_shutdown_timeout` to control the maximum time to wait for RocksDB compaction during shutdown.
- Modified `RocksPermanentStorage` and `RocksStorageState` to accept and use the new shutdown timeout parameter.
- Updated the `Drop` implementation for `RocksStorageState` to use the configurable timeout instead of a hard-coded 4-minute value.
- Added necessary imports and adjusted function signatures across multiple files to accommodate the new timeout feature.
- Updated test cases to include the new timeout parameter (using `Duration::ZERO` for tests).
___
<tr>
<td>
<details> …
> enha: add flag for rocks shutdown timeout duration

- justfile
leak.svg is not a good filename for the result of the commands
___
Enhancement, Documentation
___
- Updated the example commands for generating memory profiling flamegraphs in the `justfile`
- Changed the output filename from `leak.svg` to `mem_prof.svg` for both differential and point-in-time flamegraphs
- Improved clarity and consistency in the documentation for memory profiling
___
<tr>
<td>
<details>
<summary><strong>justfile</strong><dd><code>Update memory profiling flamegraph commands</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
justfile
<li>Updated the example …
> chore: update justfile jeprof description

- src/infra/blockchain_client/blockchain_client.rs
I was having a look at the code base and found these quick and tiny one-line optimizations.
If binary sizes are a problem, then slices (`&[JsonValue]`) are a better choice than this.
> enha: Remove some unnecessary heap allocations in BlockchainClient

- e2e/cloudwalk-contracts/integration/test/leader-follower-change.test.ts
- src/eth/primitives/stratus_error.rs
- src/eth/rpc/rpc_server.rs
___
- Implemented concurrency control for mode change endpoints (`stratus_change_to_leader` and `stratus_change_to_follower`) using a semaphore
- Added new `ModeChangeInProgress` error to handle concurrent mode change attempts
- Created E2E test to verify the prevention of concurrent mode changes with 1000 simultaneous requests
- Ensured proper error handling and response for concurrent mode change attempts
- Removed unused imports and cleaned up code in the test file
___
<tr>
<td>
<details>
<summary><strong>stratus_error.rs</strong><dd><code>Add new error for concurrent mode changes</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
> enha: control change to mode endpoints concurrency

- src/eth/executor/executor.rs
- src/eth/primitives/log_filter_input.rs
- src/eth/storage/inmemory/inmemory_temporary.rs
- src/eth/storage/stratus_storage.rs
- src/eth/storage/temporary_storage.rs
* Renamed a few transaction execution methods.
* `read_pending_block_number` becomes `read_pending_block_header` so in a next PR we can also use it to read the pending block timestamp.
___
Enhancement, Refactoring
___
- Renamed `read_pending_block_number` to `read_pending_block_header` across multiple files to provide more comprehensive block information.
- Updated `EvmInput` creation in the executor to use `pending_header.number` instead of `pending_block_number`.
- Refactored `InMemoryTemporaryStorage` methods for consistency:
- `save_execution` -> `save_pending_execution`
- `pending_transactions` -> `read_pending_executions`
- `read_transaction` -> `read_pending_execution`
- Updated `StratusStorage` to use new method names and adjust error handling accordingly.
- Refactored …
> refactor: TempStorage methods renamed and repurposed

- src/bin/importer_offline.rs
- src/eth/follower/importer/importer.rs
- src/eth/miner/miner.rs
Pass external_block to miner via parameter instead of temporary storage. The temporary storage methods will be removed in a next PR with unnecessary clones added in this PR.
___
Enhancement
___
- Refactored the `mine_external` and `mine_external_and_commit` methods to receive the external block as a parameter instead of retrieving it from temporary storage.
- Updated the `execute_external_block` calls to clone the block before passing it, to avoid unnecessary borrowing issues.
- Removed the code that retrieves the external block from `block.external_block` in the `mine_external` method.
- These changes improve the code structure and prepare for the removal of temporary storage methods in a future PR.
- Note: Some unnecessary clones were added in this PR and will be addressed in a …
> refactor: receive external block in mine_external methods

- src/eth/executor/executor.rs
- src/eth/storage/inmemory/inmemory_temporary.rs
- src/eth/storage/stratus_storage.rs
- src/eth/storage/temporary_storage.rs
Enhancement
___
- Removed the `set_pending_external_block` function and its usage across multiple files
- Eliminated the `ExternalBlock` import where it's no longer needed
- Removed associated logging and metrics for setting pending external blocks
- Updated the `TemporaryStorage` trait to remove the `set_pending_external_block` method
- This change simplifies the codebase by removing unused functionality related to external blocks
___
<tr>
<td>
<details>
<summary><strong>executor.rs</strong><dd><code>Remove external block setting in executor</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
> refactor: remove set_pending_external_block

- src/eth/rpc/rpc_client_app.rs
- src/eth/rpc/rpc_server.rs
- src/eth/rpc/rpc_subscriptions.rs
- src/infra/metrics/metrics_definitions.rs
Enhancement
___
- Implemented client-specific metrics for RPC subscriptions, allowing for more granular tracking of subscription activity.
- Refactored subscription-related methods for consistency and improved naming conventions.
- Enhanced `RpcClientApp` enum with additional trait derivations (`Eq` and `Hash`) for better functionality.
- Introduced a new `sub_metrics` module to centralize and organize subscription metric updates.
- Updated the `rpc_subscriptions_active` gauge metric to include a `client` parameter for more detailed monitoring.
- Improved code organization and readability throughout the affected files.
___
<tr>
<td>
<details> …
> enha: add client identification to subscription metrics

- src/eth/follower/importer/importer_config.rs
- src/eth/primitives/stratus_error.rs
- src/eth/rpc/rpc_context.rs
- src/eth/rpc/rpc_server.rs
Enhancement
___
- Standardized the behavior when RwLocks are poisoned across multiple files
- Improved error handling by replacing `map_err` with `match` statements
- Implemented recovery of data from poisoned locks using `into_inner()`
- Removed redundant error variants related to lock failures
- Enhanced code consistency and robustness in handling concurrent access errors
___
<tr>
<td>
<details>
<summary><strong>importer_config.rs</strong><dd><code>Improve RwLock error handling in ImporterConfig</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
src/eth/follower/importer/importer_config.rs
<li>Modified …
> enha: standardize behavior when rwlock is poisoned

- src/eth/rpc/rpc_server.rs
This check is already done in the change_miner_mode function that is called below
___
Enhancement
___
- Removed unnecessary check for miner pause status in `stratus_change_to_follower` function
- Simplified the logic for changing to follower mode by relying on the existing checks in `change_miner_mode` function
- Improved code efficiency and reduced redundancy
- Maintains the same functionality while streamlining the process
___
<tr>
<td>
<details>
<summary><strong>rpc_server.rs</strong><dd><code>Streamline follower mode transition logic</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
> chore: remove unnecessary check

- src/eth/primitives/execution.rs
- src/eth/primitives/log.rs
- src/eth/primitives/log_filter.rs
- src/eth/primitives/log_mined.rs
- src/eth/primitives/logs_bloom.rs
Enhancement
___
- Refactored log topic retrieval methods across multiple files:
- Introduced `topics_non_empty()` method to return only non-empty topics
- Renamed existing `topics()` method to `topics_non_empty()`
- Added new `topics()` method to return all topics, including empty ones
- Updated method calls and documentation in related files to reflect these changes
- Improved consistency and clarity in handling log topics throughout the codebase
- Enhanced error messages to provide more accurate information about log topic mismatches
___
<tr>
<td>
<details>
<summary><strong>execution.rs</strong><dd><code>Update log topic comparison logic</code>&nbsp; …
> refactor: document and rename topics method

- e2e/cloudwalk-contracts/integration/test/leader-follower-change.test.ts
- e2e/cloudwalk-contracts/integration/test/leader-follower-miner.test.ts
- justfile
- src/eth/primitives/stratus_error.rs
- src/eth/rpc/rpc_server.rs
Enhancement
___
- Removed the `MinerEnabled` variant from the `StratusError` enum in `stratus_error.rs`
- Updated `change_miner_mode` function in `rpc_server.rs` to use a custom error message instead of `StratusError::MinerEnabled`
- Improved error handling by using the `log_and_err!` macro for better logging and error reporting
- Simplified the codebase by removing an unused error variant
___
<tr>
<td>
<details>
<summary><strong>stratus_error.rs</strong><dd><code>Remove MinerEnabled error variant</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
> chore: remove `MinerEnabled` variant from `StratusError`

- .github/workflows/_setup-e2e.yml
- .github/workflows/build-binary.yml
- .github/workflows/check-features.yml
- .github/workflows/comment-tag-report.yml
- .github/workflows/doc-test.yml
- .github/workflows/e2e-contracts-rocks.yml
- .github/workflows/e2e-contracts.yml
- .github/workflows/e2e-leader-follower.yml
- .github/workflows/int-test.yml
- .github/workflows/outdated.yml
- .github/workflows/unit-test.yml
- rust-toolchain.toml
running CI to see if this fixes it
___
Enhancement
___
- Upgraded the Rust toolchain version from 1.79 to 1.80 in `rust-toolchain.toml`
- This update ensures the project is using the latest stable version of Rust
- May include performance improvements, bug fixes, and new language features introduced in Rust 1.80
___
<tr>
<td>
<details>
<summary><strong>rust-toolchain.toml</strong><dd><code>Upgrade Rust toolchain version</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
rust-toolchain.toml
- …
> fix: just outdated command by bumping cargo to 1.81

- Cargo.lock
- Cargo.toml
- src/eth/rpc/rpc_middleware.rs
___
- Updated jsonrpsee dependency to version 0.24.6, which includes fixes for tracking active requests correctly.
- Removed a TODO comment in the RPC middleware related to the calculation of active connections, as the issue has been resolved in the new jsonrpsee version.
- These changes improve the accuracy of request tracking and remove outdated comments, enhancing the overall reliability of the RPC system.
___
<tr>
<td>
<details>
<summary><strong>rpc_middleware.rs</strong><dd><code>Remove TODO comment for active connections</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
> fix: update jsonrpsee to track active requests correctly

- src/eth/rpc/rpc_subscriptions.rs
Bug fix
___
- Fixed a bug in the RPC subscriptions metrics reporting
- Corrected the order of arguments in `metrics::set_rpc_subscriptions_active` function calls
- Updated all occurrences of the function call to use the correct order: (count, sub_label, client)
- This fix ensures that the RPC subscription metrics are reported correctly for different subscription types and clients
___
<tr>
<td>
<details>
<summary><strong>rpc_subscriptions.rs</strong><dd><code>Correct argument order in RPC subscription metrics</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
src/eth/rpc/rpc_subscriptions.rs
<li>Fixed the order of arguments in …
> fix: wrong label order in rpc_subscriptions_active

- e2e/cloudwalk-contracts/contracts-clone.sh
Enhancement
___
- Removed hardcoded commit hashes for all repository clones, allowing the script to always use the latest commits
- Updated the `clone_alternative` function to prioritize branch over commit, improving flexibility
- Adjusted all function calls to match the new parameter order
- This change ensures that the E2E tests always run on the most recent code, improving test coverage and relevance
___
<tr>
<td>
<details>
<summary><strong>contracts-clone.sh</strong><dd><code>Update repository cloning process to use latest commits</code>&nbsp; &nbsp; </dd></summary>
<hr>
e2e/cloudwalk-contracts/contracts-clone.sh
<li>Removed hardcoded commit hashes …
> test(contracts): always run on latest commits

- .github/workflows/lint-check.yml
- e2e/cloudwalk-contracts/_functions.sh
- e2e/cloudwalk-contracts/contracts-clone.sh
- e2e/cloudwalk-contracts/contracts-compile.sh
- e2e/cloudwalk-contracts/contracts-coverage.sh
- e2e/cloudwalk-contracts/contracts-flatten.sh
- e2e/cloudwalk-contracts/contracts-remove.sh
- e2e/cloudwalk-contracts/contracts-test.sh
- justfile
All shell scripts inside cloudwalk-contracts are now formatted and linted with `shfmt` and `shellcheck`. 
Their configurations are totally compatible with Zed's Basher extension out of the box. 
Without Zed, use `just shell-lint` locally to format and lint them if you make a change.
The check was added to CI's Lint action
___
___
- Enhanced shell script robustness and safety across multiple files by adding quotes around variables and improving error handling.
- Improved script formatting and readability, including better indentation and case statement formatting.
- Fixed various shellcheck warnings throughout the shell scripts.
- Added a new shell linting step to the CI workflow using the `just shell-lint` command.
- Introduced a new `shell-lint` recipe in the …
> ci(lint): format shell scripts and add check

- src/bin/rpc_downloader.rs
- src/eth/follower/importer/importer.rs
- src/globals.rs
___
- Improved RPC downloader shutdown mechanism:
- Implemented graceful shutdown using `GlobalState::is_shutdown_warn`
- Enhanced error handling for download tasks
- Refactored importer-related code:
- Introduced `TASKS_COUNT` constant in `Importer` struct
- Updated global variables to use the new constant
- Enhanced code organization and maintainability:
- Added `TASK_NAME` constant in RPC downloader
- Replaced hard-coded values with constants
- Minor improvements:
- Updated import statements
- Simplified stream processing in RPC downloader
___
<tr>
<td>
<details>
<summary><strong>rpc_downloader.rs</strong><dd><code>Improve RPC …
> fix: rpc downloader shutdown

- src/bin/rpc_downloader.rs
Enhancement
___
- Added a new feature to report the download speed of blocks in the RPC downloader
- Implemented an atomic counter `BLOCKS_DOWNLOADED` to track the number of downloaded blocks
- Created a new function `blocks_per_minute_reporter` that calculates and logs the download speed
- The reporter provides information on blocks per second and estimated blocks per day
- Modified the `download` function to update the atomic counter after each successful block download
- Spawned a new thread in `download_blocks` to run the speed reporter concurrently
- Removed individual block download logging to reduce noise in the output
- The speed report adjusts its interval dynamically, starting from 1 minute and increasing up to 10 minutes
___ …
> enha: rpc-downloader: report speed

- src/bin/rpc_downloader.rs
by also checking in the block fetch loop, we can stop running earlier
___
Enhancement
___
- Introduced a constant `TASK_NAME` for better task identification in the download function
- Added a shutdown check within the block fetch loop to allow for faster termination of the download process
- Enhanced error logging for block fetch failures, providing more specific information
- These changes improve the overall efficiency and responsiveness of the RPC downloader, particularly during shutdown scenarios
___
<tr>
<td>
<details>
<summary><strong>rpc_downloader.rs</strong><dd><code>Enhance RPC downloader shutdown and error handling</code>&nbsp; &nbsp; &nbsp; …
> enha: make rpc-downloader shutdown faster

- src/eth/rpc/rpc_subscriptions.rs
- src/eth/storage/rocks/rocks_state.rs
- src/ext.rs
- src/infra/tracing/tracing_services.rs
and update a couple error messages
___
___
- Optimized error logging by removing unnecessary `format!()` calls in multiple files, improving performance.
- Removed outdated comments in `RocksStorageState`, enhancing code clarity.
- Improved `MutexExt` trait in `src/ext.rs`:
- Renamed `error_message` parameter to `error_context` for better clarity.
- Updated error message to be more concise.
- Fixed inaccurate error messages in `tracing_services.rs`:
- Clarified "tx channel" and "rx channel" closure messages to specify "receiver side" and "sender side" respectively.
- Overall, these changes improve code quality, performance, and error message accuracy across multiple components.
___ …
> chore: remove outdated comments

- src/eth/storage/rocks/rocks_batch_writer.rs
- src/eth/storage/rocks/rocks_cf.rs
Enhancement
___
- Removed unused write operations (`insert`, `delete`, `batch_delete`) from the RocksDB wrapper
- Simplified `BufferedBatchWriter` by removing the `delete` method
- Eliminated `insert_impl`, `delete_impl`, `prepare_batch_deletion`, and `get_or_insert_with` methods from `RocksCf`
- Improved code maintainability by removing dead code and unused functionality
- No new features added; purely a code cleanup operation
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Code cleanup</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>rocks_batch_writer.rs</strong><dd><code>Remove unused delete operation from BufferedBatchWriter</code>&nbsp; &nbsp; </dd></summary>
<hr>
src/eth/storage/rocks/rocks_batch_writer.rs …
> chore: remove unused write operations (insert, delete, batch_delete)

- src/eth/executor/evm_input.rs
- src/eth/executor/executor.rs
___
- Improved error handling and messaging in the Ethereum executor:
- Enhanced `from_eth_call` function in `EvmInput` with better error documentation and messaging
- Refined error handling for invalid block numbers in `Executor::execute_read_only_local_transaction`
- Added explicit error return using `StratusError::RpcBlockFilterInvalid` for invalid block numbers
- Updated error messages to be more descriptive and helpful for debugging
___
<tr>
<td>
<details>
<summary><strong>evm_input.rs</strong><dd><code>Enhance error handling in EvmInput creation</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
> tweak: use correct error variant for invalid block number

- src/eth/storage/rocks/cf_versions.rs
- src/eth/storage/rocks/rocks_state.rs
it was previously using the wrong types
also add a helper function for testing
___
___
- Added `fake::Dummy` derive macro to `impl_single_version_cf_value` in `cf_versions.rs` to support generating fake data for testing.
- Introduced `new_in_testdir()` helper function in `RocksStorageState` for easier test setup.
- Fixed `test_rocks_multi_get` to use correct types (`(AddressRocksdb, SlotIndexRocksdb)` for keys and `CfAccountSlotsValue` for values).
- Refactored existing tests to use the new `new_in_testdir()` helper function, improving test consistency and reducing boilerplate.
- Enhanced test assertions and added clarifying comments in `test_rocks_multi_get`.
- Removed unnecessary imports and simplified test code.
___
<table><thead><tr><th></th><th …
> tests: fix test `test_rocks_multi_get`

- src/config.rs
Documentation, Enhancement
___
- Enhanced the documentation for the `initial_accounts` field in the `RpcDownloaderConfig` struct
- Added specific information for Cloudwalk networks:
- Provided BRLC addresses for Mainnet and Testnet
- Improved clarity for users configuring initial accounts in different network environments
___
<tr>
<td>
<details>
<summary><strong>config.rs</strong><dd><code>Add documentation for initial accounts in Cloudwalk networks</code></dd></summary>
<hr>
src/config.rs
<li>Added documentation for the <code>initial_accounts</code> field in the <br><code>RpcDownloaderConfig</code> struct<br> <li> Provided specific addresses for BRLC …
> chore: add docs for common `--initial-accounts`

- src/eth/follower/consensus.rs
- src/eth/rpc/rpc_method_wrapper.rs
- src/eth/rpc/rpc_middleware.rs
- src/eth/rpc/rpc_parser.rs
- src/eth/rpc/rpc_server.rs
- src/eth/rpc/rpc_subscriptions.rs
- src/infra/blockchain_client/blockchain_client.rs
- src/infra/metrics/metrics_definitions.rs
Enhancement
___
- Improved efficiency by changing multiple methods to accept references instead of values, reducing unnecessary cloning.
- Enhanced error metrics by including client information, allowing for better tracking and analysis of errors per client.
- Optimized client handling in RPC middleware and subscriptions, improving performance and reducing memory usage.
- Updated `RpcExtensionsExt` trait to return a reference to `RpcClientApp`, further reducing cloning operations.
- Refactored several RPC methods and blockchain client methods to align with the new reference-based approach.
- Modified metrics definitions to include client information in transaction error types.
___ …
> enha: identify clients in errors

- src/bin/rpc_downloader.rs
to help in comparing with the importer-offline reports
___
Enhancement
___
- Changed the speed reporting metric in the RPC downloader from blocks per second (bps) to blocks per minute (bpm)
- Updated the `blocks_per_minute_reporter` function to calculate and log blocks per minute instead of blocks per second
- Adjusted the calculation for blocks per day to use the new blocks per minute metric
- Modified the log output to display `blocks_per_minute` instead of `blocks_per_second`
- This change aligns the reporting with the importer-offline reports for easier comparison
___
<tr>
<td>
<details>
<summary><strong>rpc_downloader.rs</strong><dd><code>Update …
> tweak: change rpc-downloader speed reporter from bps to bpm

- src/bin/rpc_downloader.rs
Bug fix
___
- Fixed a critical bug in the `blocks_per_minute_reporter` function where the calculation of blocks per minute was incorrect.
- Changed the formula from dividing by 60.0 to multiplying by 60.0, which correctly converts the blocks per second to blocks per minute.
- This fix ensures accurate reporting of download speed in the RPC downloader.
___
<tr>
<td>
<details>
<summary><strong>rpc_downloader.rs</strong><dd><code>Correct blocks per minute calculation</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
src/bin/rpc_downloader.rs …
> fix: rpc downloader speed reporter

- src/ledger/events.rs
Enhancement
___
- Renamed 'transaction_datetime' to 'block_datetime' in the AccountTransfers struct serialization for better clarity and consistency
- Reordered fields in the AccountTransfers struct and its serialization to group related fields together
- Updated the test case JSON to reflect the new field name and order
- This change improves code readability and maintains consistency in terminology across the codebase
___
<tr>
<td>
<details>
<summary><strong>events.rs</strong><dd><code>Rename and reorder datetime field in AccountTransfers</code>&nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
src/ledger/events.rs
<li>Renamed 'transaction_datetime' field …
> fix: rename transaction_datetime to block_datetime

- src/config.rs
Documentation
___
- Updated the comment for the `initial_accounts` field in the `RpcDownloaderConfig` struct
- Removed specific mention of BRLC token for Cloudwalk networks, making the comment more generic
- The change clarifies that the provided addresses are for Cloudwalk networks in general, not specifically for BRLC token
- This update improves documentation accuracy and flexibility for different token types on Cloudwalk networks
___
<tr>
<td>
<details>
<summary><strong>config.rs</strong><dd><code>Update comment for initial accounts in RpcDownloaderConfig</code></dd></summary>
<hr>
src/config.rs
<li>Updated comment for <code>initial_accounts</code> …
> chore: update comment

- src/eth/storage/rocks/rocks_batch_writer.rs
- src/eth/storage/rocks/rocks_cf.rs
- src/eth/storage/rocks/rocks_permanent.rs
- src/eth/storage/rocks/rocks_state.rs
Enhancement
___
- Enabled synchronous writes in RocksDB by using `WriteOptions` with `sync` set to true in the `write_in_batch_for_multiple_cfs_impl` function.
- Added `#[cfg(feature = "dev")]` attribute to various methods across multiple files, limiting their availability to development builds only.
- Refactored method attributes and imports in test modules for better organization and clarity.
- Changed `#[cfg_attr(not(test), allow(dead_code))]` to `#[allow(dead_code)]` for the `multi_get` method in `rocks_cf.rs`.
- These changes improve data integrity by ensuring synchronous writes and better organize the codebase by clearly separating development-only features.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td …
> enha: enable WriteOptions.sync

- src/infra/metrics/metrics_macros.rs
Enhancement
___
- Added a new "node_mode" label to all metric types (counter, histogram, gauge) in the metrics macro implementations.
- The node mode is dynamically obtained from `GlobalState::get_node_mode()` for each metric call.
- This enhancement allows for better categorization and analysis of metrics based on the current node mode.
- The change is consistently applied across different metric macro implementations, ensuring uniform behavior.
___
<tr>
<td>
<details>
<summary><strong>metrics_macros.rs</strong><dd><code>Add node mode label to all metrics</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
> enha: add node mode to metric tags

- e2e/test/helpers/rpc.ts
Bug fix, Tests
___
- Fixed a potential race condition in the `subscribeAndGetEventWithContract` function by properly awaiting the `sendEvmMine()` call.
- This change ensures that the EVM mining operation completes before proceeding with the rest of the function execution.
- Improves the reliability of tests that depend on this helper function, especially when dealing with contract events and blockchain state changes.
___
<tr>
<td>
<details>
<summary><strong>rpc.ts</strong><dd><code>Fix asynchronous behavior in EVM mining</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
> tests: fix: await sendEvmMine

- .github/workflows/e2e-leader-follower.yml
- e2e/cloudwalk-contracts/integration/package-lock.json
- e2e/cloudwalk-contracts/integration/package.json
- e2e/cloudwalk-contracts/integration/test/leader-follower-kafka.test.ts
- justfile
___
- Simplified the Kafka integration test structure in `leader-follower-kafka.test.ts`:
- Removed detailed state checks for leader and follower nodes
- Eliminated follower-specific provider updates
- Removed transaction forwarding test from follower to leader
- Enhanced E2E workflow in `.github/workflows/e2e-leader-follower.yml`:
- Added 'kafka' to the test matrix
- Included steps to install Docker Compose for the Kafka test
- Added KafkaJS dependency (version 2.2.4) to the project:
- Updated both `package.json` and `package-lock.json`
- These changes prepare the project for Kafka-based end-to-end testing, improving the test coverage and infrastructure for leader-follower communication.
___
PRDescriptionHeader.CHANGES_WALKTHROUGH
<table><thead><tr><th></th><th …
> enha: activate kafka e2e

- src/eth/rpc/rpc_parser.rs
- src/eth/rpc/rpc_server.rs
- src/infra/tracing/mod.rs
- src/infra/tracing/tracing_entered_wrap.rs
___
- Fixed a bug in `eth_subscribe` where spans were held across await points, potentially causing issues with tracing
- Introduced `EnteredWrap`, a new type that wraps `tracing::span::Entered` and is not `Send`, preventing spans from being sent to another thread
- Modified `RpcExtensionsExt` trait and its implementation to use `EnteredWrap`
- Improved span handling in `eth_subscribe` by introducing a `clear_spans` function to properly drop spans before await points
- Updated the tracing module to include and export the new `EnteredWrap` type
___
<tr>
<td>
<details>
<summary><strong>rpc_parser.rs</strong><dd><code>Modify middleware …
> fix: span across yield point in `eth_subscribe`

- src/eth/executor/executor.rs
- src/eth/rpc/rpc_method_wrapper.rs
- src/eth/rpc/rpc_middleware.rs
- src/eth/rpc/rpc_server.rs
- src/eth/storage/rocks/rocks_state.rs
now all sync eth methods used in production report errors to the same metric
___
Enhancement
___
- Refactored the metrics wrapper in `rpc_method_wrapper.rs`:
- Renamed `call_error_metrics_wrapper` to `metrics_wrapper` for clarity
- Introduced `metrify_stratus_error` function to centralize error handling logic
- Simplified the wrapper implementation
- Updated `rpc_server.rs` to use the new `metrics_wrapper`:
- Applied `metrics_wrapper` to all relevant RPC methods
- Modified function signatures to use `&Extensions` instead of `Extensions`
- Removed unnecessary `Arc` wrapping for `RpcContext` in some function calls
- These changes improve code consistency, error handling, and metrics collection across all Ethereum RPC methods
___
PRDescriptionHeader.CHANGES_WALKTHROUGH …
> enha: metrify errors for all eth methods

- src/eth/rpc/rpc_method_wrapper.rs
- src/eth/rpc/rpc_server.rs
- src/infra/metrics/metrics_definitions.rs
also rename metric from `executor_transaction_error_types` to `rpc_error_response`
___
Enhancement
___
- Added method name to RPC error metrics for better error tracking and analysis
- Refactored RPC method registration process to include method name in metrics wrapper
- Renamed `executor_transaction_error_types` metric to `rpc_error_response`
- Updated `rpc_error_response` metric to include `method` label alongside `error_type` and `client`
- Introduced a new helper function `register_blocking_method` to streamline method registration with metrics wrapper
- Updated all relevant RPC method registrations to use the new helper function
___
PRDescriptionHeader.CHANGES_WALKTHROUGH
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</st …
> enha: add method name to the rpc errors metric

- src/eth/follower/importer/importer.rs
- src/infra/kafka/kafka.rs
Enhancement
___
- Added a new `queue_event` function in the `KafkaConnector` to allow for batched event sending
- Modified `send_event` to use the new `queue_event` function, improving efficiency
- Enhanced error logging in the importer, now including transaction hash for failed Kafka event sending
- Improved error handling and logging for Kafka event publishing process
- These changes allow for more efficient event handling and better debugging capabilities
___
<tr>
<td>
<details>
<summary><strong>importer.rs</strong><dd><code>Enhanced error logging for Kafka event sending</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
> enha: add function to queue events to allow for sending in batches

- Cargo.lock
- Cargo.toml
- src/infra/kafka/kafka.rs
Enhancement
___
- Implemented a new `send_buffered` function in the `KafkaConnector` struct to allow sending multiple events efficiently
- The `send_buffered` function takes a vector of events and a buffer size, returning a `Stream` of delivery results
- Modified the `send_event` function for improved error handling and readability
- Added necessary imports from `futures` and `rdkafka` crates to support the new functionality
- Included `futures-channel` dependency in Cargo.toml to enable the use of `futures_channel::oneshot::Canceled`
___
<tr>
<td>
<details>
<summary><strong>kafka.rs</strong><dd><code>Implement buffered event sending for …
> feat: send_buffered function to send events

- e2e/cloudwalk-contracts/integration/test/leader-follower-kafka.test.ts
- src/ledger/events.rs
Enhancement
___
- Refactored the `amount` field in `AccountTransfer` struct to use `U256` instead of `Decimal`
- Removed `rust_decimal` dependency and `TOKEN_SCALE` constant, simplifying the codebase
- Updated serialization logic to directly convert `U256` to string, preserving full precision
- Modified test cases to use the new `U256` representation for amounts
- Improved documentation to reflect the changes in amount format and range
___
<tr>
<td>
<details>
<summary><strong>events.rs</strong><dd><code>Refactor amount representation to use U256</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
> enha: publish amount as U256

- src/eth/follower/importer/importer_config.rs
Bug fix
___
- Fixed a syntax error in the `ImporterConfig` struct's `#[group]` attribute.
- Changed `#[group(requires_all = ["external_rpc, follower"])]` to `#[group(requires_all = ["external_rpc", "follower"])]`.
- This correction ensures that the `external_rpc` and `follower` fields are properly recognized as separate required fields.
___
<tr>
<td>
<details>
<summary><strong>importer_config.rs</strong><dd><code>Fix syntax in ImporterConfig group attribute</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
src/eth/follower/importer/importer_config.rs
<li>Fixed a syntax error in the …
> fix: importer config requirements

- e2e/cloudwalk-contracts/integration/test/leader-follower-change.test.ts
- e2e/cloudwalk-contracts/integration/test/leader-follower-miner.test.ts
- src/eth/primitives/stratus_error.rs
Enhancement
___
- Enhanced the error message for `RpcTransactionEnabled` in `stratus_error.rs` to be more descriptive and specific
- Updated corresponding test files to expect the new error message:
- `leader-follower-change.test.ts`: Updated two test cases
- `leader-follower-miner.test.ts`: Updated two test cases
- The new error message provides clearer information about why the operation cannot be performed
___
<tr>
<td>
<details>
<summary><strong>stratus_error.rs</strong><dd><code>Update RpcTransactionEnabled error message</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr> …
> chore: make error message descriptive

- src/eth/primitives/stratus_error.rs
- src/eth/rpc/rpc_server.rs
Enhancement
___
- Removed unused `MinerModeConflict` and `MinerModeChangeUnsupported` error variants from `StratusError` enum in `stratus_error.rs`
- Refactored error handling for unsupported miner mode (automine) in `rpc_server.rs`:
- Replaced `StratusError::MinerModeChangeUnsupported` with a custom error message using `log_and_err!` macro
- These changes simplify the error handling and remove unnecessary code, improving maintainability
___
<tr>
<td>
<details>
<summary><strong>stratus_error.rs</strong><dd><code>Remove unused StratusError variants</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
> refac: remove unused or unnecessary StratusError variants

- src/eth/rpc/mod.rs
- src/eth/rpc/rpc_method_wrapper.rs
- src/eth/rpc/rpc_server.rs
Enhancement
___
- Centralized the `reject_unknown_client` check in the `metrics_wrapper` function, removing redundant checks from individual RPC methods.
- Improved span handling in the `eth_subscribe` function for better performance and clarity.
- Updated imports and function visibility for better code organization.
- This refactoring simplifies the code, reduces duplication, and improves maintainability without changing the overall functionality.
___
<tr>
<td>
<details>
<summary><strong>mod.rs</strong><dd><code>Add import for reject_unknown_client</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
> refac: simplify unknown client rejection

- src/eth/storage/rocks/rocks_batch_writer.rs
- src/eth/storage/rocks/rocks_state.rs
Enhancement
___
- Added debug logging to improve visibility into RocksDB operations:
- New log message before writing a batch in `rocks_batch_writer.rs`
- Detailed logging in `save_accounts` function in `rocks_state.rs`
- Enhanced traceability for account batch insertions:
- Separate logs for accounts CF batch and accounts history batch
- Improved debugging capabilities for RocksDB-related operations
___
<tr>
<td>
<details>
<summary><strong>rocks_batch_writer.rs</strong><dd><code>Add debug logging for batch writing</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
> chore: add debug logs to save_accounts

- src/bin/historic_events_processor.rs
- src/eth/storage/rocks/types/unix_time.rs
Enhancement
___
- Replaced Kafka event streaming with file-based event storage
- Implemented daily event batching and file saving
- Added progress bars for better visibility of processing status
- Refactored code for improved readability and maintainability
- Removed Kafka-related configurations and dependencies
- Made `UnixTimeRocksdb` field public for easier access
___
<tr>
<td>
<details>
<summary><strong>historic_events_processor.rs</strong><dd><code>Refactor historic events processor to save events to files</code></dd></summary>
<hr>
src/bin/historic_events_processor.rs
<li>Removed Kafka-related code and configurations<br> <li> Added functionality to …
> enha: save historic events to files instead of sending them to kafka

- src/eth/primitives/stratus_error.rs
Enhancement
___
- Added a TODO comment in the `StratusError` enum to indicate the need for splitting the `TransactionEvmFailed` error into multiple errors.
- This change suggests a future improvement in error handling granularity for EVM transaction failures.
- The modification is minor but important for tracking future enhancements in the codebase.
___
<tr>
<td>
<details>
<summary><strong>stratus_error.rs</strong><dd><code>Add TODO for refining TransactionEvmFailed error</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
src/eth/primitives/stratus_error.rs
<li>Added a TODO comment to split …
> chore: add todo

- src/bin/historic_events_processor.rs
Enhancement
___
- Enhanced the formatting of date and time components in file paths and names
- Added leading zeros to months, days, and hours that have only one digit
- Ensures consistent file naming and folder structure for better organization and sorting
- Affects the `historic_events_processor.rs` file in the `src/bin` directory
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Formatting</strong></td><td><table>
<tr>
<td>
<details>
<summary><strong>historic_events_processor.rs</strong><dd><code>Add leading zeros to date and time components</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
src/bin/historic_events_processor.rs
<li>Modified the folder path formatting to …
> chore: add 0 to left of months, days and hours with only 1 digit

- src/config.rs
- src/eth/executor/executor_config.rs
- src/eth/rpc/rpc_config.rs
- src/eth/storage/temporary_storage.rs
vars updated: `ASYNC_THREADS, BLOCKING_THREADS, EXECUTOR_EVMS, MAX_CONNECTIONS, MAX_SUBSCRIPTIONS, TEMP_STORAGE`
___
Enhancement
___
This PR updates default values for several environment variables to optimize performance and resource allocation:
- Increased thread counts:
- `ASYNC_THREADS`: 10 -> 32
- `BLOCKING_THREADS`: 10 -> 512
- Set default `EXECUTOR_EVMS` to 30
- Increased RPC server limits:
- `MAX_CONNECTIONS`: 200 -> 400
- `MAX_SUBSCRIPTIONS`: 15 -> 30
- Set default `TEMP_STORAGE` to "inmemory"
These changes aim to improve the application's performance and resource utilization out of the box, while still allowing for custom configuration through environment variables.
___ …
> chore: update default env var values

- src/bin/importer_offline.rs
- src/config.rs
- src/eth/executor/executor.rs
- src/eth/follower/importer/importer.rs
- src/eth/follower/importer/importer_config.rs
- src/eth/miner/miner_config.rs
- src/eth/primitives/stratus_error.rs
- src/eth/rpc/rpc_server.rs
- src/globals.rs
The fake leader imports blocks like a follower, but executes the blocks's txs locally like it's a leader, mining at its own pace.
review pr by commit.
___
Enhancement
___
- Implemented a new "Fake Leader" mode, which imports blocks like a follower but executes transactions locally like a leader
- Added `--fake-leader` flag to the configuration options
- Modified the importer, executor, and miner components to support the new Fake Leader mode
- Updated global state management to use a `NodeMode` enum instead of a boolean flag for leader/follower status
- Refactored various parts of the codebase to accommodate the new mode, including RPC server and configuration handlers
- Improved error handling and logging related to node modes
- Updated health checks and transaction processing to …
> feat: implement fake leader

- src/config.rs
Bug fix
___
- Fixed a bug in the StratusConfig struct's argument conflicts configuration
- Changed 'fake-leader' to 'fake_leader' in the conflicts_with_all lists for both 'leader' and 'follower' arguments
- This ensures proper conflict handling between leader, follower, and fake leader modes
- Improves consistency in naming conventions for command-line arguments
___
<tr>
<td>
<details>
<summary><strong>config.rs</strong><dd><code>Fix argument conflicts in StratusConfig</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
src/config.rs
<li>Fixed …
> fix: conflicts_with_all fake_leader

- justfile
- justfile_helpers
Enhancement
___
- Improved build process by allowing specification of binary and features in the `build` recipe
- Added explicit `just build` step to various e2e test recipes to ensure up-to-date binary
- Refactored `stratus-test-coverage` recipe to use LLVM coverage environment variables
- Removed `CARGO_COMMAND` variable from test commands, simplifying the process
- Reduced Stratus startup wait time from 1500 to 300 seconds for faster test execution
- Updated various recipes to use the new build process, ensuring consistency across tests
___
<tr>
<td>
<details>
<summary><strong>justfile</strong><dd><code>Enhance build process and test coverage …
> enha: change how llvm-cov runs so that we can build before running

- justfile
Enhancement
___
- Reduced disk usage during test coverage by removing log files and directories after each test run
- Set `RUST_LOG=error` to minimize log output
- Cleaned up unnecessary whitespace in the justfile
- These changes aim to optimize the GitHub runner's performance by reducing disk usage
___
<tr>
<td>
<details>
<summary><strong>justfile</strong><dd><code>Optimize test coverage process and reduce disk usage</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
justfile
<li>Added <code>export RUST_LOG=error</code> to reduce log output<br> <li> Added commands to remove log files and directories after each test<br> <li> Removed unnecessary …
> enha: reduce coverage disk usage (attempt to make github runner work)

- src/eth/follower/importer/importer.rs
Enhancement
___
- Improved logging in the `Importer` implementation:
- Added the block number to the log message when an external block is successfully mined
- This enhancement provides more detailed information during the mining process, making it easier to track and debug block imports
___
<tr>
<td>
<details>
<summary><strong>importer.rs</strong><dd><code>Enhance logging for mined external blocks</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
src/eth/follower/importer/importer.rs
- Added block number logging when mining an external block
</details>
</td>
<td><a …
> enha: log miner block number after importing

- justfile
___
- Added a build step to the E2E clock test for Stratus
- Ensures that the latest version of Stratus is built before running the test
- Improves test reliability by using the most up-to-date build
- Aligns with best practices for running E2E tests
___
<tr>
<td>
<details>
<summary><strong>justfile</strong><dd><code>Add build step to E2E clock test</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
justfile
<li>Added a <code>just build</code> command before starting Stratus in the …
> tests: fix: add build step to e2e clock test

- src/eth/follower/importer/importer.rs
- src/infra/metrics/metrics_definitions.rs
Enhancement
___
- Implemented a new metric to measure the time taken for Kafka event creation
- Added conditional compilation for metrics feature in the importer
- Updated metrics definitions to include the new `kafka_create_events` histogram
- Enhances observability of the Kafka event creation process
___
<tr>
<td>
<details>
<summary><strong>importer.rs</strong><dd><code>Add metrics for Kafka event creation time</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
src/eth/follower/importer/importer.rs
<li>Added metrics for event creation time measurement<br> <li> …
> enha: add metric for event creation

- src/eth/follower/importer/importer.rs
- src/infra/kafka/kafka.rs
- src/infra/metrics/metrics_definitions.rs
Enhancement
___
- Optimized transaction event processing in the Importer:
- Replaced individual transaction processing with a single operation using `flat_map`
- Increased buffer size from 30 to 50 for improved performance
- Enhanced Kafka connector flexibility:
- Modified `create_buffer` and `send_buffered` methods to accept generic `IntoIterator`
- Updated method signatures for better type flexibility
- These changes aim to improve performance and efficiency when sending events to Kafka
___
<tr>
<td>
<details>
<summary><strong>importer.rs</strong><dd><code>Optimize transaction event processing</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
> enha: send all events at once

- src/infra/kafka/kafka.rs
Enhancement
___
- Added Kafka producer configuration for `linger.ms` (100ms) and `batch.size` (1MB) to optimize performance:
- `linger.ms`: Introduces a small delay in sending messages, allowing for more batching and potentially reducing the number of requests
- `batch.size`: Sets the maximum size of a request in bytes, helping to accumulate more messages in a single batch
- Refactored Kafka client configuration to reduce code duplication:
- Created a base `client_config` with common settings
- Modified security protocol-specific configurations to build upon the base config
- Maintained existing security protocol configurations (None, SASL_SSL, SSL) while incorporating the new performance settings
___ …
> enha: add config for linger.ms and batch.size

- src/infra/kafka/kafka.rs
Enhancement
___
- Modified the Kafka client configuration in `src/infra/kafka/kafka.rs`:
- Reduced the `linger.ms` setting from 100 to 5 milliseconds.
- This change aims to decrease the delay before sending messages, potentially improving real-time performance at the cost of slightly increased network usage.
- The adjustment may impact message batching and overall throughput, favoring lower latency over larger batch sizes.
___
<tr>
<td>
<details>
<summary><strong>kafka.rs</strong><dd><code>Adjust Kafka linger.ms setting</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
> chore: kafka: adjust linger.ms

- e2e/cloudwalk-contracts/contracts-clone.sh
- e2e/cloudwalk-contracts/contracts-compile.sh
- e2e/cloudwalk-contracts/contracts-coverage.sh
- e2e/cloudwalk-contracts/contracts-flatten.sh
- e2e/cloudwalk-contracts/contracts-remove.sh
- e2e/cloudwalk-contracts/contracts-test.sh
Enhancement
___
This PR adds support for an isolated Balance Tracker repository in various e2e scripts:
- Clone script: Added cloning of `brlc-balance-tracker` and improved error handling for npm install
- Compile script: Added fallback compilation for BalanceTracker from different repositories
- Coverage script: Included `brlc-balance-tracker` in coverage calculation
- Flatten script: Updated to support BalanceTracker in new repository
- Remove script: Added removal of `brlc-balance-tracker` repository
- Test script: Adapted to support BalanceTracker in new repository
These changes ensure smooth transition and compatibility with the isolated Balance Tracker repository while maintaining support for the existing structure.
___ …
> ci: add support for isolated balance tracker repository in e2e scripts

- src/bin/importer_offline.rs
- src/bin/rpc_downloader.rs
- src/eth/executor/evm.rs
- src/eth/executor/executor.rs
- src/eth/miner/miner.rs
- src/eth/primitives/block.rs
- src/eth/primitives/block_number.rs
- src/eth/primitives/external_receipts.rs
- src/eth/primitives/log_filter.rs
- src/eth/primitives/log_filter_input.rs
- src/eth/primitives/log_mined.rs
- src/eth/primitives/transaction_execution.rs
- src/eth/rpc/rpc_server.rs
- src/eth/storage/inmemory/inmemory_history.rs
- src/eth/storage/inmemory/inmemory_permanent.rs
- src/eth/storage/inmemory/inmemory_temporary.rs
- src/eth/storage/permanent_storage.rs
- src/eth/storage/redis/redis_permanent.rs
- src/eth/storage/rocks/rocks_permanent.rs
- src/eth/storage/rocks/rocks_state.rs
- src/eth/storage/rocks/types/account.rs
- src/eth/storage/storage_point_in_time.rs
- src/eth/storage/stratus_storage.rs
- src/eth/storage/temporary_storage.rs
- src/infra/blockchain_client/blockchain_client.rs
Enhancement
___
- Removed unnecessary references for Copy types across multiple files in the project.
- Updated method signatures, function calls, and comparisons to use values instead of references for types like Address, Hash, BlockNumber, and StoragePointInTime.
- Modified data structures to store and return values instead of references where appropriate.
- Adjusted iterator and collection operations to work with values rather than references.
- These changes should improve performance by reducing indirection and potentially allowing for better optimizations by the compiler.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><details><summary>15 files</summary><table>
<tr>
<td>
<details> …
> refac: don't use references with `Copy` types

- src/eth/storage/rocks/rocks_state.rs
___
This PR includes several enhancements and bug fixes across multiple files in the project:
- Removed unnecessary references in method calls throughout the codebase, improving performance and readability.
- Changed several methods to take arguments by value instead of by reference, which can lead to more efficient code in some cases.
- Modified some data structures to use owned values instead of references, potentially reducing memory usage and improving cache locality.
- Fixed a bug in the log filter where a reference was missing in a contains method call.
- Updated method signatures in storage-related modules to be more consistent with the changes made elsewhere.
These changes should result in cleaner, more idiomatic Rust code and may lead to minor performance …
> test: fix multiget test again

- e2e/cloudwalk-contracts/contracts-remove.sh
enhancement
___
- Removed hardcoded commit hashes from the `remove` function calls in the `contracts-remove.sh` script.
- Simplified the script to make it more maintainable and less dependent on specific commit references.
___
<tr>
<td>
<details>
<summary><strong>contracts-remove.sh</strong><dd><code>Remove commit hashes from repository removal script</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
e2e/cloudwalk-contracts/contracts-remove.sh
<li>Removed commit hashes from <code>remove</code> function calls.<br> <li> Simplified the script by eliminating hardcoded commit references.<br>
</details>
</td>
<td><a …
> style(e2e): remove commit hashes from contracts-remove.sh

- src/bin/importer_offline.rs
- src/eth/executor/evm.rs
- src/eth/executor/executor.rs
- src/eth/follower/importer/importer.rs
- src/eth/miner/miner.rs
- src/eth/primitives/log_filter.rs
- src/eth/primitives/log_filter_input.rs
- src/eth/rpc/rpc_server.rs
- src/eth/storage/mod.rs
- src/eth/storage/stratus_storage.rs
Enhancement
___
- Introduced a new `Storage` trait in `src/eth/storage/mod.rs` to define a common interface for storage operations.
- Implemented the `Storage` trait for `StratusStorage` in `src/eth/storage/stratus_storage.rs`.
- Added imports for the new `Storage` trait in multiple files across the project.
- Moved `StratusStorageConfig` from `stratus_storage.rs` to `mod.rs`.
- Updated test code in `log_filter.rs` to use `StratusStorage::new_test()` instead of creating separate in-memory storages.
- Removed unnecessary imports and adjusted method visibility in `stratus_storage.rs`.
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><details><summary>10 files</summary><table>
<tr>
<td>
<details> …
> refac: put `StratusStorage` behind a trait

- src/eth/storage/temporary/mod.rs
Enhancement
___
- Improved error handling for unknown temporary storage kinds by providing a more informative error message that includes valid options.
- Enhanced the `TemporaryStorageKind` enum with `strum` derive macros (`Display`, `VariantNames`) for better variant handling and string conversion.
- Added `Copy` and `Parser` trait implementations to `TemporaryStorageKind` for improved usability.
- Introduced the `strum` crate dependency to leverage its functionality for enum operations.
___
<tr>
<td>
<details>
<summary><strong>mod.rs</strong><dd><code>Enhance TemporaryStorageKind enum and improve error handling</code></dd></summary>
<hr> …
> chore: improve error message when tempStorage kind doesn't match

- src/config.rs
- src/eth/storage/mod.rs
Enhancement
___
- Introduced a new `StorageKind` enum to allow for future extensibility of storage types
- Renamed `StratusStorageConfig` to `StorageConfig` for clarity and consistency
- Added `storage_kind` field to `StorageConfig` with a default value of "stratus-storage"
- Implemented `FromStr` for `StorageKind` to allow parsing from string representations
- Updated the `init` method to check the `storage_kind` before initializing storage
- Modified error messages to use `Self::VARIANTS` for better maintainability
- Updated import statements and usage of the renamed `StorageConfig` in `src/config.rs`
___
<tr>
<td>
<details> …
> chore: create storage kind

- src/eth/executor/executor.rs
- src/eth/primitives/execution_conflict.rs
- src/eth/primitives/log_filter_input.rs
- src/eth/storage/mod.rs
- src/eth/storage/stratus_storage.rs
- src/eth/storage/temporary/inmemory.rs
- src/eth/storage/temporary/mod.rs
Enhancement
___
- Made pending block header a required field in storage, removing the Option wrapper
- Simplified the storage interface by removing methods related to setting pending block number
- Updated executor and other components to work with non-optional pending block header
- Refactored InMemoryTemporaryStorage to always have a pending block
- Removed unnecessary ExecutionConflict variants
- Updated TemporaryStorage trait and its implementation to reflect these changes
- Modified storage initialization to use mined block number for setting initial pending block
___
<tr>
<td>
<details>
<summary><strong>executor.rs</strong><dd><code>Simplify pending …
> enha: make pending block header required

- .github/workflows/e2e-test.yml
- e2e/contracts/TestEvmInput.sol
- e2e/test/helpers/rpc.ts
- e2e/test/interval/evm-input.test.ts
- justfile
- src/eth/executor/evm_input.rs
- src/eth/executor/executor.rs
- src/eth/primitives/point_in_time.rs
- src/eth/primitives/stratus_error.rs
- src/eth/primitives/transaction_execution.rs
- src/eth/storage/temporary/inmemory.rs
Enhancement
___
- Removed mutex that prevents transactions from executing while a block is being committed
- Implemented EVM input validation to ensure transaction input matches block header
- Added new error type `TransactionEvmInputMismatch` for handling mismatched EVM inputs
- Updated `LocalTransactionExecution` to include `evm_input` field
- Added new test contract `TestEvmInput` and corresponding E2E tests for EVM input validation
- Modified CI workflow to include interval-based Stratus testing
- Updated `justfile` to support interval-based block mode in E2E tests
- Added derive macros to `EvmInput` and `PointInTime` structs for improved serialization and testing support
___ …
> enha: remove mutex that keeps transactions from executing while a block is being commited

- Cargo.toml
Enhancement
___
- Pinned versions for three Rust crates in Cargo.toml:
- `rdkafka`: From `0.36.2` to `=0.36.2`
- `openssl`: From `0.10.32` to `=0.10.32`
- `sasl2-sys`: From `0.1.22` to `=0.1.22`
- This change ensures consistent builds by locking these dependencies to specific versions
- Helps prevent potential issues from unexpected updates in dependencies
___
<tr>
<td>
<details>
<summary><strong>Cargo.toml</strong><dd><code>Pin versions for Rust dependencies</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
Cargo.toml …
> chore: pin crate versions

- Cargo.lock
- src/bin/importer_offline.rs
Enhancement, Documentation
___
- Updated the comment for `CACHE_SIZE` and `MAX_BLOCKS_NOT_SAVED` constants in `src/bin/importer_offline.rs`
- Clarified that the cache size must be large enough to hold slots and accounts for the specified number of blocks
- Improved documentation to better explain the relationship between cache size and block processing
___
<tr>
<td>
<details>
<summary><strong>importer_offline.rs</strong><dd><code>Improve documentation for cache size constants</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
src/bin/importer_offline.rs
<li>Updated comment for <code>CACHE_SIZE</code> …
> chore: fix Cargo.lock

- Cargo.lock
- Cargo.toml
- src/eth/storage/cache.rs
Enhancement
___
- Replaced `LruCache` with `quick_cache::sync::Cache` for improved performance in storage caching
- Removed `Mutex` locks, simplifying the code and potentially reducing contention
- Eliminated `SmallVec` usage, streamlining batch operations
- Updated dependencies: removed `lru`, added `quick_cache`
- Simplified cache operations (insert, get, clear) for better readability and maintenance
- Potential performance improvements due to the use of a more efficient caching library
___
<tr>
<td>
<details>
<summary><strong>cache.rs</strong><dd><code>Optimize storage cache implementation</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
> enha: use faster library for storage cache

- src/eth/follower/importer/importer.rs
- src/infra/blockchain_client/blockchain_client.rs
which fetches blocks and receipts in a single call, while we are just testing this endpoint, the code will fallback to the previous endpoint if it fails
___
Enhancement
___
- Implemented a new endpoint `stratus_getBlockAndReceipts` for fetching blocks and receipts in a single call
- Added fallback mechanism to use the previous endpoint if the new one fails
- Improved error handling and logging for better debugging
- Updated `BlockchainClient` to support the new endpoint
- Optimized import process by reducing the number of API calls
___
<tr>
<td>
<details>
<summary><strong>importer.rs</strong><dd><code>Implement new endpoint for fetching blocks and …
> enha: update importer-online to use faster endpoint for fetching

- e2e/cloudwalk-contracts/integration/test/leader-follower-change.test.ts
___
- Added new test cases to validate the `stratus_version` API response for both Leader and Follower nodes
- Implemented checks to ensure the git commit hash is present and has the correct format (string of length 7)
- Updated existing test case titles to reflect the addition of version validation
- Enhanced the overall test coverage for the Leader-Follower integration tests
___
<tr>
<td>
<details>
<summary><strong>leader-follower-change.test.ts</strong><dd><code>Add version validation to Leader-Follower integration tests</code></dd></summary>
<hr>
e2e/cloudwalk-contracts/integration/test/leader-follower-change.test.ts
<li>Added …
> enha: add stratus_version commit sha test case

- src/eth/storage/temporary/inmemory.rs
With the introduction of the storage cache #1887 we made it so the inmemory temporary storage only held one block in its block Vec. However this combined with #1888 introduces a possibly critical bug. When the pending block is evicted from the temporary storage it takes a few ms to be committed to the permanent storage, however executions can still happen in the interim and if an execution tries to read a slot/account that has not yet been committed to the permanent but has already been evicted from the temporary it would get the wrong value.
The cache implementation masks this bug pretty well, since all the recent changes will probably be in the cache, however it is not guaranteed that it won't evict some slot/account before we have committed the block to the permanent storage, and …
> enha + fix: possible storage bug and remove states vec from inmemory temporary storage

- src/eth/executor/executor.rs
- src/eth/miner/miner.rs
- src/eth/rpc/rpc_context.rs
- src/eth/storage/permanent/inmemory.rs
- src/eth/storage/permanent/rocks/rocks_state.rs
- src/eth/storage/temporary/inmemory.rs
- src/ext.rs
- src/globals.rs
Parking lot mutexes are faster AND RwLock is fairer. However they don't have a poison detection mechanism. Maybe we should keep the std::sync mutexes in places like the executor or the miner if poisoning is actually concern.
Enhancement
___
- Replaced `std::sync::Mutex` with `parking_lot::Mutex` across multiple files for improved performance
- Removed custom `MutexExt` trait and its usage, simplifying the codebase
- Updated mutex locking syntax to use the new `parking_lot::Mutex` methods
- Kept `MutexResultExt` trait, although its usage was removed in the shown changes
- This change affects core components like the executor, miner, storage, and global state management
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong> …
> enha: use parking_lot mutex instead of std::sync

- src/bin/importer_offline.rs
- src/eth/follower/importer/importer.rs
when importing block from another node, and when importing-offline a block from postgres
___
Enhancement
___
- Enhanced the block import process by adding transaction index validation:
- Implemented sorting of transactions and receipts by transaction_index in both offline importer and regular importer
- Added checks to ensure consecutive transaction indices in blocks and receipts
- Introduced error logging for non-consecutive transaction indices in the regular importer
- These changes improve data integrity and help detect potential issues during the block import process
- The modifications affect both the offline importer (importer_offline.rs) and the regular importer (importer.rs)
___ …
> enha: check transaction index when importing block

- src/eth/executor/evm_input.rs
- src/eth/storage/temporary/inmemory.rs
Enhancement
___
- Implemented `PartialEq` trait for `EvmInput` struct in `evm_input.rs`, enabling efficient comparison with transaction input and block header.
- Optimized `save_pending_execution` method in `inmemory.rs`:
- Replaced write lock with upgradable read lock for better concurrency.
- Utilized new `PartialEq` implementation for simplified conflict checking.
- Upgraded to write lock only when necessary, reducing lock contention.
- These changes aim to improve performance and reduce overhead in the transaction execution process.
___
<tr>
<td>
<details>
<summary><strong>evm_input.rs</strong><dd><code>Add PartialEq implementation for …
> enha: make save_pending_execution cheaper

- src/eth/storage/temporary/inmemory.rs
Enhancement
___
- Improved performance of `finish_pending_block` method by reducing the time write locks are held
- Reordered operations to minimize lock contention:
- Write operations are now performed first, then locks are dropped
- Read operations and block cloning are done after releasing write locks
- Added error handling for accessing the latest block after finishing the pending block
- Simplified code by removing redundant assignments and leveraging existing variables
- Maintained conditional compilation for dev features
___
<tr>
<td>
<details>
<summary><strong>inmemory.rs</strong><dd><code>Optimize lock usage in finish_pending_block …
> enha: make finish_pending_block hold write locks for less time

- src/eth/storage/stratus_storage.rs
Enhancement
___
- Introduced a new label constant `CACHE` for better categorization of cache-related operations
- Implemented metrics for cache slot reads using the `timed` function to measure performance
- Added metrics increment for storage read slot operations, specifically for cache reads
- Enhanced the `read_slot` function to provide more detailed performance insights
- Improved observability of the cache system in the Stratus storage implementation
___
<tr>
<td>
<details>
<summary><strong>stratus_storage.rs</strong><dd><code>Add metrics for cache slot reads</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
> metrics: metrify cache slot reads

- src/eth/storage/stratus_storage.rs
Enhancement
___
- Implemented metrics for cache account reads in the `read_account` function
- Added timing measurement for the `cache.get_account` operation
- Introduced debug logging when an account is found in the cache
- These changes improve observability and performance tracking for cache operations
___
<tr>
<td>
<details>
<summary><strong>stratus_storage.rs</strong><dd><code>Enhance cache read account with metrics and logging</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
src/eth/storage/stratus_storage.rs
<li>Added metrics for cache account reads<br> <li> Implemented timing for cache get_account operation<br> <li> Added debug …
> metrics: metrify cache account reads

- e2e/cloudwalk-contracts/integration/package-lock.json
- e2e/cloudwalk-contracts/integration/package.json
- justfile
___
- Fixed an issue where errors in E2E tests were not propagating correctly
- Pinned @openzeppelin/hardhat-upgrades to version 3.3.0 in both package.json and package-lock.json
- Improved process termination in E2E tests by adding killport commands for ports 3000 and 3001
- Restructured the justfile to ensure proper cleanup after each test section
- Enhanced readability of the e2e-leader-follower-up function
___
<tr>
<td>
<details>
<summary><strong>package-lock.json</strong><dd><code>Pin OpenZeppelin Hardhat Upgrades dependency</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
> fix: error on e2e not propagating

- Cargo.lock
- Cargo.toml
Enhancement
___
- Removed the 'openssl' dependency with its 'vendored' feature
- Cleaned up dev dependencies by removing:
- 'binary_macros'
- 'fancy-duration'
- 'stringreader'
- These changes help streamline the project's dependencies, potentially reducing build times and minimizing potential security vulnerabilities
___
<tr>
<td>
<details>
<summary><strong>Cargo.toml</strong><dd><code>Remove unused dependencies from Cargo.toml</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
Cargo.toml
<li>Removed unused dependency 'openssl'<br> <li> Removed unused dev dependencies: …
> chore: remove unused deps

- Cargo.toml
- src/eth/storage/permanent/rocks/rocks_cf.rs
- src/eth/storage/permanent/rocks/rocks_config.rs
- src/eth/storage/permanent/rocks/rocks_permanent.rs
- src/eth/storage/permanent/rocks/rocks_state.rs
Enhancement
___
- Introduced a new feature flag "rocks_metrics" for RocksDB-specific metrics collection
- Updated all occurrences of the "metrics" feature flag to "rocks_metrics" in RocksDB-related files
- Modified conditional compilation directives to use the new feature flag
- Adjusted imports and dependencies to align with the new feature flag
- Maintained backwards compatibility by making "rocks_metrics" depend on "metrics"
- This change allows for more granular control over metrics collection, specifically for RocksDB
___
<tr>
<td>
<details>
<summary><strong>rocks_cf.rs</strong><dd><code>Update feature flag for RocksDB metrics</code>&nbsp; …
> chore: put rocks metrics collection behind a feature flag

- e2e/test/admin/e2e-admin-password-enabled.test.ts
- justfile
___
- Added e2e-admin-password test to the stratus-test-coverage recipe, improving overall test coverage.
- Updated killport commands in justfile to use '-s sigterm' flag for more graceful process termination.
- Reorganized the stratus-test-coverage recipe for better efficiency:
- Moved cargo llvm-cov clean and build steps to the beginning of the recipe.
- Added cargo llvm-cov --no-report before running e2e tests.
- Removed a debug console.log statement from the admin password enabled test.
___
<tr>
<td>
<details>
<summary><strong>e2e-admin-password-enabled.test.ts</strong><dd><code>Remove debug logging in admin password …
> chore: add e2e-admin-password test to coverage recipe

- .github/workflows/e2e-leader-follower.yml
- e2e/cloudwalk-contracts/integration/test/leader-follower-change.test.ts
- e2e/cloudwalk-contracts/integration/test/leader-follower-health.test.ts
- justfile
- src/eth/follower/importer/importer.rs
Enhancement
___
- Enhanced the importer to consider network failures in health checks:
- Added tracking of the latest fetched block time
- Implemented a timeout check in the `lag` function to detect communication issues with the leader
- Added a new end-to-end test to verify follower health based on leader miner status:
- Checks follower health when leader miner is disabled
- Verifies follower health recovery when leader miner is re-enabled
- These changes improve the system's ability to detect and respond to network issues between leader and follower nodes
___
<tr>
<td>
<details>
<summary><strong>importer.rs</strong><dd><code>Enhance importer with …
> enha: make the health check consider network failures

- build.rs
- src/eth/executor/evm.rs
- src/eth/external_rpc/postgres.rs
- src/eth/follower/importer/importer.rs
- src/eth/miner/miner.rs
- src/eth/primitives/address.rs
- src/eth/primitives/execution.rs
- src/eth/primitives/external_block.rs
- src/eth/primitives/external_receipt.rs
- src/eth/primitives/log_mined.rs
- src/eth/storage/temporary/inmemory.rs
- src/ext.rs
- src/globals.rs
- src/infra/kafka/kafka.rs
___
- Improved error handling across multiple modules by replacing `expect` and `panic` calls with more robust error handling mechanisms using `Result`, `ok_or_else`, and `anyhow!`.
- Added `#[allow(clippy::expect_used)]`, `#[allow(clippy::unwrap_used)]`, and `#[allow(clippy::panic)]` attributes to specific functions and modules where these operations are deemed necessary or safe.
- Refactored `parse_revm_execution` and `parse_revm_state` functions in the EVM executor to return `Result` types for better error propagation.
- Updated various primitive types and conversions to use `anyhow::Error` for more informative error messages.
- Replaced a `panic!` call with `todo!()` in the `Address` conversion from `NameOrAddress`.
- Made minor adjustments to improve code quality …
> chore: remove/allow panics, expects and unwraps

- justfile
Bug fix
___
- Modified the shebang in the `stratus-test-coverage` recipe from `#!/opt/homebrew/bin/bash` to `#!/bin/bash`
- This change improves portability by using the system's default Bash interpreter instead of a specific path
- Ensures the script can run on different systems without relying on Homebrew's Bash installation
___
<tr>
<td>
<details>
<summary><strong>justfile</strong><dd><code>Update shebang for broader compatibility</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
justfile
<li>Changed shebang from …
> fix: stratus-test-coverage recipe shebang

- Cargo.lock
- Cargo.toml
- crates/stratus_macros/src/lib.rs
- e2e/cloudwalk-contracts/integration/test/leader-follower-change.test.ts
- e2e/cloudwalk-contracts/integration/test/leader-follower-health.test.ts
- e2e/cloudwalk-contracts/integration/test/leader-follower-importer.test.ts
- e2e/cloudwalk-contracts/integration/test/leader-follower-miner.test.ts
- e2e/test/admin/e2e-admin-password-enabled.test.ts
- e2e/test/automine/e2e-json-rpc.test.ts
- e2e/test/external/e2e-json-rpc.test.ts
- src/eth/follower/importer/importer.rs
- src/eth/primitives/stratus_error.rs
- src/eth/rpc/rpc_server.rs
___
- Derive error codes using ErrorCode trait
- Refactor error handling and logging
- Update error codes in e2e tests
- Improve code organization and imports
___
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><details><summary>2 files</summary><table>
<tr>
<td><strong>lib.rs</strong><dd><code>Implement ErrorCode derive macro</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></td>
<td><a href="https://github.com/cloudwalk/stratus/pull/1938/files#diff-aa54e2be264adf5d6c46d60aae8c43a6e73f438bbd1425de7653afb7e907ba1c">+10/-2</a>&nbsp; &nbsp; </td>
</tr>
<tr> …
> feat: derive error codes using the ErrorCode trait

- Cargo.lock
- Cargo.toml
- e2e/test/automine/e2e-json-rpc.test.ts
- src/eth/primitives/mod.rs
- src/eth/rpc/mod.rs
- src/eth/rpc/proxy_get_request.rs
- src/eth/rpc/rpc_server.rs
- src/eth/storage/permanent/rocks/types/mod.rs
Temporary until https://github.com/paritytech/jsonrpsee/pull/1512 is merged and released. If the changes in the jsonrpsee repo are not accepted we'll make these changes permanent.
___
___
- Implement temporary proxy layer for GET requests
- Update jsonrpsee dependency and add related packages
- Modify RPC middleware and server configurations
- Adjust error handling in RPC responses
___
<tr>
<td>
<details>
<summary><strong>mod.rs</strong><dd><code>Add ErrorCode to public exports</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
> fix: implement a temporary proxy layer for get requests

- crates/stratus_macros/src/lib.rs
Enhancement
___
- Add major_error_code attribute to ErrorCode derive macro
- Implement major error code offset for enum variants
- Update error code calculation in derive implementation
- Adjust test case to include major error code
___
<tr>
<td>
<details>
<summary><strong>lib.rs</strong><dd><code>Implement major error code attribute for ErrorCode derive macro</code></dd></summary>
<hr>
crates/stratus_macros/src/lib.rs
<li>Added major_error_code attribute parsing<br> <li> Implemented major error code offset for enum variants<br> <li> Updated error code calculation in derive implementation<br> <li> Adjusted test case to include major error code attribute …
> enha: add major_error_code attribute to the ErrorCode derive macro

- e2e/contracts/TestRevertReason.sol
- e2e/test/helpers/rpc.ts
- src/eth/codegen.rs
- src/eth/executor/evm.rs
- src/eth/executor/executor.rs
- src/eth/primitives/execution.rs
- src/eth/primitives/execution_result.rs
- src/eth/primitives/stratus_error.rs
- src/eth/rpc/rpc_middleware.rs
- src/eth/rpc/rpc_server.rs
- src/eth/storage/permanent/rocks/types/execution_result.rs
- src/infra/metrics/metrics_definitions.rs
- static/contracts-signatures/TestRevertReason.signatures
TODO: handle revert reasons with encoded strings (DONE)
___
Enhancement
___
- Include error signature in logs for reverted transactions
- Add function_sig_for_o11y_opt for optional signature lookup
- Improve error logging in eth_send_raw_transaction
- Use Cow for efficient string handling
___
<tr>
<td>
<details>
<summary><strong>codegen.rs</strong><dd><code>Add optional function signature lookup</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
src/eth/codegen.rs
<li>Added function_sig_for_o11y_opt for optional signature lookup<br> <li> Modified …
> enha: include error signature in logs when transactions revert

- justfile
- utils/deploy/deploy.py
Enhancement
___
- Add conditional logic for E2E test execution
- Support different block modes in Stratus E2E tests
- Improve test command flexibility in e2e-stratus-rocks recipe
___
<tr>
<td>
<details>
<summary><strong>justfile</strong><dd><code>Add conditional E2E test execution based on block mode</code>&nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
justfile
<li>Added conditional logic to handle different block modes<br> <li> Introduced support for interval-based and block-mode-based E2E tests<br> <li> Improved flexibility in test command execution
</details>
</td>
<td><a href="https://github.com/cloudwalk/stratus/pull/1957/files#diff-deb9bb56fb122db0b605aa5 …
> fix(justfile,deploy.py): add test command in e2e stratus rocks recipes and add raise

- Cargo.lock
- e2e/rpc-mock-server/package-lock.json
Reverts cloudwalk/stratus#1953
___
Enhancement
___
- Revert Express.js update to 4.20.0
- Downgrade cookie package to 0.6.0
- Revert finalhandler to 1.2.0
- Downgrade qs package to 6.11.0
___
<tr>
<td>
<details>
<summary><strong>package-lock.json</strong><dd><code>Revert npm package versions in package-lock.json</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
e2e/rpc-mock-server/package-lock.json
<li>Reverted Express.js from 4.21.2 to 4.20.0<br> <li> Downgraded cookie package from 0.7.1 to 0.6.0<br> <li> Reverted finalhandler from 1.3.1 to 1.2.0<br> <li> Downgraded qs package from 6.13.0 to 6.11.0
</details> …
> Revert "Revert "deps: update url and mock server npm packages""

- e2e/test/automine/e2e-json-rpc.test.ts
- src/eth/primitives/transaction_stage.rs
- src/eth/rpc/rpc_server.rs
- src/eth/storage/permanent/rocks/types/execution.rs
- src/eth/storage/permanent/rocks/types/execution_result.rs
Enhancement
___
- Implement stratus_getTransactionResult RPC method
- Add result() method to TransactionStage
- Refactor ExecutionResult handling in storage
- Add e2e tests for new RPC method
___
<tr>
<td>
<details>
<summary><strong>transaction_stage.rs</strong><dd><code>Add result() method to TransactionStage</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
src/eth/primitives/transaction_stage.rs
- Import ExecutionResult
- Add result() method to TransactionStage
</details>
</td>
<td><a href="https://github.com/cloudwalk/stratus/pull/1959/files#diff-01de …
> feat: implement stratus_getTransactionResult

- .github/workflows/build-pgo.yml
Enhancement
___
- Remove protoc installation from build-pgo workflow
- Streamline CI process by eliminating unnecessary dependency
___
```mermaid
flowchart LR
A["GitHub Action Workflow"] -- "Removes" --> B["protoc installation"]
A -- "Retains" --> C["Other dependencies"]
```
<tr>
<td>
<details>
<summary><strong>build-pgo.yml</strong><dd><code>Remove protoc installation step from build-pgo workflow</code>&nbsp; &nbsp; </dd></summary>
<hr>
.github/workflows/build-pgo.yml
<ul><li>Removed the step to install protobuf-compiler (protoc)<br> <li> Kept other dependency installations like …
> chore: remove protoc and rust cache from build-pgo action

- Cargo.lock
- Cargo.toml
Enhancement
___
- Update serialization crates: `serde`, `serde_json`, `serde_with`
- Upgrade collection crates: `indexmap`, `smallvec`
- Bump `hash_hasher` to version 2.0.4
___
```mermaid
flowchart LR
A["Cargo.toml"] --> B["Serialization Updates"]
A --> C["Collection Updates"]
B --> D["serde 1.0.219"]
B --> E["serde_json 1.0.141"]
B --> F["serde_with 3.14.0"]
C --> G["indexmap 2.10.0"]
C --> H["smallvec 1.15.1"]
A --> I["hash_hasher 2.0.4"]
```
<tr>
<td>
<details>
<summary><strong>Cargo.toml</strong><dd><code>Update serialization and collection crates versions</code>&nbsp; &nbsp; &nbsp; &nbsp; …
> chore: bump crates serialization + collections

- Cargo.lock
- Cargo.toml
Enhancement
___
- Update network-related crates: `reqwest`, `tower`, `http`
- Upgrade logging and tracing crates
- Bump `http-body-util` to newer version
- Maintain compatibility with existing dependencies
___
```mermaid
flowchart LR
A["Cargo.toml"] --> B["Network Updates"]
A --> C["Logging Updates"]
B --> D["reqwest 0.12.22"]
B --> E["tower 0.5.2"]
B --> F["http 1.3.1"]
C --> G["log 0.4.27"]
C --> H["tracing 0.1.41"]
C --> I["tracing-subscriber 0.3.19"]
```
<tr>
<td>
<details>
<summary><strong>Cargo.toml</strong><dd><code>Update network and logging dependencies</code>&nbsp; &nbsp; &nbsp; &nbsp; …
> chore: bump creates logging, network

- Cargo.lock
- Cargo.toml
Other
___
- Update `derive_more` crate from 0.99.17 to 2.0.1
___
```mermaid
flowchart LR
A["derive_more v0.99.17"] --> B["derive_more v2.0.1"]
```
<tr>
<td>
<details>
<summary><strong>Cargo.toml</strong><dd><code>Update derive_more dependency version</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
Cargo.toml
- Bumped `derive_more` crate version from 0.99.17 to 2.0.1
</details>
</td>
<td><a href="https://github.com/cloudwalk/stratus/pull/2217/files#diff-2e9d962a08321605940b5a657135052 …
> chore: bump derive_more crate

- .github/workflows/check-unused-deps.yml
Enhancement
___
- Simplified unused dependencies check using Just
- Added setup for Just command runner
- Removed manual cargo udeps execution and output parsing
- Streamlined workflow for better maintainability
___
```mermaid
flowchart LR
A["Manual cargo udeps"] --> B["Just command"]
C["Output parsing"] --> D["Simplified check"]
E["Workflow steps"] --> F["Streamlined process"]
```
<tr>
<td>
<details>
<summary><strong>check-unused-deps.yml</strong><dd><code>Simplify unused dependencies check using Just</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
> chore: show full output on check unused deps workflow

- src/eth/miner/miner.rs
- src/eth/storage/stratus_storage.rs
Enhancement
___
- Moved `set_mined_block_number` call to `save_block` method
- Improved block saving process in `StratusStorage`
- Removed `set_mined_block_number` from `Miner` implementation
- Enhanced error handling in `save_block` method
___
```mermaid
flowchart LR
Miner["Miner"]
SaveBlock["save_block()"]
SetMinedBlockNumber["set_mined_block_number()"]
Miner -- "Calls" --> SaveBlock
SaveBlock -- "Now includes" --> SetMinedBlockNumber
```
<tr>
<td>
<details>
<summary><strong>miner.rs</strong><dd><code>Remove mined block number setting from Miner</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …
> chore: set mined block number in save_block instead of miner

- src/eth/executor/evm.rs
- src/eth/primitives/block.rs
- src/eth/primitives/execution.rs
- src/eth/primitives/execution_account_changes.rs
- src/eth/storage/cache.rs
- src/eth/storage/permanent/rocks/rocks_state.rs
- src/eth/storage/permanent/rocks/types/block_changes.rs
- src/eth/storage/temporary/inmemory/transaction.rs
Enhancement
___
- Remove `new_account` and `address` from ExecutionAccountChanges
- Update related code to use address from map
- Refactor compact_account_changes to return ExecutionChanges
- Adjust function signatures and implementations accordingly
___
```mermaid
flowchart LR
A["ExecutionAccountChanges"]
B["Remove fields"]
C["Update usage"]
D["Refactor functions"]
A --> B
B --> C
C --> D
B --"new_account"--> E["Removed"]
B --"address"--> E
C --"Use map key"--> F["Address"]
D --"Return type"--> G["ExecutionChanges"]
```
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><details><summary>8 files</summary><table>
<tr> …
> chore: remove new_account and address from ExecutionAccountChanges

- Cargo.toml
- src/eth/executor/evm.rs
Enhancement
___
- Disable EIP-3607 for eth_call operations
- Update revm dependency to include optional_eip3607 feature
___
```mermaid
flowchart LR
A["EVM Configuration"] --> B["Disable EIP-3607"]
B --> C["eth_call operations"]
D["revm dependency"] --> E["Add optional_eip3607 feature"]
```
<tr>
<td>
<details>
<summary><strong>evm.rs</strong><dd><code>Disable EIP-3607 for eth_call in EVM configuration</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
<ul><li>Added <code>cfg_env.disable_eip3607 = matches!(kind, EvmKind::Call);</code> to <br>disable …
> enha: disable EIP-3607 on eth_call

- src/eth/executor/evm.rs
Enhancement
___
- Remove clippy allow attribute for arc_with_non_send_sync
___
```mermaid
flowchart LR
A["Evm::new method"] -- "Remove" --> B["clippy ignore"]
B -- "Improves" --> C["Code quality"]
```
<tr>
<td>
<details>
<summary><strong>evm.rs</strong><dd><code>Remove clippy ignore for arc_with_non_send_sync</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
<ul><li>Removed #[allow(clippy::arc_with_non_send_sync)] attribute from <br>Evm::new method</ul>
</details>
</td>
<td><a …
> chore: remove allow(clippy::arc_with_non_send_sync) from Evm::new(\3)

- Cargo.lock
- Cargo.toml
- e2e/test/external/e2e-json-rpc.test.ts
- src/eth/executor/evm.rs
Enhancement
___
- Implemented JS Tracer for EVM execution
- Added support for custom JavaScript tracing
- Integrated JsInspector in EVM execution flow
- Added E2E tests for JS tracing functionality
___
```mermaid
flowchart LR
A["EVM Execution"] --> B["JsInspector"]
B --> C["Custom JS Tracer"]
C --> D["Trace Results"]
E["E2E Tests"] --> F["Verify JS Tracing"]
```
<tr>
<td>
<details>
<summary><strong>evm.rs</strong><dd><code>Integrate JsInspector into EVM execution flow</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr> …
> feat: Js Tracer

- src/eth/executor/executor.rs
Bug fix
___
- Check sender's nonce on reverted external transactions
- Improve error handling for failed external transactions
- Ensure correct nonce for failed external transactions
___
```mermaid
flowchart LR
A["External Transaction"] --> B{"Is Failed?"}
B -->|Yes| C["Check Sender's Nonce"]
C -->|Mismatch| D["Throw Error"]
C -->|Match| E["Process Failed Transaction"]
B -->|No| F["Normal Execution"]
```
<tr>
<td>
<details>
<summary><strong>executor.rs</strong><dd><code>Add nonce validation for failed external transactions</code>&nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr> …
> fix(importer): check sender's nonce on reverted external transaction

- .github/workflows/build-binary.yml
This solution addresses the build process's instability, which has been causing intermittent "out of space" errors.
closes #74
___
Enhancement, Other
___
- Clean cargo target before building debug binaries
- Optimize CI process to prevent "out of space" errors
___
```mermaid
flowchart LR
A["CI Workflow"] --> B["Clean cargo target"]
B --> C["Build Debug binaries"]
C --> D["Cache Rust artifacts"]
```
<tr>
<td>
<details>
<summary><strong>build-binary.yml</strong><dd><code>Add cargo clean step before building debug binaries</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr> …
> ci: Clean cargo target before doing build for cache.
